function result = analyze_4ch_dpll_tracking(config)
%ANALYZE_4CH_DPLL_TRACKING 四路同步采集下的DPLL追踪闭合分析。

addpath(config.simudateDirectory);

pciPath = fullfile(config.dataDirectory, config.pciFileName);
fileInfo = dir(pciPath);
fileSampleCount = (fileInfo.bytes - config.headerBytes) / ...
    (2 * config.channelCount);
sampleCount = min(fileSampleCount, floor(config.processingEndRawSample));
if isfinite(config.processingEndRawSample) && ...
        config.processingEndRawSample > fileSampleCount
    fprintf('配置截止点超过文件总长度，自动按文件末尾%d点处理。\n', ...
        fileSampleCount);
end
tag = string(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
[~, datasetName] = fileparts(pciPath);
outputDirectory = fullfile(config.outputParentDirectory, ...
    datasetName + "_" + tag);
figureDirectory = fullfile(outputDirectory, "figures");
tableDirectory = fullfile(outputDirectory, "tables");
mkdir(figureDirectory);
mkdir(tableDirectory);

fprintf('\n=== 四通道DPLL追踪分析 ===\n');
fprintf('文件：%s\n', pciPath);
fprintf('每通道点数：%d；时长：%.6f s\n', ...
    sampleCount, sampleCount / config.sampleRateHz);
if sampleCount < fileSampleCount
    fprintf('已按配置截断：文件共%d点，本次只处理1 .. %d。\n', ...
        fileSampleCount, sampleCount);
end
fprintf('结果：%s\n', outputDirectory);

%% CH1：先建立双峰身份，后续只使用主采样峰
fprintf('\n[1/5] 读取CH%d并识别双峰...\n', config.pulseChannel);
pulseVolts = (read_pci_channel(pciPath, config.pulseChannel, ...
    sampleCount, config) - 8192) / 8192;
pulseVolts = pulseVolts - median(pulseVolts);
peaks = locate_double_peaks(pulseVolts, config);
make_peak_identification_figure(pulseVolts, peaks, config, ...
    figureDirectory);
clear pulseVolts

peakTime = (peaks.samplingLocation - 1) / config.sampleRateHz;
interactionTime = (peaks.interactionLocation - 1) / ...
    config.sampleRateHz;
fprintf('双峰周期：%d；两峰平均间隔：%.3f us\n', ...
    numel(peakTime), 1e6 * mean(peakTime - interactionTime));

%% CH4：FPGA定点CIC/DC Block，之后用双精度IQ累积相位
fprintf('\n[2/5] 处理CH%d参考输入...\n', config.referenceChannel);
frontendMat = fullfile(outputDirectory, ...
    datasetName + "_ch" + config.referenceChannel + ...
    "_CIC_DCBlock_3M125.mat");
extract_pci_reference_frontend(pciPath, frontendMat, ...
    dataset_id=datasetName, ...
    frontend_mex_dir=config.frontendMexDirectory, ...
    channel_count=config.channelCount, ...
    channel_index=config.referenceChannel, ...
    maximum_source_samples=sampleCount, ...
    compute_source_sha256=false);
frontend = load(frontendMat, 'frontendOutput', 'metadata');
referenceCic = reference_analysis.estimate_iq_phase( ...
    frontend.frontendOutput, frontend.metadata.outputSampleRate, ...
    observation_rate_hz=config.referenceObservationRateHz, ...
    iq_window_s=config.referenceIqWindowSeconds, ...
    frequency_aperture_s=config.frequencyApertureSeconds);
referenceCic.time_s = referenceCic.time_s - ...
    config.cicGroupDelaySeconds;
clear frontend

referenceRawCodes = read_pci_channel(pciPath, ...
    config.referenceChannel, sampleCount, config);
referenceRaw = reference_analysis.estimate_iq_phase( ...
    referenceRawCodes, config.sampleRateHz, ...
    carrier_frequency_hz=referenceCic.carrier_frequency_hz, ...
    observation_rate_hz=config.referenceObservationRateHz, ...
    iq_window_s=config.referenceIqWindowSeconds, ...
    frequency_aperture_s=config.frequencyApertureSeconds);
clear referenceRawCodes

%% CH2：直接从500倍DDS正弦重建连续相位
fprintf('\n[3/5] 处理CH%d自适应时钟...\n', ...
    config.adaptiveClockChannel);
clockCodes = read_pci_channel(pciPath, ...
    config.adaptiveClockChannel, sampleCount, config);
adaptiveClock = reference_analysis.estimate_iq_phase( ...
    clockCodes, config.sampleRateHz, ...
    observation_rate_hz=config.clockObservationRateHz, ...
    iq_window_s=config.clockIqWindowSeconds, ...
    frequency_aperture_s=config.frequencyApertureSeconds);
clear clockCodes

%% 在同一组主采样峰端点上建立误差恒等式
refPhaseCic = interp1(referenceCic.time_s, ...
    referenceCic.phase_cycles, peakTime, 'pchip');
refPhaseRaw = interp1(referenceRaw.time_s, ...
    referenceRaw.phase_cycles, peakTime, 'pchip');
clockPhase = interp1(adaptiveClock.time_s, ...
    adaptiveClock.phase_cycles, peakTime, 'pchip');
referenceCrossingTime = (referenceCic.crossing_index - 1) / ...
    referenceCic.sample_rate_hz - config.cicGroupDelaySeconds;
referencePhaseCrossing = phase_from_crossings(referenceCrossingTime, ...
    referenceCic.crossing_cycle, peakTime, ...
    config.referenceIqWindowSeconds);
clockCrossingTime = (adaptiveClock.crossing_index - 1) / ...
    adaptiveClock.sample_rate_hz;
clockPhaseCrossing = phase_from_crossings(clockCrossingTime, ...
    adaptiveClock.crossing_cycle, peakTime, config.clockIqWindowSeconds);

interval.startTime_s = peakTime(1:end - 1);
interval.endTime_s = peakTime(2:end);
interval.midTime_s = 0.5 * (interval.startTime_s + ...
    interval.endTime_s);
interval.pulseSpacing_62M5 = diff(peaks.samplingLocation);
interval.pulseDuration_s = diff(peakTime);
interval.pulseEquivalentFrequency_Hz = ...
    config.referenceCyclesPerPulse ./ interval.pulseDuration_s;
interval.referenceCyclesCic = diff(refPhaseCic);
interval.referenceCyclesRaw = diff(refPhaseRaw);
interval.referenceCyclesCicCrossing = diff(referencePhaseCrossing);
interval.clockCycles500 = diff(clockPhase);
interval.clockCycles500Crossing = diff(clockPhaseCrossing);
interval.referenceAverageFrequencyCic_Hz = ...
    interval.referenceCyclesCic ./ interval.pulseDuration_s;
interval.referenceAverageFrequencyRaw_Hz = ...
    interval.referenceCyclesRaw ./ interval.pulseDuration_s;
interval.clockEquivalentFrequency_Hz = interval.clockCycles500 ./ ...
    (config.capturedClockMultiplier * interval.pulseDuration_s);
interval.referencePulseFrequencyMismatch_Hz = ...
    interval.referenceAverageFrequencyCic_Hz - ...
    interval.pulseEquivalentFrequency_Hz;
interval.clockReferenceFrequencyMismatch_Hz = ...
    interval.clockEquivalentFrequency_Hz - ...
    interval.referenceAverageFrequencyCic_Hz;

M = config.capturedClockMultiplier;
R = config.referenceCyclesPerPulse;
interval.finalError500 = interval.clockCycles500 - M * R;
interval.referenceEvent500 = M * (interval.referenceCyclesCic - R);
interval.pllTracking500 = interval.clockCycles500 - ...
    M * interval.referenceCyclesCic;
interval.closure500 = interval.finalError500 - ...
    interval.referenceEvent500 - interval.pllTracking500;
interval.finalError500Crossing = interval.clockCycles500Crossing - M * R;
interval.referenceEvent500Crossing = M * ...
    (interval.referenceCyclesCicCrossing - R);
interval.pllTracking500Crossing = interval.clockCycles500Crossing - ...
    M * interval.referenceCyclesCicCrossing;
interval.closure500Crossing = interval.finalError500Crossing - ...
    interval.referenceEvent500Crossing - interval.pllTracking500Crossing;

% 四种相位测量组合。第一个后缀是CH2，第二个后缀是CH4。
interval.pllTracking500Ch2IqCh4Iq = interval.pllTracking500;
interval.pllTracking500Ch2IqCh4Crossing = interval.clockCycles500 - ...
    M * interval.referenceCyclesCicCrossing;
interval.pllTracking500Ch2CrossingCh4Iq = ...
    interval.clockCycles500Crossing - M * interval.referenceCyclesCic;
interval.pllTracking500Ch2CrossingCh4Crossing = ...
    interval.pllTracking500Crossing;

scaleToReport = config.reportClockMultiplier / M;
interval.finalError2000 = scaleToReport * interval.finalError500;
interval.referenceEvent2000 = scaleToReport * ...
    interval.referenceEvent500;
interval.pllTracking2000 = scaleToReport * interval.pllTracking500;
interval.closure2000 = scaleToReport * interval.closure500;
interval.finalError2000Crossing = scaleToReport * ...
    interval.finalError500Crossing;
interval.referenceEvent2000Crossing = scaleToReport * ...
    interval.referenceEvent500Crossing;
interval.pllTracking2000Crossing = scaleToReport * ...
    interval.pllTracking500Crossing;
interval.closure2000Crossing = scaleToReport * ...
    interval.closure500Crossing;
interval.pllTracking2000Ch2IqCh4Iq = scaleToReport * ...
    interval.pllTracking500Ch2IqCh4Iq;
interval.pllTracking2000Ch2IqCh4Crossing = scaleToReport * ...
    interval.pllTracking500Ch2IqCh4Crossing;
interval.pllTracking2000Ch2CrossingCh4Iq = scaleToReport * ...
    interval.pllTracking500Ch2CrossingCh4Iq;
interval.pllTracking2000Ch2CrossingCh4Crossing = scaleToReport * ...
    interval.pllTracking500Ch2CrossingCh4Crossing;
interval.ch2IqToCrossingEffect2000 = ...
    interval.pllTracking2000Ch2CrossingCh4Iq - ...
    interval.pllTracking2000Ch2IqCh4Iq;
interval.ch4IqToCrossingEffect2000 = ...
    interval.pllTracking2000Ch2IqCh4Crossing - ...
    interval.pllTracking2000Ch2IqCh4Iq;
interval.iqCrossingCombinationClosure2000 = ...
    interval.pllTracking2000Ch2CrossingCh4Crossing - ...
    interval.pllTracking2000Ch2IqCh4Iq - ...
    interval.ch2IqToCrossingEffect2000 - ...
    interval.ch4IqToCrossingEffect2000;
cyclesToMrad = 2 * pi * 1000 / config.reportClockMultiplier;
interval.finalErrorMrad = cyclesToMrad * interval.finalError2000;
interval.referenceEventMrad = cyclesToMrad * ...
    interval.referenceEvent2000;
interval.pllTrackingMrad = cyclesToMrad * interval.pllTracking2000;

%% CH2/CH4载波只用于判断PCI固定时间轴是否连续
continuity = classify_capture_continuity(peaks.samplingLocation, ...
    referenceCic, adaptiveClock, config);
interval.pulseSpacingOutlier = continuity.pulseSpacingOutlier;
interval.containsClockCrossingOutlier = ...
    continuity.containsClockCrossingOutlier;
interval.containsReferenceCrossingOutlier = ...
    continuity.containsReferenceCrossingOutlier;
interval.containsCarrierDiscontinuity = ...
    continuity.containsCarrierDiscontinuity;
interval.pulseOnlyMissingCandidate = ...
    continuity.pulseOnlyMissingCandidate;
interval.validForTrackingAnalysis = ...
    continuity.validForTrackingAnalysis;
interval.maximumClockCrossingDeviationSamples = ...
    continuity.maximumClockCrossingDeviationSamples;
interval.maximumReferenceCrossingDeviationSamples = ...
    continuity.maximumReferenceCrossingDeviationSamples;

%% CH3：用端点相位差独立预测PLL自身项
fprintf('\n[4/5] 处理CH%d相位残差并扫描固定通道延时...\n', ...
    config.phaseResidualChannel);
phaseVolts = (read_pci_channel(pciPath, ...
    config.phaseResidualChannel, sampleCount, config) - 8192) / 8192;
phaseRadians = config.phaseRadiansPerVolt * phaseVolts;
delaySamples = (-round(config.phaseDelayScanHalfSeconds * ...
    config.sampleRateHz):config.phaseDelayScanStepSamples: ...
    round(config.phaseDelayScanHalfSeconds * config.sampleRateHz)).';
delayCorrelation = zeros(size(delaySamples));
for k = 1:numel(delaySamples)
    phaseAtPeak = mean_at_locations(phaseRadians, ...
        peaks.samplingLocation + delaySamples(k), ...
        config.phaseAverageHalfSamples);
    prediction = phase_prediction(diff(phaseAtPeak), ...
        config.capturedClockMultiplier, config.phasePredictionSign);
    use = interval.validForTrackingAnalysis;
    delayCorrelation(k) = correlation(prediction(use), ...
        interval.pllTracking500(use));
end
[~, bestDelayIndex] = max(delayCorrelation);
bestDelaySamples = delaySamples(bestDelayIndex);
phaseAtPeakZero = mean_at_locations(phaseRadians, ...
    peaks.samplingLocation, config.phaseAverageHalfSamples);
phaseAtPeakBest = mean_at_locations(phaseRadians, ...
    peaks.samplingLocation + bestDelaySamples, ...
    config.phaseAverageHalfSamples);
interval.phasePrediction500Zero = phase_prediction( ...
    diff(phaseAtPeakZero), M, config.phasePredictionSign);
interval.phasePrediction500Best = phase_prediction( ...
    diff(phaseAtPeakBest), M, config.phasePredictionSign);
interval.phasePrediction2000Best = scaleToReport * ...
    interval.phasePrediction500Best;

%% 一个完整脉冲周期宽度的滑动累计
windowSeconds = median(interval.pulseDuration_s);
slideTime = referenceCic.time_s(referenceCic.time_s >= ...
    peakTime(1) + windowSeconds & referenceCic.time_s <= peakTime(end));
referenceNow = interp1(referenceCic.time_s, ...
    referenceCic.phase_cycles, slideTime, 'pchip');
referencePast = interp1(referenceCic.time_s, ...
    referenceCic.phase_cycles, slideTime - windowSeconds, 'pchip');
rawNow = interp1(referenceRaw.time_s, referenceRaw.phase_cycles, ...
    slideTime, 'pchip');
rawPast = interp1(referenceRaw.time_s, referenceRaw.phase_cycles, ...
    slideTime - windowSeconds, 'pchip');
clockNow = interp1(adaptiveClock.time_s, ...
    adaptiveClock.phase_cycles, slideTime, 'pchip');
clockPast = interp1(adaptiveClock.time_s, ...
    adaptiveClock.phase_cycles, slideTime - windowSeconds, 'pchip');

sliding.time_s = slideTime;
sliding.referenceFrequencyCic_Hz = ...
    (referenceNow - referencePast) / windowSeconds;
sliding.referenceFrequencyRaw_Hz = ...
    (rawNow - rawPast) / windowSeconds;
sliding.clockEquivalentFrequency_Hz = ...
    (clockNow - clockPast) / (M * windowSeconds);
sliding.pulseEquivalentFrequency_Hz = interp1(interval.midTime_s, ...
    interval.pulseEquivalentFrequency_Hz, slideTime, 'linear', 'extrap');
sliding.phaseResidualMrad = 1000 * mean_at_locations(phaseRadians, ...
    1 + slideTime * config.sampleRateHz, ...
    config.phaseAverageHalfSamples);
clear phaseRadians phaseVolts

%% 表格、指标和图
fprintf('\n[5/5] 计算指标并保存图表...\n');
intervalTable = build_interval_table(interval, peaks, ...
    phaseAtPeakZero, phaseAtPeakBest);
slidingTable = struct2table(sliding);
delayTable = table(delaySamples, 1e6 * delaySamples / ...
    config.sampleRateHz, delayCorrelation, ...
    'VariableNames', {'delay_samples', 'delay_us', 'correlation'});
segmentTable = build_segment_table(interval);

summary = build_summary(config, referenceCic, referenceRaw, ...
    adaptiveClock, interval, bestDelaySamples, delayCorrelation(bestDelayIndex));
summary.samplingPeakCorrelationMedian = median(peaks.samplingCorrelation);
summary.samplingPeakCorrelationMinimum = min(peaks.samplingCorrelation);
summary.interactionPeakCorrelationMedian = median(peaks.interactionCorrelation);
summary.interactionPeakCorrelationMinimum = min(peaks.interactionCorrelation);
summaryTable = summary_to_table(summary);

writetable(intervalTable, fullfile(tableDirectory, ...
    'interval_metrics.csv'));
writetable(slidingTable, fullfile(tableDirectory, ...
    'sliding_one_pulse_window.csv'));
writetable(delayTable, fullfile(tableDirectory, ...
    'phase_delay_scan.csv'));
writetable(segmentTable, fullfile(tableDirectory, ...
    'segment_metrics.csv'));
writetable(summaryTable, fullfile(tableDirectory, ...
    'summary_metrics.csv'));
writetable(continuity.summaryTable, fullfile(tableDirectory, ...
    'capture_continuity_summary.csv'));
writetable(continuity.clockCrossingOutlierTable, ...
    fullfile(tableDirectory, 'ch2_crossing_outliers.csv'));
writetable(continuity.referenceCrossingOutlierTable, ...
    fullfile(tableDirectory, 'ch4_cic_crossing_outliers.csv'));

make_overview_figure(interval, phaseAtPeakBest, config, figureDirectory);
make_sliding_figure(sliding, config, figureDirectory);
make_reference_crosscheck_figure(interval, sliding, config, ...
    figureDirectory);
make_decomposition_figure(interval, config, figureDirectory);
make_phase_validation_figure(interval, phaseAtPeakBest, ...
    delayTable, bestDelaySamples, config, figureDirectory);
make_peak_reference_pll_relation_figure(interval, config, figureDirectory);
make_capture_continuity_figure(interval, continuity, config, ...
    figureDirectory);

result.schemaVersion = 1;
result.createdAt = char(datetime('now', ...
    'Format', 'yyyy-MM-dd HH:mm:ss Z'));
result.pciPath = char(pciPath);
result.outputDirectory = char(outputDirectory);
result.config = config;
result.peaks = peaks;
result.referenceCic = compact_phase(referenceCic);
result.referenceRaw = compact_phase(referenceRaw);
result.adaptiveClock = compact_phase(adaptiveClock);
result.interval = interval;
result.sliding = sliding;
result.phaseAtPeakZero_rad = phaseAtPeakZero;
result.phaseAtPeakBest_rad = phaseAtPeakBest;
result.phaseDelayScan = delayTable;
result.captureContinuity = continuity;
result.summary = summary;
result.posteriorPeakDataUsedForController = false;
result.phaseDelayScanPosteriorDiagnosticOnly = true;
save(fullfile(outputDirectory, 'four_channel_tracking_analysis.mat'), ...
    'result', '-v7.3');

fprintf('\n=== 主要结果 ===\n');
fprintf('CH4参考频率：%.6f Hz\n', referenceCic.carrier_frequency_hz);
fprintf('CH2时钟频率：%.6f Hz；倍频比：%.9f\n', ...
    adaptiveClock.carrier_frequency_hz, ...
    adaptiveClock.carrier_frequency_hz / referenceCic.carrier_frequency_hz);
fprintf('2000倍等效最终/reference-event/PLL RMS：%.6f / %.6f / %.6f cycles\n', ...
    summary.finalRms2000, summary.referenceEventRms2000, ...
    summary.pllTrackingRms2000);
fprintf(['时间轴连续且峰间距正常%d段：最终/reference-event/PLL RMS ' ...
    '%.6f / %.6f / %.6f cycles\n'], ...
    summary.validIntervalCount, summary.validFinalRms2000, ...
    summary.validReferenceEventRms2000, summary.validPllTrackingRms2000);
fprintf(['采集载波断点%d段；仅CH1缺脉冲候选%d段；' ...
    '全部原样保留在MAT/CSV中\n'], ...
    summary.carrierDiscontinuityIntervalCount, ...
    summary.pulseOnlyMissingCandidateCount);
fprintf('正过零交叉核验最终/reference-event/PLL RMS：%.6f / %.6f / %.6f cycles\n', ...
    summary.finalRms2000Crossing, ...
    summary.referenceEventRms2000Crossing, ...
    summary.pllTrackingRms2000Crossing);
fprintf('闭合残差最大值：%.3e cycles\n', ...
    summary.closurePeak2000);
fprintf('IQ/亚采样正过零交叉差异：CH4 %.6f；CH2 %.6f cycles RMS\n', ...
    summary.referenceIqCrossingDifferenceRms2000, ...
    summary.clockIqCrossingDifferenceRms2000);
fprintf(['PLL四组合RMS [CH2, CH4] IQ/IQ %.6f；IQ/ZC %.6f；' ...
    'ZC/IQ %.6f；ZC/ZC %.6f cycles\n'], ...
    summary.pllTrackingRms2000Ch2IqCh4Iq, ...
    summary.pllTrackingRms2000Ch2IqCh4Crossing, ...
    summary.pllTrackingRms2000Ch2CrossingCh4Iq, ...
    summary.pllTrackingRms2000Ch2CrossingCh4Crossing);
fprintf(['有效区间只切换CH2/只切换CH4/两者同时切换的差异RMS：' ...
    '%.6f / %.6f / %.6f cycles；组合闭合峰值 %.3e\n'], ...
    summary.validCh2IqToCrossingEffectRms2000, ...
    summary.validCh4IqToCrossingEffectRms2000, ...
    summary.validMatchedIqToCrossingEffectRms2000, ...
    summary.iqCrossingCombinationClosurePeak2000);
fprintf('CH3预测PLL项：零延时 r=%.4f；诊断最佳延时 %.3f us, r=%.4f\n', ...
    summary.phaseCorrelationZero, summary.bestPhaseDelayUs, ...
    summary.phaseCorrelationBest);
fprintf('结果目录：%s\n', outputDirectory);
end

function codes = read_pci_channel(path, channel, sampleCount, config)
fileId = fopen(path, 'r', 'l');
fseek(fileId, config.headerBytes + 2 * (channel - 1), 'bof');
codes = fread(fileId, [sampleCount 1], 'uint16=>double', ...
    2 * (config.channelCount - 1));
fclose(fileId);
if codes(1) >= 32768, codes(1) = codes(1) - 32768; end
end

function peaks = locate_double_peaks(signal, config)
fs = config.sampleRateHz;
nominalPeriod = fs * config.referenceCyclesPerPulse / ...
    config.nominalReferenceHz;
[~, bootstrapSampling] = findpeaks(-signal, ...
    'MinPeakHeight', config.samplingPeakMinimumVolts, ...
    'MinPeakDistance', round(0.70 * nominalPeriod));
bootstrapTemplate = median_template(signal, bootstrapSampling, ...
    config.samplingTemplateHalfSamples);
[positiveLocation, positiveAmplitude] = threshold_extrema(signal, ...
    signal >= config.doublePeakEventMinimumVolts, 1);
[negativeLocation, negativeAmplitude] = threshold_extrema(signal, ...
    signal <= -config.doublePeakEventMinimumVolts, -1);
mergeGap = round(config.doublePeakEventMergeSeconds * fs);
[positiveLocation, ~] = merge_events( ...
    positiveLocation, positiveAmplitude, mergeGap);
[negativeLocation, negativeAmplitude] = merge_events( ...
    negativeLocation, negativeAmplitude, mergeGap);

templateHalf = config.samplingTemplateHalfSamples;
inside = negativeLocation > templateHalf & ...
    negativeLocation <= numel(signal) - templateHalf;
negativeLocation = negativeLocation(inside);
negativeAmplitude = negativeAmplitude(inside);
primaryNegative = negativeAmplitude >= config.samplingPeakMinimumVolts;
negativeCorrelation = template_correlation_at_locations( ...
    signal, negativeLocation, bootstrapTemplate);
firstSampling = bootstrapSampling(1);
beforeRange = round(config.interactionBeforeRangeSeconds * fs);
[~, index] = max(signal(firstSampling - beforeRange(2): ...
    firstSampling - beforeRange(1)));
firstInteraction = firstSampling - beforeRange(2) + index - 1;
targetPairOffset = firstSampling - firstInteraction;

pairTolerance = round(config.doublePeakPairToleranceSeconds * fs);
pairIndex = pair_double_peaks(positiveLocation, negativeLocation, ...
    targetPairOffset, pairTolerance);
pairedSampling = primaryNegative & pairIndex > 0 & ...
    negativeCorrelation >= config.samplingTemplateMinimumCorrelation;
samplingLocation = negativeLocation(pairedSampling);
selectedPairIndex = pair_double_peaks(positiveLocation, samplingLocation, ...
    targetPairOffset, pairTolerance);
interactionLocation = positiveLocation(selectedPairIndex);

% 相互作用峰只用于双峰身份确认；只细化后续实际使用的主采样峰。
[samplingLocation, samplingCorrelation] = refine_template_locations( ...
    signal, samplingLocation, bootstrapTemplate, ...
    config.samplingTemplateRefineHalfSamples);
samplingTemplate = median_template(signal, samplingLocation, templateHalf);
interactionTemplate = median_template(signal, interactionLocation, templateHalf);
interactionCorrelation = template_correlation_at_locations( ...
    signal, interactionLocation, interactionTemplate);

peaks.samplingLocation = samplingLocation;
peaks.interactionLocation = interactionLocation;
peaks.samplingCorrelation = samplingCorrelation;
peaks.interactionCorrelation = interactionCorrelation;
peaks.separationSamples = samplingLocation - interactionLocation;
peaks.samplingTemplate = samplingTemplate;
peaks.interactionTemplate = interactionTemplate;
peaks.nominalPeriodSamples = nominalPeriod;
peaks.bootstrapSamplingCount = numel(bootstrapSampling);
peaks.positiveEventCount = numel(positiveLocation);
peaks.negativeEventCount = numel(negativeLocation);
peaks.strongNegativeCount = nnz(primaryNegative);
peaks.completeDoublePairCount = numel(samplingLocation);
end

function [location, amplitude] = threshold_extrema(signal, mask, polarity)
index = find(mask);
breaks = [0; find(diff(index) > 1); numel(index)];
location = zeros(numel(breaks) - 1, 1);
amplitude = zeros(size(location));
for k = 1:numel(location)
    region = index(breaks(k) + 1:breaks(k + 1));
    [amplitude(k), position] = max(polarity * signal(region));
    location(k) = region(position);
end
end

function [location, amplitude] = merge_events(location, amplitude, gap)
mergedLocation = location(1);
mergedAmplitude = amplitude(1);
for k = 2:numel(location)
    if location(k) - mergedLocation(end) <= gap
        if amplitude(k) > mergedAmplitude(end)
            mergedLocation(end) = location(k);
            mergedAmplitude(end) = amplitude(k);
        end
    else
        mergedLocation(end + 1, 1) = location(k); %#ok<AGROW>
        mergedAmplitude(end + 1, 1) = amplitude(k); %#ok<AGROW>
    end
end
location = mergedLocation;
amplitude = mergedAmplitude;
end

function pairIndex = pair_double_peaks(positiveLocation, negativeLocation, ...
    targetOffset, tolerance)
pairIndex = zeros(size(negativeLocation));
for k = 1:numel(negativeLocation)
    distance = negativeLocation(k) - positiveLocation;
    candidate = find(abs(distance - targetOffset) <= tolerance);
    if isempty(candidate), continue; end
    [~, nearest] = min(abs(distance(candidate) - targetOffset));
    pairIndex(k) = candidate(nearest);
end
end

function correlation = template_correlation_at_locations( ...
    signal, locations, template)
offset = (-(numel(template) - 1) / 2:(numel(template) - 1) / 2).';
correlation = zeros(size(locations));
for k = 1:numel(locations)
    value = signal(round(locations(k)) + offset);
    value = value - mean(value);
    correlation(k) = sum(value .* template) / ...
        sqrt(sum(value.^2) * sum(template.^2));
end
end

function [location, correlation] = refine_template_locations( ...
    signal, location, template, searchHalf)
template = template(:);
templateOffset = (-(numel(template) - 1) / 2: ...
    (numel(template) - 1) / 2).';
lag = (-searchHalf:searchHalf).';
correlation = zeros(size(location));
for k = 1:numel(location)
    center = round(location(k));
    score = zeros(size(lag));
    for n = 1:numel(lag)
        value = signal(center + lag(n) + templateOffset);
        value = value - mean(value);
        score(n) = sum(value .* template) / ...
            sqrt(sum(value.^2) * sum(template.^2));
    end
    [correlation(k), index] = max(score);
    fraction = 0;
    if index > 1 && index < numel(score)
        denominator = score(index - 1) - 2 * score(index) + score(index + 1);
        fraction = 0.5 * (score(index - 1) - score(index + 1)) / denominator;
        fraction = max(-0.5, min(0.5, fraction));
    end
    location(k) = center + lag(index) + fraction;
end
end

function template = median_template(signal, locations, halfWidth)
offset = (-halfWidth:halfWidth).';
waveform = zeros(numel(offset), numel(locations));
for k = 1:numel(locations)
    waveform(:, k) = signal(round(locations(k)) + offset);
end
template = median(waveform, 2);
template = template - mean(template);
end

function values = mean_at_locations(signal, locations, halfWidth)
locations = round(locations(:));
offset = -halfWidth:halfWidth;
values = zeros(size(locations));
for k = 1:numel(locations)
    values(k) = mean(signal(locations(k) + offset));
end
end

function phase = phase_from_crossings(crossingTime, crossingCycle, ...
    queryTime, windowSeconds)
crossingTime = crossingTime(:);
crossingCycle = crossingCycle(:);
queryTime = queryTime(:);
crossingIndex = (1:numel(crossingTime)).';
leftIndex = round(interp1(crossingTime, crossingIndex, ...
    queryTime - windowSeconds / 2, 'linear'));
rightIndex = round(interp1(crossingTime, crossingIndex, ...
    queryTime + windowSeconds / 2, 'linear'));
phase = zeros(size(queryTime));
for k = 1:numel(queryTime)
    use = leftIndex(k):rightIndex(k);
    localTime = crossingTime(use) - queryTime(k);
    fitValue = [localTime, ones(numel(use), 1)] \ crossingCycle(use);
    phase(k) = fitValue(2);
end
end

function prediction = phase_prediction(deltaPhase, multiplier, signValue)
deltaPhase = angle(exp(1i * deltaPhase));
prediction = signValue * multiplier / (2 * pi) * deltaPhase;
end

function continuity = classify_capture_continuity(peakLocation, ...
    referenceCic, adaptiveClock, config)
clockScale = config.sampleRateHz / adaptiveClock.sample_rate_hz;
referenceScale = config.sampleRateHz / referenceCic.sample_rate_hz;
referenceDelay = config.cicGroupDelaySeconds * config.sampleRateHz;
clockAudit = crossing_continuity_audit(adaptiveClock.crossing_index, ...
    clockScale, 0, config.clockCrossingMinimumDeviationSamples, ...
    config.carrierContinuityMadMultiplier);
referenceAudit = crossing_continuity_audit( ...
    referenceCic.crossing_index, referenceScale, referenceDelay, ...
    config.referenceCrossingMinimumDeviationSamples, ...
    config.carrierContinuityMadMultiplier);

[containsClock, maximumClockDeviation] = map_crossing_outliers( ...
    peakLocation, clockAudit.outlierLocation, ...
    clockAudit.outlierDeviation);
[containsReference, maximumReferenceDeviation] = ...
    map_crossing_outliers(peakLocation, referenceAudit.outlierLocation, ...
    referenceAudit.outlierDeviation);
pulseSpacing = diff(peakLocation);
pulseSpacingMedian = median(pulseSpacing);
pulseSpacingOutlier = abs(pulseSpacing - pulseSpacingMedian) >= ...
    config.pulseSpacingOutlierSamples;
containsCarrierDiscontinuity = containsClock | containsReference;
pulseOnlyMissingCandidate = pulseSpacingOutlier & ...
    ~containsCarrierDiscontinuity;
validForTrackingAnalysis = ~pulseSpacingOutlier & ...
    ~containsCarrierDiscontinuity;

summaryTable = table(numel(pulseSpacing), pulseSpacingMedian, ...
    nnz(pulseSpacingOutlier), clockAudit.crossingCount, ...
    clockAudit.spacingMedian, clockAudit.outlierThreshold, ...
    clockAudit.outlierCount, referenceAudit.crossingCount, ...
    referenceAudit.spacingMedian, referenceAudit.outlierThreshold, ...
    referenceAudit.outlierCount, nnz(containsClock), ...
    nnz(containsReference), nnz(containsCarrierDiscontinuity), ...
    nnz(pulseOnlyMissingCandidate), nnz(validForTrackingAnalysis), ...
    'VariableNames', {'pulse_interval_count', ...
    'pulse_spacing_median_samples', 'pulse_spacing_outlier_count', ...
    'ch2_crossing_count', 'ch2_spacing_median_samples', ...
    'ch2_outlier_threshold_samples', 'ch2_crossing_outlier_count', ...
    'ch4_cic_crossing_count', 'ch4_spacing_median_raw_samples', ...
    'ch4_outlier_threshold_raw_samples', ...
    'ch4_cic_crossing_outlier_count', ...
    'intervals_with_ch2_outlier', 'intervals_with_ch4_outlier', ...
    'intervals_with_carrier_discontinuity', ...
    'pulse_only_missing_candidate_count', 'valid_interval_count'});
clockCrossingOutlierTable = table(clockAudit.outlierLocation, ...
    clockAudit.outlierSpacing, clockAudit.outlierDeviation, ...
    'VariableNames', {'location_raw', 'crossing_spacing_samples', ...
    'spacing_deviation_samples'});
referenceCrossingOutlierTable = table(referenceAudit.outlierLocation, ...
    referenceAudit.outlierSpacing, referenceAudit.outlierDeviation, ...
    'VariableNames', {'location_raw', ...
    'crossing_spacing_raw_samples', 'spacing_deviation_raw_samples'});

continuity.pulseSpacingMedian = pulseSpacingMedian;
continuity.pulseSpacingOutlier = pulseSpacingOutlier;
continuity.containsClockCrossingOutlier = containsClock;
continuity.containsReferenceCrossingOutlier = containsReference;
continuity.containsCarrierDiscontinuity = ...
    containsCarrierDiscontinuity;
continuity.pulseOnlyMissingCandidate = pulseOnlyMissingCandidate;
continuity.validForTrackingAnalysis = validForTrackingAnalysis;
continuity.maximumClockCrossingDeviationSamples = ...
    maximumClockDeviation;
continuity.maximumReferenceCrossingDeviationSamples = ...
    maximumReferenceDeviation;
continuity.clockAudit = clockAudit;
continuity.referenceAudit = referenceAudit;
continuity.summaryTable = summaryTable;
continuity.clockCrossingOutlierTable = clockCrossingOutlierTable;
continuity.referenceCrossingOutlierTable = ...
    referenceCrossingOutlierTable;
end

function audit = crossing_continuity_audit(crossingIndex, scale, ...
    delaySamples, minimumDeviation, madMultiplier)
probeCount = min(numel(crossingIndex), 1e6);
probeSpacing = scale * diff(crossingIndex(1:probeCount));
spacingMedian = median(probeSpacing);
spacingMad = median(abs(probeSpacing - spacingMedian));
outlierThreshold = max(minimumDeviation, ...
    madMultiplier * 1.4826 * spacingMad);

outlierLocation = zeros(0, 1);
outlierSpacing = zeros(0, 1);
chunkCrossings = 5e6;
first = 1;
while first < numel(crossingIndex)
    last = min(first + chunkCrossings, numel(crossingIndex));
    crossing = crossingIndex(first:last);
    spacing = scale * diff(crossing);
    deviation = spacing - spacingMedian;
    use = abs(deviation) >= outlierThreshold;
    midpoint = 1 + (0.5 * (crossing(1:end - 1) + ...
        crossing(2:end)) - 1) * scale - delaySamples;
    outlierLocation = [outlierLocation; midpoint(use)]; %#ok<AGROW>
    outlierSpacing = [outlierSpacing; spacing(use)]; %#ok<AGROW>
    first = last;
end

audit.crossingCount = numel(crossingIndex);
audit.spacingMedian = spacingMedian;
audit.spacingMad = spacingMad;
audit.outlierThreshold = outlierThreshold;
audit.outlierCount = numel(outlierLocation);
audit.outlierLocation = outlierLocation;
audit.outlierSpacing = outlierSpacing;
audit.outlierDeviation = outlierSpacing - spacingMedian;
end

function [containsOutlier, maximumDeviation] = map_crossing_outliers( ...
    peakLocation, outlierLocation, outlierDeviation)
intervalCount = numel(peakLocation) - 1;
bin = discretize(outlierLocation, peakLocation);
inside = isfinite(bin);
containsOutlier = accumarray(bin(inside), true(nnz(inside), 1), ...
    [intervalCount 1], @any, false);
maximumDeviation = accumarray(bin(inside), ...
    abs(outlierDeviation(inside)), [intervalCount 1], @max, 0);
end

function value = correlation(a, b)
matrix = corrcoef(a(:), b(:));
value = matrix(1, 2);
end

function make_peak_identification_figure(signal, peaks, config, figureDirectory)
visible = figure_visibility(config.showFigures);
fig = figure('Color', 'w', 'Visible', visible, ...
    'Name', '显示范围内连续5周期双峰识别人工核对');
fs = config.sampleRateHz;
firstPeak = find(peaks.samplingLocation >= ...
    config.displayStartRawSample & peaks.samplingLocation <= ...
    config.displayEndRawSample, 1);
firstPeak = min(firstPeak, numel(peaks.samplingLocation) - 4);
usePeak = firstPeak:firstPeak + 4;
first = round(peaks.interactionLocation(usePeak(1)) - 0.10e-3 * fs);
last = round(peaks.samplingLocation(usePeak(end)) + 0.20e-3 * fs);
index = (first:20:last).';
timeMs = 1e3 * (index - peaks.samplingLocation(usePeak(1))) / fs;
plot(timeMs, signal(index), 'Color', [0.15 0.35 0.72]);
hold on;

interactionTimeMs = 1e3 * (peaks.interactionLocation(usePeak) - ...
    peaks.samplingLocation(usePeak(1))) / fs;
samplingTimeMs = 1e3 * (peaks.samplingLocation(usePeak) - ...
    peaks.samplingLocation(usePeak(1))) / fs;
interactionValue = interp1((1:numel(signal)).', signal, ...
    peaks.interactionLocation(usePeak), 'pchip');
samplingValue = interp1((1:numel(signal)).', signal, ...
    peaks.samplingLocation(usePeak), 'pchip');
scatter(interactionTimeMs, interactionValue, 46, ...
    [0.92 0.48 0.08], '^', 'filled');
scatter(samplingTimeMs, samplingValue, 50, ...
    [0.82 0.12 0.12], 'v', 'filled');
for k = 1:5
    xline(samplingTimeMs(k), ':', sprintf('周期%d', k), ...
        'LabelVerticalAlignment', 'bottom');
end
xlabel('相对第1个主采样峰的连续时间 (ms)');
ylabel('CH1电压 (V)');
title(sprintf(['显示范围内连续5周期双峰识别：平均双峰间隔 %.3f us，' ...
    '主采样峰相关中位数 %.3f'], ...
    1e6 * mean(peaks.separationSamples(usePeak)) / fs, ...
    median(peaks.samplingCorrelation(usePeak))));
legend('原始CH1', '互作用峰', '主采样峰', ...
    'Location', 'best');
grid on;
save_analysis_figure(fig, figureDirectory, ...
    'fig01_first5_double_peak_identification');
end

function make_overview_figure(interval, phaseAtPeak, config, figureDirectory)
visible = figure_visibility(config.showFigures);
timeMs = 1e3 * interval.midTime_s;
fig = figure('Color', 'w', 'Visible', visible, ...
    'Name', '四通道逐峰总览');
layout = tiledlayout(4, 1, 'TileSpacing', 'compact', ...
    'Padding', 'compact');
title(layout, '四通道在同一组主采样峰区间上的逐峰对照');

ax = nexttile(layout);
plot(ax, timeMs, interval.pulseSpacing_62M5 - ...
    mean(interval.pulseSpacing_62M5), 'k-', 'LineWidth', 1.0);
ylabel(ax, 'CH1间距偏差 (点)'); grid(ax, 'on');

ax = nexttile(layout);
plot(ax, timeMs, interval.referenceCyclesCic ./ ...
    interval.pulseDuration_s, 'Color', [0.00 0.35 0.78], ...
    'LineWidth', 1.0); hold(ax, 'on');
plot(ax, timeMs, interval.pulseEquivalentFrequency_Hz, ...
    'Color', [0.15 0.15 0.15], 'LineWidth', 1.0);
ylabel(ax, 'CH4/CH1 (Hz)');
legend(ax, 'CH4参考', 'CH1脉冲等效', 'Location', 'best');
grid(ax, 'on');

ax = nexttile(layout);
plot(ax, timeMs, interval.clockCycles500 ./ ...
    (config.capturedClockMultiplier * interval.pulseDuration_s), ...
    'Color', [0.76 0.18 0.12], 'LineWidth', 1.0); hold(ax, 'on');
plot(ax, timeMs, interval.referenceCyclesCic ./ ...
    interval.pulseDuration_s, '--', 'Color', [0.00 0.35 0.78]);
ylabel(ax, 'CH2/CH4 (Hz)');
legend(ax, 'CH2时钟/500', 'CH4参考', 'Location', 'best');
grid(ax, 'on');

ax = nexttile(layout);
set(ax, 'Tag', 'time-axis');
plot(ax, 1e3 * interval.startTime_s, 1e3 * phaseAtPeak(1:end - 1), ...
    'Color', [0.42 0.12 0.62], 'LineWidth', 1.0);
ylabel(ax, 'CH3相位残差 (mrad)');
xlabel(ax, '固定62.5 MHz时间轴 (ms)'); grid(ax, 'on');
apply_display_range(fig, config);
save_analysis_figure(fig, figureDirectory, 'fig02_four_channel_overview');
end

function make_sliding_figure(sliding, config, figureDirectory)
visible = figure_visibility(config.showFigures);
fig = figure('Color', 'w', 'Visible', visible, ...
    'Name', '一个脉冲周期的滑动累计');
layout = tiledlayout(3, 1, 'TileSpacing', 'compact', ...
    'Padding', 'compact');
title(layout, '每个观测点都累计其前一个完整脉冲周期');
timeMs = 1e3 * sliding.time_s;

ax = nexttile(layout);
plot(ax, timeMs, sliding.referenceFrequencyCic_Hz, ...
    'Color', [0.00 0.35 0.78]); hold(ax, 'on');
plot(ax, timeMs, sliding.pulseEquivalentFrequency_Hz, ...
    'Color', [0.15 0.15 0.15]);
ylabel(ax, '频率 (Hz)');
legend(ax, 'CH4 CIC参考', 'CH1脉冲等效', 'Location', 'best');
grid(ax, 'on');

ax = nexttile(layout);
plot(ax, timeMs, sliding.clockEquivalentFrequency_Hz, ...
    'Color', [0.76 0.18 0.12]); hold(ax, 'on');
plot(ax, timeMs, sliding.referenceFrequencyCic_Hz, '--', ...
    'Color', [0.00 0.35 0.78]);
ylabel(ax, '频率 (Hz)');
legend(ax, 'CH2时钟/500', 'CH4 CIC参考', 'Location', 'best');
grid(ax, 'on');

ax = nexttile(layout);
plot(ax, timeMs, sliding.phaseResidualMrad, ...
    'Color', [0.42 0.12 0.62]);
ylabel(ax, 'CH3相位残差 (mrad)');
xlabel(ax, '固定62.5 MHz时间轴 (ms)'); grid(ax, 'on');
apply_display_range(fig, config);
save_analysis_figure(fig, figureDirectory, ...
    'fig03_one_pulse_sliding_accumulation');
end

function make_reference_crosscheck_figure(interval, sliding, config, figureDirectory)
visible = figure_visibility(config.showFigures);
fig = figure('Color', 'w', 'Visible', visible, ...
    'Name', 'CH4原始与CIC交叉核验');
layout = tiledlayout(3, 1, 'TileSpacing', 'compact', ...
    'Padding', 'compact');
title(layout, 'CH4直接IQ与FPGA定点CIC/DC Block结果对照');
timeMs = 1e3 * interval.midTime_s;
R = config.referenceCyclesPerPulse;
M = config.reportClockMultiplier;

ax = nexttile(layout);
plot(ax, timeMs, M * (interval.referenceCyclesRaw - R), ...
    'Color', [0.55 0.55 0.55]); hold(ax, 'on');
plot(ax, timeMs, M * (interval.referenceCyclesCic - R), ...
    'Color', [0.00 0.35 0.78]);
ylabel(ax, 'reference-event (点)');
legend(ax, 'CH4原始IQ', 'CH4 CIC IQ', 'Location', 'best'); grid(ax, 'on');

ax = nexttile(layout);
plot(ax, 1e3 * sliding.time_s, sliding.referenceFrequencyRaw_Hz, ...
    'Color', [0.55 0.55 0.55]); hold(ax, 'on');
plot(ax, 1e3 * sliding.time_s, sliding.referenceFrequencyCic_Hz, ...
    'Color', [0.00 0.35 0.78]);
ylabel(ax, '滑动频率 (Hz)');
legend(ax, '原始IQ', 'CIC IQ', 'Location', 'best'); grid(ax, 'on');

ax = nexttile(layout);
plot(ax, 1e3 * sliding.time_s, ...
    sliding.referenceFrequencyCic_Hz - sliding.referenceFrequencyRaw_Hz, ...
    'Color', [0.82 0.18 0.12]);
ylabel(ax, 'CIC-原始 (Hz)');
xlabel(ax, '固定62.5 MHz时间轴 (ms)'); grid(ax, 'on');
apply_display_range(fig, config);
save_analysis_figure(fig, figureDirectory, ...
    'fig04_reference_raw_vs_cic');
end

function make_decomposition_figure(interval, config, figureDirectory)
visible = figure_visibility(config.showFigures);
fig = figure('Color', 'w', 'Visible', visible, ...
    'Name', '最终误差精确分解', 'Position', [80 40 1500 1120]);
layout = tiledlayout(4, 2, 'TileSpacing', 'compact', ...
    'Padding', 'compact');
title(layout, sprintf(['逐区间有符号误差（相对名义值，未减均值）' ...
    '：最终误差 = reference-event项 + PLL自身追踪项\n' ...
    '前三行左列为2000倍输出时钟点数、右列为同一误差的mrad换算；' ...
    '末行分离IQ/正过零测量口径影响；仅显示有效区间']));
timeMs = 1e3 * interval.midTime_s;
valid = interval.validForTrackingAnalysis;
finalError = interval.finalError2000;
referenceEvent = interval.referenceEvent2000;
pllTracking = interval.pllTracking2000Ch2IqCh4Iq;
ch2Effect = interval.ch2IqToCrossingEffect2000;
ch4Effect = interval.ch4IqToCrossingEffect2000;
finalValid = finalError(valid);
referenceValid = referenceEvent(valid);
pllValid = pllTracking(valid);
ch2EffectValid = ch2Effect(valid);
ch4EffectValid = ch4Effect(valid);
finalError(~valid) = NaN;
referenceEvent(~valid) = NaN;
pllTracking(~valid) = NaN;
ch2Effect(~valid) = NaN;
ch4Effect(~valid) = NaN;

ax = nexttile(layout);
plot(ax, timeMs, finalError, 'k-', 'LineWidth', 1.2); hold(ax, 'on');
yline(ax, 0, ':', 'Color', [0.55 0.55 0.55]);
ylabel(ax, 'output cycles');
title(ax, sprintf(['最终误差：CH1两峰间CH2计数相对226000；' ...
    'RMS %.3f，均值 %.3f，标准差 %.3f点'], ...
    rms0(finalValid), mean(finalValid), std(finalValid, 1)));
grid(ax, 'on');

ax = nexttile(layout);
plot(ax, timeMs, cycles_to_mrad(finalError, config), ...
    'k-', 'LineWidth', 1.2); hold(ax, 'on');
yline(ax, 0, ':', 'Color', [0.55 0.55 0.55]);
ylabel(ax, 'mrad');
title(ax, sprintf('最终误差相位换算；RMS %.3f mrad', ...
    rms0(cycles_to_mrad(finalValid, config))));
grid(ax, 'on');

ax = nexttile(layout);
plot(ax, timeMs, referenceEvent, 'Color', [0.00 0.35 0.78], ...
    'LineWidth', 1.1);
yline(ax, 0, ':', 'Color', [0.55 0.55 0.55]);
ylabel(ax, 'output cycles');
title(ax, sprintf(['测得的reference-event：CH4参考相位相对CH1峰端点；' ...
    'RMS %.3f，均值 %.3f，标准差 %.3f点'], ...
    rms0(referenceValid), mean(referenceValid), std(referenceValid, 1)));
grid(ax, 'on');

ax = nexttile(layout);
plot(ax, timeMs, cycles_to_mrad(referenceEvent, config), ...
    'Color', [0.00 0.35 0.78], 'LineWidth', 1.1);
yline(ax, 0, ':', 'Color', [0.55 0.55 0.55]);
ylabel(ax, 'mrad');
title(ax, sprintf('reference-event相位换算；RMS %.3f mrad', ...
    rms0(cycles_to_mrad(referenceValid, config))));
grid(ax, 'on');

ax = nexttile(layout);
plot(ax, timeMs, pllTracking, 'Color', [0.90 0.40 0.05], ...
    'LineWidth', 1.1);
yline(ax, 0, ':', 'Color', [0.55 0.55 0.55]);
ylabel(ax, 'output cycles');
title(ax, sprintf(['PLL端点追踪误差（CH2 IQ，CH4 IQ）；' ...
    'RMS %.3f，均值 %.3f，标准差 %.3f点'], ...
    rms0(pllValid), mean(pllValid), std(pllValid, 1)));
grid(ax, 'on');

ax = nexttile(layout);
plot(ax, timeMs, cycles_to_mrad(pllTracking, config), ...
    'Color', [0.90 0.40 0.05], 'LineWidth', 1.1);
yline(ax, 0, ':', 'Color', [0.55 0.55 0.55]);
ylabel(ax, 'mrad');
title(ax, sprintf('PLL端点追踪误差相位换算；RMS %.3f mrad', ...
    rms0(cycles_to_mrad(pllValid, config))));
grid(ax, 'on');

ax = nexttile(layout);
plot(ax, timeMs, ch2Effect, 'Color', [0.48 0.18 0.65], ...
    'LineWidth', 1.0); hold(ax, 'on');
yline(ax, 0, ':', 'Color', [0.55 0.55 0.55]);
ylabel(ax, 'output cycles'); xlabel(ax, '固定62.5 MHz时间轴 (ms)');
title(ax, sprintf(['只切换CH2：P(ZC,IQ)-P(IQ,IQ)；' ...
    'RMS %.3f点 / %.3f mrad'], ...
    rms0(ch2EffectValid), ...
    rms0(cycles_to_mrad(ch2EffectValid, config))));
grid(ax, 'on');

ax = nexttile(layout);
plot(ax, timeMs, ch4Effect, 'Color', [0.10 0.55 0.28], ...
    'LineWidth', 1.0); hold(ax, 'on');
yline(ax, 0, ':', 'Color', [0.55 0.55 0.55]);
ylabel(ax, 'output cycles'); xlabel(ax, '固定62.5 MHz时间轴 (ms)');
title(ax, sprintf(['只切换CH4：P(IQ,ZC)-P(IQ,IQ)；' ...
    'RMS %.3f点 / %.3f mrad'], ...
    rms0(ch4EffectValid), ...
    rms0(cycles_to_mrad(ch4EffectValid, config))));
grid(ax, 'on');
linkaxes(findall(fig, 'Type', 'axes'), 'x');
apply_display_range(fig, config);
save_analysis_figure(fig, figureDirectory, ...
    'fig05_exact_error_decomposition');
end

function make_phase_validation_figure(interval, phaseAtPeak, ...
    delayTable, bestDelaySamples, config, figureDirectory)
visible = figure_visibility(config.showFigures);
fig = figure('Color', 'w', 'Visible', visible, ...
    'Name', 'CH3相位残差端点预测');
layout = tiledlayout(3, 1, 'TileSpacing', 'compact', ...
    'Padding', 'compact');
title(layout, 'CH3端点相位差与CH2/CH4独立测得PLL追踪项');
valid = interval.validForTrackingAnalysis;
pllTracking = interval.pllTracking500;
phasePrediction = interval.phasePrediction500Best;
pllTracking(~valid) = NaN;
phasePrediction(~valid) = NaN;

ax = nexttile(layout);
set(ax, 'Tag', 'time-axis');
plot(ax, 1e3 * interval.startTime_s, 1e3 * phaseAtPeak(1:end - 1), ...
    'Color', [0.42 0.12 0.62]);
ylabel(ax, 'CH3相位 (mrad)'); grid(ax, 'on');

ax = nexttile(layout);
set(ax, 'Tag', 'time-axis');
plot(ax, 1e3 * interval.midTime_s, pllTracking, ...
    'Color', [0.90 0.40 0.05], 'LineWidth', 1.1); hold(ax, 'on');
plot(ax, 1e3 * interval.midTime_s, phasePrediction, ...
    '--', 'Color', [0.42 0.12 0.62], 'LineWidth', 1.1);
ylabel(ax, '500倍时钟周期');
legend(ax, 'CH2-500×CH4', 'CH3端点预测', 'Location', 'best');
grid(ax, 'on');

ax = nexttile(layout);
plot(ax, delayTable.delay_us, delayTable.correlation, ...
    'Color', [0.12 0.45 0.20]); hold(ax, 'on');
xline(ax, 1e6 * bestDelaySamples / config.sampleRateHz, '--r');
ylabel(ax, '相关系数'); xlabel(ax, 'CH3固定延时 (us)'); grid(ax, 'on');
apply_display_range_to_axes(findall(fig, 'Type', 'axes', ...
    '-and', 'Tag', 'time-axis'), config);
save_analysis_figure(fig, figureDirectory, ...
    'fig06_phase_residual_endpoint_validation');
end

function make_peak_reference_pll_relation_figure(interval, config, figureDirectory)
visible = figure_visibility(config.showFigures);
fig = figure('Color', 'w', 'Visible', visible, ...
    'Name', '峰间距与参考及PLL残差关系');
layout = tiledlayout(3, 1, 'TileSpacing', 'compact', ...
    'Padding', 'compact');
title(layout, '主采样峰间距—细化输入参考—PLL相位残差关系');
timeMs = 1e3 * interval.midTime_s;
valid = interval.validForTrackingAnalysis;

pulseDeviation = interval.pulseEquivalentFrequency_Hz - ...
    mean(interval.pulseEquivalentFrequency_Hz(valid));
referenceDeviation = interval.referenceAverageFrequencyCic_Hz - ...
    mean(interval.referenceAverageFrequencyCic_Hz(valid));
pulseDeviation(~valid) = NaN;
referenceDeviation(~valid) = NaN;
ax = nexttile(layout);
plot(ax, timeMs, pulseDeviation, 'k-', 'LineWidth', 1.1); hold(ax, 'on');
plot(ax, timeMs, referenceDeviation, ...
    'Color', [0.00 0.35 0.78], 'LineWidth', 1.1);
ylabel(ax, '频率波动 (Hz)');
title(ax, sprintf(['CH1峰间距换算频率 vs CH4 CIC/IQ参考频率：' ...
    'r = %.4f'], correlation(pulseDeviation(valid), ...
    referenceDeviation(valid))));
legend(ax, 'CH1峰间距换算', 'CH4细化参考', ...
    'Location', 'best'); grid(ax, 'on');

ax = nexttile(layout);
finalError = interval.finalError2000;
referenceEvent = interval.referenceEvent2000;
finalError(~valid) = NaN;
referenceEvent(~valid) = NaN;
plot(ax, timeMs, finalError, 'k-', 'LineWidth', 1.1); hold(ax, 'on');
plot(ax, timeMs, referenceEvent, ...
    'Color', [0.00 0.35 0.78], 'LineWidth', 1.1);
ylabel(ax, '2000倍等效误差 (点)');
title(ax, sprintf(['最终峰间距误差 vs reference-event项：' ...
    'r = %.4f'], correlation(interval.finalError2000(valid), ...
    interval.referenceEvent2000(valid))));
legend(ax, '最终峰间距误差', 'reference-event项', ...
    'Location', 'best'); grid(ax, 'on');

ax = nexttile(layout);
pllTracking = interval.pllTracking2000;
phasePrediction = interval.phasePrediction2000Best;
pllTracking(~valid) = NaN;
phasePrediction(~valid) = NaN;
plot(ax, timeMs, pllTracking, ...
    'Color', [0.90 0.40 0.05], 'LineWidth', 1.1); hold(ax, 'on');
plot(ax, timeMs, phasePrediction, '--', ...
    'Color', [0.42 0.12 0.62], 'LineWidth', 1.1);
ylabel(ax, '2000倍等效误差 (点)');
xlabel(ax, '固定62.5 MHz时间轴 (ms)');
title(ax, sprintf(['CH2/CH4独立测得PLL项 vs CH3端点相位差预测：' ...
    'r = %.4f'], correlation(interval.pllTracking2000(valid), ...
    interval.phasePrediction2000Best(valid))));
legend(ax, 'PLL自身追踪项', 'CH3相位残差预测', ...
    'Location', 'best'); grid(ax, 'on');
apply_display_range(fig, config);
save_analysis_figure(fig, figureDirectory, ...
    'fig07_peak_reference_pll_relationship');
end

function make_capture_continuity_figure(interval, continuity, config, ...
    figureDirectory)
visible = figure_visibility(config.showFigures);
fig = figure('Color', 'w', 'Visible', visible, ...
    'Name', 'PCI固定时间轴连续性诊断');
layout = tiledlayout(3, 1, 'TileSpacing', 'compact', ...
    'Padding', 'compact');
title(layout, sprintf(['采集质量分类：有效%d段，载波断点%d段，' ...
    '仅CH1缺脉冲候选%d段（所有区间均保留）'], ...
    nnz(interval.validForTrackingAnalysis), ...
    nnz(interval.containsCarrierDiscontinuity), ...
    nnz(interval.pulseOnlyMissingCandidate)));
timeMs = 1e3 * interval.midTime_s;

ax = nexttile(layout);
spacingDeviation = interval.pulseSpacing_62M5 - ...
    continuity.pulseSpacingMedian;
plot(ax, timeMs, spacingDeviation, 'k-', 'LineWidth', 0.9); hold(ax, 'on');
use = interval.containsCarrierDiscontinuity;
scatter(ax, timeMs(use), spacingDeviation(use), 20, ...
    [0.82 0.12 0.12], 'filled');
use = interval.pulseOnlyMissingCandidate;
scatter(ax, timeMs(use), spacingDeviation(use), 28, ...
    [0.92 0.48 0.08], 'diamond', 'filled');
ylabel(ax, 'CH1间距偏差 (点)');
legend(ax, '全部区间', 'CH2/CH4载波断点', ...
    '仅CH1缺脉冲候选', 'Location', 'best');
grid(ax, 'on');

ax = nexttile(layout);
clock = continuity.clockAudit;
scatter(ax, 1e3 * (clock.outlierLocation - 1) / ...
    config.sampleRateHz, clock.outlierDeviation, 16, ...
    [0.76 0.18 0.12], 'filled');
ylabel(ax, 'CH2过零偏差 (点)');
title(ax, sprintf('CH2自适应时钟：%d个逐周期断点', ...
    clock.outlierCount));
grid(ax, 'on');

ax = nexttile(layout);
reference = continuity.referenceAudit;
scatter(ax, 1e3 * (reference.outlierLocation - 1) / ...
    config.sampleRateHz, reference.outlierDeviation, 16, ...
    [0.00 0.35 0.78], 'filled');
ylabel(ax, 'CH4过零偏差 (原始点)');
xlabel(ax, '固定62.5 MHz时间轴 (ms)');
title(ax, sprintf('CH4 CIC参考：%d个逐周期断点', ...
    reference.outlierCount));
grid(ax, 'on');
linkaxes(findall(fig, 'Type', 'axes'), 'x');
apply_display_range(fig, config);
save_analysis_figure(fig, figureDirectory, ...
    'fig08_capture_continuity_classification');
end

function tableValue = build_interval_table(interval, peaks, phaseZero, phaseBest)
n = numel(interval.midTime_s);
tableValue = table((1:n).', interval.startTime_s, interval.endTime_s, ...
    interval.midTime_s, peaks.samplingLocation(1:end - 1), ...
    peaks.samplingLocation(2:end), peaks.interactionLocation(1:end - 1), ...
    peaks.separationSamples(1:end - 1), ...
    peaks.samplingCorrelation(1:end - 1), ...
    peaks.samplingCorrelation(2:end), ...
    peaks.interactionCorrelation(1:end - 1), ...
    interval.pulseSpacing_62M5, ...
    interval.pulseDuration_s, interval.pulseEquivalentFrequency_Hz, ...
    interval.referenceAverageFrequencyRaw_Hz, ...
    interval.referenceAverageFrequencyCic_Hz, ...
    interval.clockEquivalentFrequency_Hz, ...
    interval.referencePulseFrequencyMismatch_Hz, ...
    interval.clockReferenceFrequencyMismatch_Hz, ...
    interval.referenceCyclesRaw, interval.referenceCyclesCic, ...
    interval.referenceCyclesCicCrossing, interval.clockCycles500, ...
    interval.clockCycles500Crossing, interval.finalError500, ...
    interval.referenceEvent500, interval.pllTracking500, ...
    interval.finalError500Crossing, interval.referenceEvent500Crossing, ...
    interval.pllTracking500Crossing, ...
    interval.finalError2000, interval.referenceEvent2000, ...
    interval.pllTracking2000, ...
    interval.pllTracking2000Ch2IqCh4Iq, ...
    interval.pllTracking2000Ch2IqCh4Crossing, ...
    interval.pllTracking2000Ch2CrossingCh4Iq, ...
    interval.pllTracking2000Ch2CrossingCh4Crossing, ...
    interval.ch2IqToCrossingEffect2000, ...
    interval.ch4IqToCrossingEffect2000, ...
    interval.iqCrossingCombinationClosure2000, ...
    interval.finalErrorMrad, ...
    interval.referenceEventMrad, interval.pllTrackingMrad, ...
    interval.pulseSpacingOutlier, ...
    interval.containsClockCrossingOutlier, ...
    interval.containsReferenceCrossingOutlier, ...
    interval.containsCarrierDiscontinuity, ...
    interval.pulseOnlyMissingCandidate, ...
    interval.validForTrackingAnalysis, ...
    interval.maximumClockCrossingDeviationSamples, ...
    interval.maximumReferenceCrossingDeviationSamples, ...
    phaseZero(1:end - 1), phaseZero(2:end), ...
    phaseBest(1:end - 1), phaseBest(2:end), ...
    interval.phasePrediction500Zero, interval.phasePrediction500Best, ...
    interval.closure2000, ...
    'VariableNames', {'interval', 'start_time_s', 'end_time_s', ...
    'mid_time_s', 'sampling_start_raw', 'sampling_end_raw', ...
    'interaction_start_raw', 'double_peak_separation_samples', ...
    'sampling_correlation_start', 'sampling_correlation_end', ...
    'interaction_correlation_start', ...
    'pulse_spacing_62M5', 'pulse_duration_s', ...
    'pulse_equivalent_frequency_hz', ...
    'reference_average_frequency_raw_hz', ...
    'reference_average_frequency_cic_hz', ...
    'clock_equivalent_frequency_hz', ...
    'reference_pulse_frequency_mismatch_hz', ...
    'clock_reference_frequency_mismatch_hz', ...
    'reference_cycles_raw', ...
    'reference_cycles_cic', 'reference_cycles_cic_crossing', ...
    'clock_cycles_500', 'clock_cycles_500_crossing', 'final_error_500', ...
    'reference_event_500', 'pll_tracking_500', ...
    'final_error_500_crossing', 'reference_event_500_crossing', ...
    'pll_tracking_500_crossing', 'final_error_2000', ...
    'reference_event_2000', 'pll_tracking_2000', ...
    'pll_tracking_2000_ch2_iq_ch4_iq', ...
    'pll_tracking_2000_ch2_iq_ch4_crossing', ...
    'pll_tracking_2000_ch2_crossing_ch4_iq', ...
    'pll_tracking_2000_ch2_crossing_ch4_crossing', ...
    'ch2_iq_to_crossing_effect_2000', ...
    'ch4_iq_to_crossing_effect_2000', ...
    'iq_crossing_combination_closure_2000', ...
    'final_error_mrad', 'reference_event_mrad', 'pll_tracking_mrad', ...
    'pulse_spacing_outlier', 'contains_ch2_crossing_outlier', ...
    'contains_ch4_cic_crossing_outlier', ...
    'contains_carrier_discontinuity', ...
    'pulse_only_missing_candidate', 'valid_for_tracking_analysis', ...
    'maximum_ch2_crossing_deviation_samples', ...
    'maximum_ch4_cic_crossing_deviation_samples', ...
    'phase_zero_start_rad', 'phase_zero_end_rad', ...
    'phase_best_start_rad', 'phase_best_end_rad', ...
    'phase_prediction_500_zero', 'phase_prediction_500_best', ...
    'closure_2000'});
end

function segmentTable = build_segment_table(interval)
count = numel(interval.midTime_s);
edge = round(linspace(1, count + 1, 5));
segment = (1:4).';
startTime_s = zeros(4, 1);
endTime_s = zeros(4, 1);
intervalCount = zeros(4, 1);
validIntervalCount = zeros(4, 1);
allFinalRms2000 = zeros(4, 1);
allReferenceEventRms2000 = zeros(4, 1);
allPllTrackingRms2000 = zeros(4, 1);
allPllCh2IqCh4CrossingRms2000 = zeros(4, 1);
allPllCh2CrossingCh4IqRms2000 = zeros(4, 1);
allPllCh2CrossingCh4CrossingRms2000 = zeros(4, 1);
allCh2IqToCrossingEffectRms2000 = zeros(4, 1);
allCh4IqToCrossingEffectRms2000 = zeros(4, 1);
validFinalRms2000 = zeros(4, 1);
validReferenceEventRms2000 = zeros(4, 1);
validPllTrackingRms2000 = zeros(4, 1);
validPllCh2IqCh4CrossingRms2000 = zeros(4, 1);
validPllCh2CrossingCh4IqRms2000 = zeros(4, 1);
validPllCh2CrossingCh4CrossingRms2000 = zeros(4, 1);
validCh2IqToCrossingEffectRms2000 = zeros(4, 1);
validCh4IqToCrossingEffectRms2000 = zeros(4, 1);
for k = 1:4
    use = edge(k):edge(k + 1) - 1;
    valid = use(interval.validForTrackingAnalysis(use));
    startTime_s(k) = interval.startTime_s(use(1));
    endTime_s(k) = interval.endTime_s(use(end));
    intervalCount(k) = numel(use);
    validIntervalCount(k) = numel(valid);
    allFinalRms2000(k) = rms0(interval.finalError2000(use));
    allReferenceEventRms2000(k) = rms0(interval.referenceEvent2000(use));
    allPllTrackingRms2000(k) = rms0(interval.pllTracking2000(use));
    allPllCh2IqCh4CrossingRms2000(k) = rms0( ...
        interval.pllTracking2000Ch2IqCh4Crossing(use));
    allPllCh2CrossingCh4IqRms2000(k) = rms0( ...
        interval.pllTracking2000Ch2CrossingCh4Iq(use));
    allPllCh2CrossingCh4CrossingRms2000(k) = rms0( ...
        interval.pllTracking2000Ch2CrossingCh4Crossing(use));
    allCh2IqToCrossingEffectRms2000(k) = rms0( ...
        interval.ch2IqToCrossingEffect2000(use));
    allCh4IqToCrossingEffectRms2000(k) = rms0( ...
        interval.ch4IqToCrossingEffect2000(use));
    validFinalRms2000(k) = rms0(interval.finalError2000(valid));
    validReferenceEventRms2000(k) = ...
        rms0(interval.referenceEvent2000(valid));
    validPllTrackingRms2000(k) = rms0(interval.pllTracking2000(valid));
    validPllCh2IqCh4CrossingRms2000(k) = rms0( ...
        interval.pllTracking2000Ch2IqCh4Crossing(valid));
    validPllCh2CrossingCh4IqRms2000(k) = rms0( ...
        interval.pllTracking2000Ch2CrossingCh4Iq(valid));
    validPllCh2CrossingCh4CrossingRms2000(k) = rms0( ...
        interval.pllTracking2000Ch2CrossingCh4Crossing(valid));
    validCh2IqToCrossingEffectRms2000(k) = rms0( ...
        interval.ch2IqToCrossingEffect2000(valid));
    validCh4IqToCrossingEffectRms2000(k) = rms0( ...
        interval.ch4IqToCrossingEffect2000(valid));
end
segmentTable = table(segment, startTime_s, endTime_s, intervalCount, ...
    validIntervalCount, allFinalRms2000, allReferenceEventRms2000, ...
    allPllTrackingRms2000, allPllCh2IqCh4CrossingRms2000, ...
    allPllCh2CrossingCh4IqRms2000, ...
    allPllCh2CrossingCh4CrossingRms2000, ...
    allCh2IqToCrossingEffectRms2000, ...
    allCh4IqToCrossingEffectRms2000, validFinalRms2000, ...
    validReferenceEventRms2000, validPllTrackingRms2000, ...
    validPllCh2IqCh4CrossingRms2000, ...
    validPllCh2CrossingCh4IqRms2000, ...
    validPllCh2CrossingCh4CrossingRms2000, ...
    validCh2IqToCrossingEffectRms2000, ...
    validCh4IqToCrossingEffectRms2000);
end

function summary = build_summary(config, referenceCic, referenceRaw, ...
    adaptiveClock, interval, bestDelaySamples, bestCorrelation)
summary.referenceCarrierCicHz = referenceCic.carrier_frequency_hz;
summary.referenceCarrierRawHz = referenceRaw.carrier_frequency_hz;
summary.adaptiveClockCarrierHz = adaptiveClock.carrier_frequency_hz;
summary.measuredMultiplier = adaptiveClock.carrier_frequency_hz / ...
    referenceCic.carrier_frequency_hz;
summary.pulseIntervalCount = numel(interval.midTime_s);
summary.finalRms2000 = rms0(interval.finalError2000);
summary.referenceEventRms2000 = rms0(interval.referenceEvent2000);
summary.pllTrackingRms2000 = rms0(interval.pllTracking2000);
summary.finalMean2000 = mean(interval.finalError2000);
summary.referenceEventMean2000 = mean(interval.referenceEvent2000);
summary.pllTrackingMean2000 = mean(interval.pllTracking2000);
summary.finalStd2000 = std(interval.finalError2000, 1);
summary.referenceEventStd2000 = std(interval.referenceEvent2000, 1);
summary.pllTrackingStd2000 = std(interval.pllTracking2000, 1);
summary.finalPeak2000 = max(abs(interval.finalError2000));
summary.referenceEventPeak2000 = max(abs(interval.referenceEvent2000));
summary.pllTrackingPeak2000 = max(abs(interval.pllTracking2000));
summary.finalRmsMrad = rms0(interval.finalErrorMrad);
summary.referenceEventRmsMrad = rms0(interval.referenceEventMrad);
summary.pllTrackingRmsMrad = rms0(interval.pllTrackingMrad);
summary.closurePeak2000 = max(abs(interval.closure2000));
summary.rawCicReferenceCorrelation = correlation( ...
    interval.referenceCyclesRaw, interval.referenceCyclesCic);
summary.rawCicReferenceDifferenceRms2000 = ...
    config.reportClockMultiplier * rms0(interval.referenceCyclesRaw - ...
    interval.referenceCyclesCic);
summary.referenceIqCrossingDifferenceRms2000 = ...
    config.reportClockMultiplier * rms0(interval.referenceCyclesCic - ...
    interval.referenceCyclesCicCrossing);
summary.clockIqCrossingDifferenceRms2000 = ...
    config.reportClockMultiplier / config.capturedClockMultiplier * ...
    rms0(interval.clockCycles500 - interval.clockCycles500Crossing);
summary.phaseCorrelationZero = correlation( ...
    interval.phasePrediction500Zero, interval.pllTracking500);
summary.phaseCorrelationBest = bestCorrelation;
summary.bestPhaseDelaySamples = bestDelaySamples;
summary.bestPhaseDelayUs = 1e6 * bestDelaySamples / config.sampleRateHz;
summary.phasePredictionResidualRms500 = rms0( ...
    interval.phasePrediction500Best - interval.pllTracking500);
summary.finalReferenceEventCorrelation = correlation( ...
    interval.finalError2000, interval.referenceEvent2000);
summary.finalPllTrackingCorrelation = correlation( ...
    interval.finalError2000, interval.pllTracking2000);
summary.finalRms2000Crossing = rms0(interval.finalError2000Crossing);
summary.referenceEventRms2000Crossing = ...
    rms0(interval.referenceEvent2000Crossing);
summary.pllTrackingRms2000Crossing = ...
    rms0(interval.pllTracking2000Crossing);
summary.pllTrackingRms2000Ch2IqCh4Iq = rms0( ...
    interval.pllTracking2000Ch2IqCh4Iq);
summary.pllTrackingRms2000Ch2IqCh4Crossing = rms0( ...
    interval.pllTracking2000Ch2IqCh4Crossing);
summary.pllTrackingRms2000Ch2CrossingCh4Iq = rms0( ...
    interval.pllTracking2000Ch2CrossingCh4Iq);
summary.pllTrackingRms2000Ch2CrossingCh4Crossing = rms0( ...
    interval.pllTracking2000Ch2CrossingCh4Crossing);
summary.ch2IqToCrossingEffectRms2000 = rms0( ...
    interval.ch2IqToCrossingEffect2000);
summary.ch4IqToCrossingEffectRms2000 = rms0( ...
    interval.ch4IqToCrossingEffect2000);
summary.matchedIqToCrossingEffectRms2000 = rms0( ...
    interval.pllTracking2000Ch2CrossingCh4Crossing - ...
    interval.pllTracking2000Ch2IqCh4Iq);
summary.iqCrossingCombinationClosurePeak2000 = max(abs( ...
    interval.iqCrossingCombinationClosure2000));
summary.finalIqCrossingCorrelation = correlation( ...
    interval.finalError2000, interval.finalError2000Crossing);
summary.pulseReferenceFrequencyCorrelation = correlation( ...
    interval.pulseEquivalentFrequency_Hz, ...
    interval.referenceAverageFrequencyCic_Hz);
summary.clockReferenceFrequencyCorrelation = correlation( ...
    interval.clockEquivalentFrequency_Hz, ...
    interval.referenceAverageFrequencyCic_Hz);
summary.referencePulseFrequencyMismatchRmsHz = rms0( ...
    interval.referencePulseFrequencyMismatch_Hz);
summary.clockReferenceFrequencyMismatchRmsHz = rms0( ...
    interval.clockReferenceFrequencyMismatch_Hz);
valid = interval.validForTrackingAnalysis;
summary.validIntervalCount = nnz(valid);
summary.pulseSpacingOutlierCount = nnz(interval.pulseSpacingOutlier);
summary.carrierDiscontinuityIntervalCount = ...
    nnz(interval.containsCarrierDiscontinuity);
summary.clockDiscontinuityIntervalCount = ...
    nnz(interval.containsClockCrossingOutlier);
summary.referenceDiscontinuityIntervalCount = ...
    nnz(interval.containsReferenceCrossingOutlier);
summary.pulseOnlyMissingCandidateCount = ...
    nnz(interval.pulseOnlyMissingCandidate);
summary.validFinalRms2000 = rms0(interval.finalError2000(valid));
summary.validReferenceEventRms2000 = ...
    rms0(interval.referenceEvent2000(valid));
summary.validPllTrackingRms2000 = ...
    rms0(interval.pllTracking2000(valid));
summary.validFinalRmsMrad = rms0(interval.finalErrorMrad(valid));
summary.validReferenceEventRmsMrad = ...
    rms0(interval.referenceEventMrad(valid));
summary.validPllTrackingRmsMrad = ...
    rms0(interval.pllTrackingMrad(valid));
summary.validPllTrackingRms2000Ch2IqCh4Iq = rms0( ...
    interval.pllTracking2000Ch2IqCh4Iq(valid));
summary.validPllTrackingRms2000Ch2IqCh4Crossing = rms0( ...
    interval.pllTracking2000Ch2IqCh4Crossing(valid));
summary.validPllTrackingRms2000Ch2CrossingCh4Iq = rms0( ...
    interval.pllTracking2000Ch2CrossingCh4Iq(valid));
summary.validPllTrackingRms2000Ch2CrossingCh4Crossing = rms0( ...
    interval.pllTracking2000Ch2CrossingCh4Crossing(valid));
summary.validCh2IqToCrossingEffectRms2000 = rms0( ...
    interval.ch2IqToCrossingEffect2000(valid));
summary.validCh4IqToCrossingEffectRms2000 = rms0( ...
    interval.ch4IqToCrossingEffect2000(valid));
summary.validMatchedIqToCrossingEffectRms2000 = rms0( ...
    interval.pllTracking2000Ch2CrossingCh4Crossing(valid) - ...
    interval.pllTracking2000Ch2IqCh4Iq(valid));
summary.validFinalPeak2000 = max(abs(interval.finalError2000(valid)));
summary.validFinalReferenceEventCorrelation = correlation( ...
    interval.finalError2000(valid), interval.referenceEvent2000(valid));
summary.validPhaseCorrelationBest = correlation( ...
    interval.phasePrediction500Best(valid), interval.pllTracking500(valid));
end

function tableValue = summary_to_table(summary)
name = string(fieldnames(summary));
value = struct2cell(summary);
value = cellfun(@double, value);
tableValue = table(name, value);
end

function dense = compact_phase(dense)
dense = rmfield(dense, {'crossing_index', 'crossing_cycle', 'iq'});
end

function value = rms0(values)
value = sqrt(mean(values(:).^2));
end

function value = cycles_to_mrad(cycles, config)
value = 2 * pi * 1000 / config.reportClockMultiplier * cycles;
end

function apply_display_range(fig, config)
apply_display_range_to_axes(findall(fig, 'Type', 'axes'), config);
end

function apply_display_range_to_axes(axesValue, config)
startMs = 1e3 * (config.displayStartRawSample - 1) / ...
    config.sampleRateHz;
endMs = 1e3 * (config.displayEndRawSample - 1) / ...
    config.sampleRateHz;
for k = 1:numel(axesValue)
    current = xlim(axesValue(k));
    first = max(current(1), startMs);
    last = current(2);
    if isfinite(endMs), last = min(last, endMs); end
    xlim(axesValue(k), [first last]);
end
end

function visible = figure_visibility(showFigures)
if showFigures, visible = 'on'; else, visible = 'off'; end
end

function save_analysis_figure(fig, directory, name)
set(fig, 'Position', [100 100 1400 900]);
savefig(fig, fullfile(directory, name + ".fig"));
exportgraphics(fig, fullfile(directory, name + ".png"), ...
    'Resolution', 180);
end
