%% 四通道CH4 CIC载波连续性核查
% 用FPGA等效CIC/DC Block后的逐周期正过零间距检查采集时间轴断点。

close all;
clear;
clc;

resultDirectory = "E:/JiangSiyi/THz器件采样/光源稳定性分析/20260809/" + ...
    "results_4ch_tracking/dat5_62M5_4CH_20260809_230252";
workspaceResultDirectory = "E:/JiangSiyi/FPGA/DPLL_Low_Freq_Track/" + ...
    "MCU_src/simudate/results_4ch_tracking/dat5_62M5_4CH_20260809_230252";
frontendMat = fullfile(resultDirectory, ...
    "dat5_62M5_4CH_ch4_CIC_DCBlock_3M125.mat");
doublePeakAuditMat = fullfile(workspaceResultDirectory, ...
    "double_peak_extraction_audit.mat");

sourceSampleRateHz = 62.5e6;
cicGroupDelaySourceSamples = 158 / 125e6 * sourceSampleRateHz;

frontend = load(frontendMat, 'frontendOutput', 'metadata');
signal = double(frontend.frontendOutput(:));
outputSampleRateHz = frontend.metadata.outputSampleRate;
sourceSamplesPerOutput = sourceSampleRateHz / outputSampleRateHz;
signal = signal - median(signal);
clear frontend

left = find(signal(1:end - 1) <= 0 & signal(2:end) > 0);
fraction = -signal(left) ./ (signal(left + 1) - signal(left));
crossingOutput = left + fraction;
crossingLocationRaw = 1 + (crossingOutput - 1) * sourceSamplesPerOutput - ...
    cicGroupDelaySourceSamples;
crossingSpacingRaw = diff(crossingLocationRaw);
spacingMedian = median(crossingSpacingRaw);
spacingMad = median(abs(crossingSpacingRaw - spacingMedian));
outlierThreshold = max(10, 20 * 1.4826 * spacingMad);
crossingOutlier = abs(crossingSpacingRaw - spacingMedian) >= outlierThreshold;
crossingMidpointRaw = 0.5 * (crossingLocationRaw(1:end - 1) + ...
    crossingLocationRaw(2:end));

saved = load(doublePeakAuditMat, 'audit');
intervals = saved.audit.intervals;
abnormal = intervals.abnormal_spacing;
clear saved

intervalHasCrossingOutlier = false(height(intervals), 1);
maximumCrossingDeviation = zeros(height(intervals), 1);
for k = 1:height(intervals)
    use = crossingMidpointRaw >= intervals.start_location_raw(k) & ...
        crossingMidpointRaw <= intervals.end_location_raw(k);
    intervalHasCrossingOutlier(k) = any(crossingOutlier(use));
    maximumCrossingDeviation(k) = max(abs( ...
        crossingSpacingRaw(use) - spacingMedian));
end

summary = table(numel(crossingLocationRaw), spacingMedian, spacingMad, ...
    outlierThreshold, nnz(crossingOutlier), nnz(abnormal), ...
    nnz(abnormal & intervalHasCrossingOutlier), ...
    nnz(~abnormal & intervalHasCrossingOutlier), ...
    'VariableNames', {'crossing_count', 'median_spacing_raw_samples', ...
    'spacing_mad_raw_samples', 'outlier_threshold_raw_samples', ...
    'crossing_outlier_count', 'abnormal_pulse_interval_count', ...
    'abnormal_pulse_intervals_with_ch4_outlier', ...
    'normal_pulse_intervals_with_ch4_outlier'});

intervalTable = table(intervals.interval, intervals.start_location_raw, ...
    intervals.end_location_raw, intervals.spacing_samples, abnormal, ...
    intervalHasCrossingOutlier, maximumCrossingDeviation, ...
    'VariableNames', {'interval', 'start_location_raw', ...
    'end_location_raw', 'pulse_spacing_samples', ...
    'abnormal_pulse_spacing', 'contains_ch4_cic_crossing_outlier', ...
    'maximum_ch4_cic_crossing_deviation_raw_samples'});
crossingTable = table(crossingMidpointRaw(crossingOutlier), ...
    crossingSpacingRaw(crossingOutlier), ...
    crossingSpacingRaw(crossingOutlier) - spacingMedian, ...
    'VariableNames', {'location_raw', 'crossing_spacing_raw_samples', ...
    'spacing_deviation_raw_samples'});

tableDirectory = fullfile(workspaceResultDirectory, 'tables');
figureDirectory = fullfile(workspaceResultDirectory, 'figures');
writetable(summary, fullfile(tableDirectory, ...
    'ch4_cic_continuity_audit_summary.csv'));
writetable(intervalTable, fullfile(tableDirectory, ...
    'ch4_cic_continuity_by_pulse_interval.csv'));
writetable(crossingTable, fullfile(tableDirectory, ...
    'ch4_cic_crossing_outliers.csv'));

continuityAudit.schemaVersion = 1;
continuityAudit.method = 'FPGA-equivalent CIC/DC Block positive crossings';
continuityAudit.summary = summary;
continuityAudit.intervalTable = intervalTable;
continuityAudit.crossingOutliers = crossingTable;
save(fullfile(workspaceResultDirectory, 'ch4_cic_continuity_audit.mat'), ...
    'continuityAudit', '-v7.3');

timeMs = 1e3 * (intervals.start_location_raw - 1) / sourceSampleRateHz;
fig = figure('Color', 'w', 'Name', 'CH4 CIC时间轴连续性核查', ...
    'Position', [100 100 1200 700]);
layout = tiledlayout(2, 1, 'TileSpacing', 'compact', 'Padding', 'compact');
title(layout, sprintf(['CH4 CIC正过零连续性：脉冲大间距变化%d，' ...
    '其中%d个区间含参考载波断点'], nnz(abnormal), ...
    nnz(abnormal & intervalHasCrossingOutlier)));

ax = nexttile(layout);
plot(ax, 1e3 * (crossingMidpointRaw - 1) / sourceSampleRateHz, ...
    crossingSpacingRaw - spacingMedian, 'Color', [0.25 0.25 0.25]); hold(ax, 'on');
scatter(ax, 1e3 * (crossingMidpointRaw(crossingOutlier) - 1) / ...
    sourceSampleRateHz, crossingSpacingRaw(crossingOutlier) - spacingMedian, ...
    18, [0.82 0.12 0.12], 'filled');
ylabel(ax, 'CH4过零间距偏差 (原始点)'); grid(ax, 'on');

ax = nexttile(layout);
plot(ax, timeMs, maximumCrossingDeviation, 'Color', [0.00 0.35 0.78]); hold(ax, 'on');
scatter(ax, timeMs(abnormal), maximumCrossingDeviation(abnormal), ...
    18, [0.82 0.12 0.12], 'filled');
ylabel(ax, '区间内最大CH4偏差 (原始点)');
xlabel(ax, '固定62.5 MHz时间轴 (ms)'); grid(ax, 'on');
legend(ax, '全部脉冲区间', 'CH1大间距变化', 'Location', 'best');

savefig(fig, fullfile(figureDirectory, ...
    'fig13_ch4_cic_continuity_audit.fig'));
exportgraphics(fig, fullfile(figureDirectory, ...
    'fig13_ch4_cic_continuity_audit.png'), 'Resolution', 180);

disp(summary);
