function comparison = build_peak_localization_baseline_comparison( ...
    baseline_dirs, fractional_dirs, output_dir, options)
%BUILD_PEAK_LOCALIZATION_BASELINE_COMPARISON Integer versus fractional peaks.

arguments
    baseline_dirs (:,1) string
    fractional_dirs (:,1) string
    output_dir (1,1) string
    options.labels (:,1) string = strings(0, 1)
    options.show_figures (1,1) logical = false
end

baseline_dirs = baseline_dirs(:);
fractional_dirs = fractional_dirs(:);
if numel(baseline_dirs) ~= numel(fractional_dirs) || ...
        numel(baseline_dirs) < 1
    error('reference_analysis:BaselineCountMismatch', ...
        'Baseline and fractional study counts must match and be nonzero.');
end
if isfolder(output_dir)
    error('reference_analysis:OutputExists', ...
        'Refusing to overwrite baseline comparison: %s', output_dir);
end
count = numel(baseline_dirs);
if isempty(options.labels)
    labels = "dataset " + (1:count).';
else
    labels = options.labels(:);
end
if numel(labels) ~= count
    error('reference_analysis:LabelCountMismatch', ...
        'labels must match the study count.');
end
mkdir(output_dir);
mkdir(fullfile(output_dir, 'figures'));
mkdir(fullfile(output_dir, 'tables'));

row_template = struct('dataset', "", ...
    'integer_reference_event_rms_output_cycles', NaN, ...
    'fractional_reference_event_rms_output_cycles', NaN, ...
    'reference_event_rms_reduction_percent', NaN, ...
    'integer_reference_event_rms_mrad', NaN, ...
    'fractional_reference_event_rms_mrad', NaN, ...
    'integer_frequency_mismatch_rms_hz', NaN, ...
    'fractional_frequency_mismatch_rms_hz', NaN, ...
    'frequency_mismatch_reduction_percent', NaN, ...
    'integer_timing_residual_rms_raw_samples', NaN, ...
    'fractional_timing_residual_rms_raw_samples', NaN);
rows = repmat(row_template, count, 1);
baseline_paths = strings(count, 1);
fractional_paths = strings(count, 1);
for k = 1:count
    baseline_paths(k) = fullfile(baseline_dirs(k), ...
        'reference_pulse_relation_study.mat');
    fractional_paths(k) = fullfile(fractional_dirs(k), ...
        'reference_pulse_relation_study.mat');
    baseline = load_summary(baseline_paths(k));
    fractional = load_summary(fractional_paths(k));
    rows(k).dataset = labels(k);
    rows(k).integer_reference_event_rms_output_cycles = ...
        baseline.reference_event_rms_output_cycles;
    rows(k).fractional_reference_event_rms_output_cycles = ...
        fractional.reference_event_rms_output_cycles;
    rows(k).reference_event_rms_reduction_percent = 100 * ...
        (baseline.reference_event_rms_output_cycles - ...
        fractional.reference_event_rms_output_cycles) / ...
        baseline.reference_event_rms_output_cycles;
    rows(k).integer_reference_event_rms_mrad = ...
        baseline.reference_event_rms_mrad;
    rows(k).fractional_reference_event_rms_mrad = ...
        fractional.reference_event_rms_mrad;
    rows(k).integer_frequency_mismatch_rms_hz = ...
        baseline.frequency_mismatch_rms_hz;
    rows(k).fractional_frequency_mismatch_rms_hz = ...
        fractional.frequency_mismatch_rms_hz;
    rows(k).frequency_mismatch_reduction_percent = 100 * ...
        (baseline.frequency_mismatch_rms_hz - ...
        fractional.frequency_mismatch_rms_hz) / ...
        baseline.frequency_mismatch_rms_hz;
    rows(k).integer_timing_residual_rms_raw_samples = ...
        baseline.timing_residual_rms_raw_samples_62m5;
    rows(k).fractional_timing_residual_rms_raw_samples = ...
        fractional.timing_residual_rms_raw_samples_62m5;
end
metrics = struct2table(rows);
provenance = table( ...
    repelem(labels, 2), repmat(["integer_peak_baseline"; ...
    "fractional_xcorr_peak"], count, 1), ...
    reshape([baseline_paths.'; fractional_paths.'], [], 1), ...
    'VariableNames', {'dataset', 'role', 'study_mat'});
provenance.sha256 = arrayfun(@(path) ...
    string(dpll.file_sha256(path)), provenance.study_mat);
writetable(metrics, fullfile(output_dir, 'tables', ...
    'peak_localization_baseline_comparison.csv'));
writetable(provenance, fullfile(output_dir, 'tables', ...
    'source_provenance.csv'));

figure_files = make_figure(metrics, fullfile(output_dir, 'figures'), ...
    options.show_figures);
comparison.schema_version = 1;
comparison.created_at = char(datetime('now', ...
    'Format', 'yyyy-MM-dd HH:mm:ss Z'));
comparison.metrics = metrics;
comparison.provenance = provenance;
comparison.figure_files = figure_files;
comparison.report_path = fullfile(output_dir, ...
    'peak_localization_baseline_report_cn.md');
write_report(comparison.report_path, metrics);
save(fullfile(output_dir, 'peak_localization_baseline_comparison.mat'), ...
    'comparison', '-v7.3');
end

function files = make_figure(metrics, figure_dir, show_figures)
visibility = 'off';
if show_figures, visibility = 'on'; end
colors = lines(height(metrics));
fig = figure('Visible', visibility, 'Color', 'w', ...
    'Position', [100 100 1200 520]);
layout = tiledlayout(fig, 1, 2, 'TileSpacing', 'compact', ...
    'Padding', 'compact');
title(layout, '整数峰与模板互相关亚采样峰的配对基线', ...
    'FontWeight', 'normal');

ax = nexttile(layout);
hold(ax, 'on');
for k = 1:height(metrics)
    values = [metrics.integer_reference_event_rms_output_cycles(k), ...
        metrics.fractional_reference_event_rms_output_cycles(k)];
    plot(ax, [1 2], values, '-', 'Color', colors(k, :), ...
        'LineWidth', 1.4, 'DisplayName', metrics.dataset(k));
    plot(ax, 1, values(1), 'o', 'Color', colors(k, :), ...
        'MarkerFaceColor', 'w', 'MarkerSize', 8, ...
        'HandleVisibility', 'off');
    plot(ax, 2, values(2), 'o', 'Color', colors(k, :), ...
        'MarkerFaceColor', colors(k, :), 'MarkerSize', 8, ...
        'HandleVisibility', 'off');
end
set(ax, 'XTick', [1 2], 'XTickLabel', {'旧整数峰', '亚采样峰'}, ...
    'XLim', [0.7 2.3]);
ylabel(ax, 'reference-event RMS (等效输出点)');
title(ax, '事件相位误差');
legend(ax, 'Location', 'best');
grid(ax, 'on');

ax = nexttile(layout);
hold(ax, 'on');
for k = 1:height(metrics)
    values = [metrics.integer_frequency_mismatch_rms_hz(k), ...
        metrics.fractional_frequency_mismatch_rms_hz(k)];
    plot(ax, [1 2], values, '-', 'Color', colors(k, :), ...
        'LineWidth', 1.4, 'DisplayName', metrics.dataset(k));
    plot(ax, 1, values(1), 'o', 'Color', colors(k, :), ...
        'MarkerFaceColor', 'w', 'MarkerSize', 8, ...
        'HandleVisibility', 'off');
    plot(ax, 2, values(2), 'o', 'Color', colors(k, :), ...
        'MarkerFaceColor', colors(k, :), 'MarkerSize', 8, ...
        'HandleVisibility', 'off');
end
set(ax, 'XTick', [1 2], 'XTickLabel', {'旧整数峰', '亚采样峰'}, ...
    'XLim', [0.7 2.3]);
ylabel(ax, '参考 - 脉冲等效频率 RMS (Hz)');
title(ax, '区间频率差');
legend(ax, 'Location', 'best');
grid(ax, 'on');
files = dpll.export_paper_figure(fig, fullfile(figure_dir, ...
    'figure1_integer_vs_fractional_peak_baseline_cn'), ...
    [9.2 4.2], 'Microsoft YaHei');
if ~show_figures, close(fig); end
end

function summary = load_summary(path)
if ~isfile(path)
    error('reference_analysis:StudyNotFound', ...
        'Study MAT does not exist: %s', path);
end
loaded = load(path, 'study');
summary = loaded.study.summary;
end

function write_report(path, metrics)
file_id = fopen(path, 'w', 'n', 'UTF-8');
if file_id < 0
    error('reference_analysis:ReportOpenFailed', ...
        'Cannot create report: %s', path);
end
cleanup = onCleanup(@() fclose(file_id));
fprintf(file_id, '# 整数峰与亚采样峰基线比较\n\n');
fprintf(file_id, ['| 数据 | 整数峰事件RMS | 亚采样事件RMS | 降低 | ' ...
    '整数峰频率差RMS | 亚采样频率差RMS |\n']);
fprintf(file_id, '|---|---:|---:|---:|---:|---:|\n');
for k = 1:height(metrics)
    fprintf(file_id, '| %s | %.6f | %.6f | %.3f%% | %.6f | %.6f |\n', ...
        metrics.dataset(k), ...
        metrics.integer_reference_event_rms_output_cycles(k), ...
        metrics.fractional_reference_event_rms_output_cycles(k), ...
        metrics.reference_event_rms_reduction_percent(k), ...
        metrics.integer_frequency_mismatch_rms_hz(k), ...
        metrics.fractional_frequency_mismatch_rms_hz(k));
end
fprintf(file_id, ['\n亚采样细化保持旧离散峰身份不变。改善约1%%，因此整数峰量化' ...
    '不是当前reference-event误差的主要来源。\n']);
end
