function bundle = export_fixed_clock_peak_family_tables( ...
    extraction_mat, output_dir)
%EXPORT_FIXED_CLOCK_PEAK_FAMILY_TABLES Export auditable extraction CSVs.

arguments
    extraction_mat (1,1) string
    output_dir (1,1) string
end

if ~isfile(extraction_mat)
    error('reference_analysis:ExtractionNotFound', ...
        'Peak extraction MAT does not exist: %s', extraction_mat);
end
if isfolder(output_dir)
    error('reference_analysis:OutputExists', ...
        'Refusing to overwrite extraction tables: %s', output_dir);
end
loaded = load(extraction_mat, 'extraction');
if ~isfield(loaded, 'extraction') || ...
        ~isfield(loaded.extraction, 'families')
    error('reference_analysis:InvalidExtraction', ...
        'MAT does not contain a peak-family extraction structure.');
end
extraction = loaded.extraction;
mkdir(output_dir);

family_count = numel(extraction.families);
row_template = struct('dataset', "", 'family_id', 0, ...
    'phase_center_samples', NaN, 'polarity', 0, ...
    'stable', false, 'sampling_candidate', false, ...
    'longest_contiguous_event_count', 0, 'accepted_event_count', 0, ...
    'cycle_span_count', 0, 'cycle_occupancy', NaN, ...
    'segment_count', 0, 'dropped_outside_longest_segment', 0, ...
    'mean_peak_spacing_samples', NaN, ...
    'std_peak_spacing_samples', NaN, ...
    'interval_residual_rms_samples', NaN, ...
    'median_template_correlation', NaN, ...
    'minimum_template_correlation', NaN, 'median_snr', NaN, ...
    'xcorr_fractional_offset_rms_samples', NaN, ...
    'waveform_fractional_offset_rms_samples', NaN, ...
    'integer_seed_consistency_fraction', NaN);
rows = repmat(row_template, family_count, 1);
event_tables = cell(family_count, 1);
for k = 1:family_count
    family = extraction.families(k);
    rows(k).dataset = string(extraction.dataset_id);
    rows(k).family_id = family.id;
    rows(k).phase_center_samples = family.phase_center_samples;
    rows(k).polarity = family.polarity;
    rows(k).stable = family.stable;
    rows(k).sampling_candidate = family.sampling_candidate;
    rows(k).longest_contiguous_event_count = ...
        numel(family.refined_location_raw);
    rows(k).accepted_event_count = family.accepted_event_count;
    rows(k).cycle_span_count = family.cycle_span_count;
    rows(k).cycle_occupancy = family.cycle_occupancy;
    rows(k).segment_count = family.segment_count;
    rows(k).dropped_outside_longest_segment = ...
        family.dropped_nonconsecutive_events;
    rows(k).mean_peak_spacing_samples = ...
        mean(family.refined_distance_raw);
    rows(k).std_peak_spacing_samples = std(family.refined_distance_raw);
    rows(k).interval_residual_rms_samples = ...
        family.interval_residual_rms_samples;
    rows(k).median_template_correlation = ...
        family.median_template_correlation;
    rows(k).minimum_template_correlation = ...
        family.minimum_template_correlation;
    rows(k).median_snr = family.median_snr;
    rows(k).xcorr_fractional_offset_rms_samples = ...
        rms_plain(family.fractional_offset_samples);
    rows(k).waveform_fractional_offset_rms_samples = ...
        rms_plain(family.waveform_fractional_offset_samples);
    rows(k).integer_seed_consistency_fraction = ...
        mean(family.integer_seed_consistent);

    event_count = numel(family.all_refined_location_raw);
    event_tables{k} = table( ...
        repmat(string(extraction.dataset_id), event_count, 1), ...
        repmat(family.id, event_count, 1), ...
        repmat(family.polarity, event_count, 1), ...
        repmat(family.sampling_candidate, event_count, 1), ...
        (1:event_count).', family.all_segment_id(:), ...
        family.all_macro_cycle_index(:), ...
        family.all_coarse_location_raw(:), ...
        family.all_discrete_location_raw(:), ...
        family.all_fractional_offset_samples(:), ...
        family.all_waveform_fractional_offset_samples(:), ...
        family.all_refined_location_raw(:), ...
        family.all_template_correlation(:), ...
        'VariableNames', {'dataset', 'family_id', 'polarity', ...
        'sampling_candidate', 'accepted_event_index', 'segment_id', ...
        'macro_cycle_index', 'coarse_location_raw', ...
        'discrete_location_raw', 'xcorr_fractional_offset_samples', ...
        'waveform_fractional_offset_samples', 'refined_location_raw', ...
        'template_correlation'});
end
family_table = struct2table(rows);
event_table = vertcat(event_tables{:});
candidate_table = table( ...
    extraction.event_location_raw(:), extraction.event_score(:), ...
    extraction.family_assignment(:), ...
    extraction.family_assignment(:) == 0, ...
    'VariableNames', {'candidate_location_raw', 'candidate_score', ...
    'assigned_phase_family', 'unassigned_noise_candidate'});
provenance = table( ...
    ["peak_family_extraction_mat"; "source_pci"], ...
    [extraction_mat; string(extraction.pci_path)], ...
    [string(dpll.file_sha256(extraction_mat)); ...
     string(extraction.pci_sha256)], ...
    'VariableNames', {'role', 'path', 'sha256'});

writetable(family_table, fullfile(output_dir, ...
    'peak_family_metrics.csv'));
writetable(event_table, fullfile(output_dir, ...
    'accepted_fractional_peak_events.csv'));
writetable(candidate_table, fullfile(output_dir, ...
    'coarse_candidate_assignment.csv'));
writetable(provenance, fullfile(output_dir, ...
    'source_provenance.csv'));

bundle.schema_version = 1;
bundle.created_at = char(datetime('now', ...
    'Format', 'yyyy-MM-dd HH:mm:ss Z'));
bundle.extraction_mat = char(extraction_mat);
bundle.output_dir = char(output_dir);
bundle.family_metrics = family_table;
bundle.accepted_events = event_table;
bundle.candidate_assignment = candidate_table;
bundle.provenance = provenance;
bundle.report_path = fullfile(output_dir, ...
    'peak_family_extraction_report_cn.md');
write_report(bundle.report_path, extraction, family_table);
save(fullfile(output_dir, 'peak_family_table_bundle.mat'), ...
    'bundle', '-v7.3');
end

function write_report(path, extraction, table_value)
file_id = fopen(path, 'w', 'n', 'UTF-8');
if file_id < 0
    error('reference_analysis:ReportOpenFailed', ...
        'Cannot create report: %s', path);
end
cleanup = onCleanup(@() fclose(file_id));
fprintf(file_id, '# %s 固定时钟峰族提取报告\n\n', ...
    extraction.dataset_id);
fprintf(file_id, '| 项目 | 数值 |\n|---|---:|\n');
fprintf(file_id, '| 分析源点数 | %d |\n', extraction.analysis_sample_count);
fprintf(file_id, '| 粗候选数 | %d |\n', numel(extraction.event_location_raw));
fprintf(file_id, '| 未分配噪声候选数 | %d |\n', ...
    extraction.cluster_diagnostics.unassigned_event_count);
fprintf(file_id, '| 宏周期 (62.5 MHz点) | %.6f |\n', ...
    extraction.macro_period_samples);
fprintf(file_id, '| 稳定峰族数 | %d |\n\n', height(table_value));
fprintf(file_id, ['| 族 | 极性 | 连续峰数 | 覆盖率 | 峰距均值 | 峰距标准差 | ' ...
    '模板相关中位数 | 采样候选 |\n']);
fprintf(file_id, '|---:|---:|---:|---:|---:|---:|---:|---:|\n');
for k = 1:height(table_value)
    fprintf(file_id, '| %d | %+d | %d | %.6f | %.6f | %.6f | %.6f | %d |\n', ...
        table_value.family_id(k), table_value.polarity(k), ...
        table_value.longest_contiguous_event_count(k), ...
        table_value.cycle_occupancy(k), ...
        table_value.mean_peak_spacing_samples(k), ...
        table_value.std_peak_spacing_samples(k), ...
        table_value.median_template_correlation(k), ...
        table_value.sampling_candidate(k));
end
fprintf(file_id, ['\n小数峰位由离散峰身份不变的零延迟模板互相关峰三点拟合得到。' ...
    'dat8若存在两个负峰候选，两者均保留，不自动选择物理采样峰。\n']);
end

function value = rms_plain(input)
input = double(input(:));
input = input(isfinite(input));
if isempty(input), value = NaN; else, value = sqrt(mean(input.^2)); end
end
