function audit = run_dpll_root_cause_audit( ...
    replay_mat_path, reference_mat_path, peak_mat_path, ...
    peak_extractor_script, output_dir, options)
%RUN_DPLL_ROOT_CAUSE_AUDIT Full frozen-boundary DPLL root-cause investigation.

arguments
    replay_mat_path (1,1) string
    reference_mat_path (1,1) string
    peak_mat_path (1,1) string
    peak_extractor_script (1,1) string
    output_dir (1,1) string
    options.reference_sample_count (1,1) double = 4194304
    options.local_window_cycles (1,1) double = 8
    options.analytic_half_bandwidth_hz (1,1) double = 500
    options.delay_scan_s (:,1) double = (-0.003:0.00001:0.003).'
    options.slow_window_pulses (1,1) double = 21
    options.show_figures (1,1) logical = false
    options.reuse_calibration (1,1) logical = false
    options.run_pi_refinement (1,1) logical = true
end

required_files = [replay_mat_path, reference_mat_path, peak_mat_path];
for k = 1:numel(required_files)
    if ~isfile(required_files(k))
        error('dpll:AuditInputMissing', ...
            'Required audit input does not exist: %s', required_files(k));
    end
end
if ~isfolder(output_dir), mkdir(output_dir); end
raw_dir = fullfile(output_dir, 'raw');
table_dir = fullfile(output_dir, 'tables');
figure_dir = fullfile(output_dir, 'figures');
calibration_dir = fullfile(output_dir, 'calibration');
ceiling_dir = fullfile(output_dir, 'reference_ceiling');
if ~isfolder(raw_dir), mkdir(raw_dir); end
if ~isfolder(table_dir), mkdir(table_dir); end
if ~isfolder(figure_dir), mkdir(figure_dir); end

frozen = load(replay_mat_path, 'result', 'summary');
if ~isfield(frozen, 'result') || ...
        frozen.result.metadata.posterior_interval_data_used
    error('dpll:InvalidFrozenReplay', ...
        'The replay is missing or already posterior-contaminated.');
end
result = frozen.result;
cfg = result.config;

% Freeze estimators and detector metrics before loading any peak posterior.
calibration_file = fullfile(calibration_dir, ...
    'reference_estimator_calibration.mat');
if options.reuse_calibration && isfile(calibration_file)
    loaded_calibration = load(calibration_file, 'calibration');
    calibration = loaded_calibration.calibration;
else
    calibration = run_reference_estimator_calibration( ...
        cfg, string(calibration_dir), ...
        local_window_cycles=options.local_window_cycles, ...
        analytic_half_bandwidth_hz=options.analytic_half_bandwidth_hz);
end
if calibration.posterior_peak_data_loaded
    error('dpll:CalibrationPosteriorLeak', ...
        'Reference estimator calibration unexpectedly used peak data.');
end
calibration_frozen_at = char(datetime('now', ...
    'Format', 'yyyy-MM-dd HH:mm:ss'));

reference_info = whos('-file', reference_mat_path, 'frontendOutput');
if isempty(reference_info)
    error('dpll:MissingFrontendOutput', ...
        'Reference MAT file does not contain frontendOutput.');
end
reference_meta_raw = load(reference_mat_path, 'metadata');
reference_metadata = reference_meta_raw.metadata;
sample_count = min(options.reference_sample_count, reference_info.size(1));
mapped = matfile(reference_mat_path);
codes = mapped.frontendOutput(1:sample_count, 1);

% Posterior boundary starts here.
peak_raw_data = load(peak_mat_path, 'channel1SampleRate', ...
    'samplingPeakFirstLocation', 'samplingPeakMeanDistance', ...
    'samplingPeakDistance');
validation = validate_peak_alignment(result, peak_mat_path, false);
peak_raw = double(validation.peak_raw_index(:));
source_per_reference = reference_metadata.sourceSampleRate / ...
    reference_metadata.outputSampleRate;
peak_reference_index = 1 + (peak_raw - 1) / source_per_reference;

trace_keep = result.trace.analysis_valid;
trace_raw = double(result.metadata.source_raw_start_index) + ...
    (double(result.trace.input_index(trace_keep)) - ...
    double(result.metadata.input_start_index)) * ...
    double(result.metadata.source_samples_per_input);
trace_reference_index = 1 + (trace_raw - 1) / source_per_reference;

delay_scan = options.delay_scan_s(:);
delay_query = peak_reference_index.' + ...
    delay_scan * reference_metadata.outputSampleRate;
delay_query_vector = delay_query(:);
all_query = [peak_reference_index; trace_reference_index; delay_query_vector];

zero_all = dpll.estimate_zero_crossing_phase(codes, all_query, ...
    reference_metadata.outputSampleRate);
analytic_all = dpll.estimate_fft_analytic_phase(codes, all_query, ...
    reference_metadata.outputSampleRate, ...
    zero_all.carrier_frequency_hz, options.analytic_half_bandwidth_hz);
local_peak = dpll.estimate_local_sinusoid_phase(codes, ...
    peak_reference_index, reference_metadata.outputSampleRate, ...
    zero_all.carrier_frequency_hz, options.local_window_cycles);

peak_count = numel(peak_reference_index);
trace_count = numel(trace_reference_index);
peak_range = 1:peak_count;
trace_range = peak_count + (1:trace_count);
delay_range = peak_count + trace_count + (1:numel(delay_query_vector));
zero_peak_cycles = zero_all.phase_cycles(peak_range);
analytic_peak_cycles = analytic_all.phase_cycles(peak_range);
zero_trace_cycles = zero_all.phase_cycles(trace_range);
analytic_trace_cycles = analytic_all.phase_cycles(trace_range);
zero_delay_cycles = reshape(zero_all.phase_cycles(delay_range), ...
    size(delay_query));
analytic_delay_cycles = reshape(analytic_all.phase_cycles(delay_range), ...
    size(delay_query));

[fpga_trace_cycles, fpga_trace_phase_error_rad] = ...
    reconstruct_fpga_reference_trace(result, trace_keep);
fpga_peak_cycles = interp1(trace_raw, fpga_trace_cycles, ...
    peak_raw, 'linear', NaN);
fpga_delay_cycles = nan(size(delay_query));
for k = 1:numel(delay_scan)
    shifted_raw = peak_raw + delay_scan(k) * ...
        reference_metadata.sourceSampleRate;
    fpga_delay_cycles(k, :) = interp1(trace_raw, fpga_trace_cycles, ...
        shifted_raw, 'linear', NaN);
end

method_names = ["zero_crossing"; "local_sinusoid"; ...
    "fft_analytic"; "fpga_detector_reconstruction"];
method_phase = {zero_peak_cycles; local_peak.phase_cycles; ...
    analytic_peak_cycles; fpga_peak_cycles};
ideal_interval = cfg.pulse.reference_cycles_per_pulse * ...
    cfg.pulse.output_multiplier;
interval_errors = cell(numel(method_names), 1);
for k = 1:numel(method_names)
    interval_errors{k} = diff(method_phase{k}) * ...
        cfg.pulse.output_multiplier - ideal_interval;
end

method_metrics = build_method_metrics(method_names, interval_errors, ...
    validation, options.slow_window_pulses);
pairwise = build_pairwise_metrics(method_names, interval_errors);
interval_table = build_interval_table(validation, method_names, ...
    interval_errors);
delay_table = build_delay_table(delay_scan, ...
    {zero_delay_cycles, analytic_delay_cycles, fpga_delay_cycles}, ...
    ["zero_crossing", "fft_analytic", ...
    "fpga_detector_reconstruction"], cfg);

crossing_count = diff(interp1(zero_all.crossing_index, ...
    zero_all.crossing_cycle, peak_reference_index, 'previous'));
timing_audit = build_timing_audit(reference_metadata, result, ...
    peak_raw_data, peak_raw, peak_reference_index, crossing_count, ...
    zero_all, sample_count);
extractor_audit = build_peak_extractor_audit(peak_raw_data, ...
    peak_extractor_script);
real_detector = build_real_detector_comparison(result, trace_keep, ...
    fpga_trace_cycles, fpga_trace_phase_error_rad, zero_trace_cycles, ...
    analytic_trace_cycles);
detector_group_delay = build_group_delay_summary(calibration.response);
theoretical_iir = build_theoretical_iir_response(cfg, ...
    calibration.options.phase_tone_hz);

ceiling = run_reference_phase_ceiling_validation( ...
    replay_mat_path, peak_mat_path, string(ceiling_dir), ...
    shift_scan_s=options.delay_scan_s, ...
    slow_window_pulses=options.slow_window_pulses, ...
    show_figures=false);
pi_refinement = [];
selected_pi_posterior = [];
if options.run_pi_refinement
    pi_refinement = run_pi_reference_only_refinement(cfg, ...
        string(fullfile(output_dir, 'pi_refinement')));
    selected_id = pi_refinement.selected_candidate.id;
    selected_replay_index = find(string({pi_refinement.candidates.id}) == ...
        selected_id, 1, 'first');
    selected_replay = load(pi_refinement.replay_files(selected_replay_index), ...
        'result');
    selected_pi_posterior = validate_peak_alignment( ...
        selected_replay.result, peak_mat_path, false);
end
evidence = build_root_cause_evidence(method_metrics, pairwise, ...
    delay_table, timing_audit, extractor_audit, calibration, ceiling, ...
    pi_refinement, selected_pi_posterior);
decision = make_root_cause_decision(evidence, calibration, pi_refinement);

audit.schema_version = 1;
audit.created_at = char(datetime('now', ...
    'Format', 'yyyy-MM-dd HH:mm:ss'));
audit.calibration_frozen_at = calibration_frozen_at;
audit.posterior_loaded_after_calibration = true;
audit.posterior_used_for_parameter_selection = false;
audit.options = options;
audit.config = cfg;
audit.reference_metadata = reference_metadata;
audit.calibration = calibration;
audit.validation = validation;
audit.method_names = method_names;
audit.peak_raw_index = peak_raw;
audit.peak_reference_index = peak_reference_index;
audit.method_phase_at_peak_cycles = method_phase;
audit.interval_errors = interval_errors;
audit.method_metrics = method_metrics;
audit.pairwise = pairwise;
audit.interval_table = interval_table;
audit.delay_scan = delay_table;
audit.timing_audit = timing_audit;
audit.extractor_audit = extractor_audit;
audit.real_detector = real_detector;
audit.detector_group_delay = detector_group_delay;
audit.theoretical_iir = theoretical_iir;
audit.reference_ceiling = ceiling;
audit.pi_refinement = pi_refinement;
audit.selected_pi_posterior = selected_pi_posterior;
audit.evidence = evidence;
audit.decision = decision;
audit.provenance = build_provenance(replay_mat_path, ...
    reference_mat_path, peak_mat_path, peak_extractor_script);

writetable(method_metrics, fullfile(table_dir, ...
    'real_phase_method_metrics.csv'));
writetable(pairwise, fullfile(table_dir, ...
    'real_phase_method_pairwise.csv'));
writetable(interval_table, fullfile(table_dir, ...
    'real_interval_phase_methods.csv'));
writetable(delay_table, fullfile(table_dir, ...
    'phase_method_fixed_delay_scan.csv'));
writetable(timing_audit, fullfile(table_dir, ...
    'timing_coordinate_audit.csv'));
writetable(extractor_audit, fullfile(table_dir, ...
    'peak_extractor_audit.csv'));
writetable(real_detector.metrics, fullfile(table_dir, ...
    'real_detector_phase_comparison.csv'));
writetable(detector_group_delay, fullfile(table_dir, ...
    'detector_group_delay_summary.csv'));
writetable(theoretical_iir, fullfile(table_dir, ...
    'theoretical_iir_response.csv'));
writetable(evidence, fullfile(table_dir, ...
    'root_cause_evidence.csv'));
writetable(audit.provenance, fullfile(table_dir, ...
    'source_provenance.csv'));

audit.figure_files = make_audit_figures(audit, figure_dir, ...
    options.show_figures);
audit.report_path = write_audit_report(audit, output_dir);
save(fullfile(raw_dir, 'dpll_root_cause_derived_data.mat'), ...
    'audit', '-v7.3');
save(fullfile(output_dir, 'dpll_root_cause_audit_complete.mat'), ...
    'audit', '-v7.3');
fprintf('\nDPLL root-cause audit complete.\n');
fprintf('  Decision: %s\n', audit.decision.primary_issue);
fprintf('  Report  : %s\n', audit.report_path);
end

function [cycles, phase_error_rad] = ...
    reconstruct_fpga_reference_trace(result, trace_keep)
phase_error_rad = double(result.trace.phase_error(trace_keep)) * pi / ...
    2^(result.config.phase_width - 1);
setpoint_rad = double(result.config.phase_setpoint) * pi / ...
    2^(result.config.phase_width - 1);
detector_phase = unwrap(phase_error_rad + setpoint_rad);
nco_phase = double(result.trace.tracking_phase_rad(trace_keep));
cycles = (nco_phase + detector_phase) / (2 * pi);
end

function metrics = build_method_metrics(names, errors, validation, slow_window)
rows = repmat(struct(), numel(names), 1);
for k = 1:numel(names)
    value = double(errors{k}(:));
    window = min(slow_window, numel(value));
    slow = movmean(value, window, 'Endpoints', 'shrink');
    fast = value - slow;
    rows(k).method = names(k);
    rows(k).count = numel(value);
    rows(k).mean_cycles = mean(value);
    rows(k).std_cycles = std(value);
    rows(k).rms_cycles = sqrt(mean(value.^2));
    rows(k).peak_to_peak_cycles = range(value);
    rows(k).slow_std_cycles = std(slow);
    rows(k).fast_std_cycles = std(fast);
    rows(k).lag1_correlation = corr(value(1:end-1), value(2:end));
    rows(k).correlation_with_fixed_error = corr(value, ...
        validation.uncompensated_interval_error_output_cycles);
    rows(k).correlation_with_pll_residual = corr(value, ...
        validation.recovered_interval_error);
end
metrics = struct2table(rows);
end

function table_value = build_pairwise_metrics(names, errors)
rows = repmat(struct(), 0, 1);
for left = 1:numel(names)
    for right = left + 1:numel(names)
        delta = errors{left} - errors{right};
        row.left_method = names(left);
        row.right_method = names(right);
        row.correlation = corr(errors{left}, errors{right});
        row.delta_mean_cycles = mean(delta);
        row.delta_std_cycles = std(delta);
        row.delta_rms_cycles = sqrt(mean(delta.^2));
        if isempty(rows)
            rows = row;
        else
            rows(end + 1, 1) = row; %#ok<AGROW>
        end
    end
end
table_value = struct2table(rows);
end

function table_value = build_interval_table(validation, names, errors)
table_value = table((1:numel(errors{1})).', ...
    validation.peak_time_s(2:end), validation.peak_raw_index(2:end), ...
    validation.uncompensated_interval_error_output_cycles, ...
    validation.recovered_interval_error, ...
    'VariableNames', {'interval_index', 'interval_end_time_s', ...
    'interval_end_raw_index', 'fixed_clock_error_cycles', ...
    'pll_residual_error_cycles'});
for k = 1:numel(names)
    table_value.(char(names(k) + "_error_cycles")) = errors{k};
end
end

function table_value = build_delay_table(shifts, phase_sets, names, cfg)
rows = repmat(struct(), 0, 1);
ideal = cfg.pulse.reference_cycles_per_pulse * ...
    cfg.pulse.output_multiplier;
for method_index = 1:numel(names)
    phase_matrix = phase_sets{method_index};
    for shift_index = 1:numel(shifts)
        phase = phase_matrix(shift_index, :).';
        error_value = diff(phase) * cfg.pulse.output_multiplier - ideal;
        valid = isfinite(error_value);
        row.method = names(method_index);
        row.shift_s = shifts(shift_index);
        row.count = nnz(valid);
        row.rms_cycles = sqrt(mean(error_value(valid).^2));
        row.std_cycles = std(error_value(valid));
        if isempty(rows)
            rows = row;
        else
            rows(end + 1, 1) = row; %#ok<AGROW>
        end
    end
end
table_value = struct2table(rows);
end

function table_value = build_timing_audit(metadata, result, peak_raw_data, ...
    peak_raw, peak_reference_index, crossing_count, zero, sample_count)
name = ["source_to_reference_rate_ratio"; ...
    "configured_source_samples_per_input"; "peak_channel_sample_rate_hz"; ...
    "reference_source_sample_rate_hz"; "reference_output_sample_rate_hz"; ...
    "loaded_reference_sample_count"; "covered_peak_count"; ...
    "peak_reference_index_min"; "peak_reference_index_max"; ...
    "positive_crossing_count_min_per_interval"; ...
    "positive_crossing_count_max_per_interval"; ...
    "positive_crossing_count_non113"; "reference_carrier_frequency_hz"; ...
    "reference_crossing_spacing_std_samples"; "trace_input_index_step_min"; ...
    "trace_input_index_step_max"; "trace_fabric_tick_step_min"; ...
    "trace_fabric_tick_step_max"; "saved_distance_fractional_value_count"; ...
    "saved_distance_count"];
value = [metadata.sourceSampleRate / metadata.outputSampleRate; ...
    result.metadata.source_samples_per_input; ...
    double(peak_raw_data.channel1SampleRate); metadata.sourceSampleRate; ...
    metadata.outputSampleRate; sample_count; numel(peak_raw); ...
    min(peak_reference_index); max(peak_reference_index); ...
    min(crossing_count); max(crossing_count); ...
    nnz(crossing_count ~= result.config.pulse.reference_cycles_per_pulse); ...
    zero.carrier_frequency_hz; zero.crossing_spacing_std; ...
    min(diff(result.trace.input_index)); max(diff(result.trace.input_index)); ...
    min(double(diff(result.trace.fabric_tick))); ...
    max(double(diff(result.trace.fabric_tick))); ...
    nnz(abs(double(peak_raw_data.samplingPeakDistance(:)) - ...
    round(double(peak_raw_data.samplingPeakDistance(:)))) > 1e-9); ...
    numel(peak_raw_data.samplingPeakDistance)];
status = repmat("measured", numel(name), 1);
table_value = table(name, value, status);
end

function table_value = build_peak_extractor_audit(peak_data, script_path)
script_available = isfile(script_path);
script_text = '';
if script_available, script_text = fileread(script_path); end
check = ["peak_distance_values_are_fractional"; ...
    "extractor_rounds_input_locations"; ...
    "extractor_uses_integer_xcorr_lag"; ...
    "extractor_has_parabolic_peak_interpolation"; ...
    "extractor_has_fractional_lag_interpolation"; ...
    "extractor_script_available"];
result = [any(abs(double(peak_data.samplingPeakDistance(:)) - ...
    round(double(peak_data.samplingPeakDistance(:)))) > 1e-9); ...
    contains(script_text, 'locs = round(locs(:))'); ...
    contains(script_text, 'lag = lagVal(maxIdx)') && ...
    contains(script_text, 'refinedLocs(i) = center + lag'); ...
    contains(lower(script_text), 'parabolic'); ...
    contains(lower(script_text), 'fractional') || ...
    contains(lower(script_text), 'subsample'); script_available];
evidence = ["fractional part of saved samplingPeakDistance"; ...
    "refineLocsByXcorr rounds all input locations"; ...
    "xcorr maximum selects an integer lag bin"; ...
    "search for parabolic interpolation in extractor"; ...
    "search for fractional/subsample interpolation in extractor"; ...
    script_path];
table_value = table(check, logical(result), evidence, ...
    'VariableNames', {'check', 'result', 'evidence'});
end

function comparison = build_real_detector_comparison(result, keep, ...
    fpga_cycles, phase_error_rad, zero_cycles, analytic_cycles)
time_s = result.trace.time_s(keep);
names = ["zero_minus_fpga"; "analytic_minus_fpga"; ...
    "zero_minus_analytic"];
series = {zero_cycles - fpga_cycles; analytic_cycles - fpga_cycles; ...
    zero_cycles - analytic_cycles};
rows = repmat(struct(), numel(names), 1);
aligned = cell(numel(names), 1);
for k = 1:numel(names)
    value = series{k};
    design = [ones(size(time_s)), time_s - mean(time_s)];
    value = value - design * (design \ value);
    aligned{k} = value;
    rows(k).comparison = names(k);
    rows(k).rms_reference_cycles = sqrt(mean(value.^2));
    rows(k).rms_output_cycles = result.config.pulse.output_multiplier * ...
        rows(k).rms_reference_cycles;
    rows(k).peak_output_cycles = result.config.pulse.output_multiplier * ...
        max(abs(value));
    rows(k).correlation_with_magnitude = corr(value, ...
        double(result.trace.magnitude(keep)));
end
comparison.time_s = time_s;
comparison.aligned_phase_difference_cycles = aligned;
comparison.names = names;
comparison.phase_error_rad = phase_error_rad;
comparison.metrics = struct2table(rows);
end

function summary = build_group_delay_summary(response)
methods = unique(response.method, 'stable');
rows = repmat(struct(), numel(methods), 1);
for k = 1:numel(methods)
    use = response.method == methods(k);
    frequency = response.frequency_hz(use);
    phase = unwrap(response.phase_deg(use) * pi / 180);
    fit_value = polyfit(frequency, phase, 1);
    rows(k).method = methods(k);
    rows(k).fitted_group_delay_us = -fit_value(1) / (2 * pi) * 1e6;
    rows(k).phase_intercept_deg = fit_value(2) * 180 / pi;
    rows(k).gain_min_db = min(response.gain_db(use));
    rows(k).gain_max_db = max(response.gain_db(use));
    rows(k).gain_span_db = range(response.gain_db(use));
end
summary = struct2table(rows);
end

function table_value = build_theoretical_iir_response(cfg, frequencies)
fs = cfg.input_sample_rate_hz / cfg.cic.rate;
coefficient = cfg.iir.track;
b = double([coefficient.b0 coefficient.b1 coefficient.b2]) / 2^30;
a = [1 double([coefficient.a1 coefficient.a2]) / 2^30];
z = exp(-1j * 2 * pi * frequencies(:) / fs);
single = (b(1) + b(2) * z + b(3) * z.^2) ./ ...
    (a(1) + a(2) * z + a(3) * z.^2);
transfer = single.^2;
phase = unwrap(angle(transfer));
frequency_hz = frequencies(:);
gain_db = 20 * log10(abs(transfer));
phase_deg = phase * 180 / pi;
equivalent_delay_us = -phase ./ (2 * pi * frequency_hz) * 1e6;
table_value = table(frequency_hz, gain_db, phase_deg, equivalent_delay_us);
end

function evidence = build_root_cause_evidence(metrics, pairwise, delay, ...
    timing, extractor, calibration, ceiling, pi_refinement, selected_posterior)
zero_rms = metric_value(metrics, "zero_crossing", 'rms_cycles');
local_rms = metric_value(metrics, "local_sinusoid", 'rms_cycles');
analytic_rms = metric_value(metrics, "fft_analytic", 'rms_cycles');
fpga_rms = metric_value(metrics, ...
    "fpga_detector_reconstruction", 'rms_cycles');
zero_fpga_corr = pair_value(pairwise, "zero_crossing", ...
    "fpga_detector_reconstruction", 'correlation');
best_zero = min(delay.std_cycles(delay.method == "zero_crossing"));
zero_shift0 = delay.std_cycles(delay.method == "zero_crossing" & ...
    abs(delay.shift_s) < 1e-15);
non113 = timing.value(timing.name == ...
    "positive_crossing_count_non113");
fractional_count = timing.value(timing.name == ...
    "saved_distance_fractional_value_count");
integer_xcorr = extractor.result(extractor.check == ...
    "extractor_uses_integer_xcorr_lag");
rows = {"real_zero_crossing_rms_cycles", zero_rms, "cycles", ...
        "direct reference waveform"; ...
    "real_local_sinusoid_rms_cycles", local_rms, "cycles", ...
        "independent local sine fit"; ...
    "real_fft_analytic_rms_cycles", analytic_rms, "cycles", ...
        "independent analytic phase"; ...
    "real_fpga_reference_rms_cycles", fpga_rms, "cycles", ...
        "NCO plus detector residual"; ...
    "zero_fpga_interval_correlation", zero_fpga_corr, "ratio", ...
        "independent versus FPGA phase"; ...
    "constant_delay_best_improvement_cycles", zero_shift0 - best_zero, ...
        "cycles", "zero-crossing delay scan"; ...
    "intervals_with_non113_crossing_count", non113, "count", ...
        "direct cycle count"; ...
    "saved_fractional_peak_distances", fractional_count, "count", ...
        "peak MAT inspection"; ...
    "extractor_uses_integer_xcorr_lag", double(integer_xcorr), ...
        "boolean", "extractor source audit"; ...
    "synthetic_estimator_worst_rms_output_cycles", ...
        max(calibration.accuracy.phase_error_rms_output_cycles(1:3)), ...
        "cycles", "known-truth calibration"; ...
    "real_pll_minus_reference_rms_cycles", ...
        sqrt(mean(ceiling.real.pll_minus_reference_error.^2)), ...
        "cycles", "frozen PLL decomposition"; ...
    "exact113_synthetic_pll_rms_cycles_p9", ...
        sqrt(mean(ceiling.synthetic.pll_residual_error.^2)), ...
        "cycles", "exact-cycle event validation"};
if ~isempty(pi_refinement)
    selected_row = pi_refinement.metrics.candidate == ...
        pi_refinement.selected_candidate.id;
    rows(end + 1, :) = {"selected_pi_p_product_shift", ...
        pi_refinement.metrics.p_product_shift(selected_row), ...
        "bits", "reference-only PI refinement"};
    rows(end + 1, :) = {"selected_pi_exact113_rms_cycles", ...
        pi_refinement.metrics.exact113_rms_cycles(selected_row), ...
        "cycles", "reference-only PI refinement"};
    rows(end + 1, :) = {"selected_pi_real_posterior_rms_cycles", ...
        sqrt(mean(selected_posterior.recovered_interval_error.^2)), ...
        "cycles", "posterior after candidate freeze"};
end
evidence = cell2table(rows, ...
    'VariableNames', {'evidence', 'value', 'unit', 'source'});
evidence.evidence = string(evidence.evidence);
if iscell(evidence.value)
    evidence.value = cell2mat(evidence.value);
end
evidence.unit = string(evidence.unit);
evidence.source = string(evidence.source);
end

function decision = make_root_cause_decision(evidence, calibration, pi_refinement)
value = @(name) evidence.value(evidence.evidence == name);
decision.pi_is_primary_limit = ...
    value("real_pll_minus_reference_rms_cycles") > ...
    0.5 * value("real_zero_crossing_rms_cycles");
decision.fpga_detector_is_primary_limit = ...
    value("zero_fpga_interval_correlation") < 0.9;
decision.constant_delay_is_primary_limit = ...
    value("constant_delay_best_improvement_cycles") > ...
    0.25 * value("real_zero_crossing_rms_cycles");
decision.reference_estimators_pass_known_truth = ...
    value("synthetic_estimator_worst_rms_output_cycles") < 0.1;
decision.every_interval_contains_113_cycles = ...
    value("intervals_with_non113_crossing_count") == 0;
decision.saved_peak_data_are_subsample = ...
    value("saved_fractional_peak_distances") > 0;
decision.extractor_uses_integer_lag = ...
    value("extractor_uses_integer_xcorr_lag") ~= 0;
decision.real_residual_to_exact113_ratio = ...
    value("real_zero_crossing_rms_cycles") / ...
    value("exact113_synthetic_pll_rms_cycles_p9");
decision.detector_cordic_am_to_pm_output_cycles = ...
    calibration.am_to_pm.false_phase_output_cycles( ...
    calibration.am_to_pm.method == "fpga_cordic");
decision.primary_issue = [ ...
    'Saved posterior peak timestamps are not at a constant phase of the measured ' ...
    'reference. The saved peak extractor is integer-lag, not sub-sample; ' ...
    'this posterior timing/reference inconsistency dominates the residual.'];
if isempty(pi_refinement)
    decision.secondary_issue = [ ...
        'The original P shift 12 PI was underdamped. P shift 9 reduces the ' ...
        'remaining loop-only error to about one output cycle.'];
else
    decision.secondary_issue = sprintf([ ...
        'The original P shift 12 PI was underdamped. The tested ' ...
        'reference-only optimum is %s; shift 6 crosses into instability.'], ...
        pi_refinement.selected_candidate.id);
end
end

function value = metric_value(table_value, method, field)
value = table_value.(field)(table_value.method == method);
end

function value = pair_value(table_value, left, right, field)
use = (table_value.left_method == left & table_value.right_method == right) | ...
    (table_value.left_method == right & table_value.right_method == left);
value = table_value.(field)(use);
end

function provenance = build_provenance(replay_path, reference_path, ...
    peak_path, extractor_path)
role = ["frozen_replay"; "reference_waveform"; ...
    "peak_posterior"; "peak_extractor_source"];
path = [replay_path; reference_path; peak_path; extractor_path];
sha256 = strings(size(path));
for k = 1:numel(path)
    if isfile(path(k)), sha256(k) = dpll.file_sha256(path(k)); end
end
provenance = table(role, path, sha256);
end

function files = make_audit_figures(audit, figure_dir, show_figures)
visibility = 'off';
if show_figures, visibility = 'on'; end
files.estimators = make_estimator_figure(audit, figure_dir, visibility);
files.detector = make_detector_figure(audit, figure_dir, visibility);
files.budget = make_budget_figure(audit, figure_dir, visibility);
files.timing = make_timing_figure(audit, figure_dir, visibility);
end

function files = make_estimator_figure(audit, figure_dir, visibility)
fig = figure('Visible', visibility, 'Color', 'w', ...
    'Name', 'Independent reference phase estimators');
layout = tiledlayout(fig, 3, 1, 'TileSpacing', 'compact', ...
    'Padding', 'compact');
title(layout, ...
    'Real peaks evaluated by independently calibrated reference phases');
time_s = audit.validation.peak_time_s(2:end);
colors = lines(numel(audit.method_names));
nexttile; hold on;
for k = 1:numel(audit.method_names)
    plot(time_s, audit.interval_errors{k}, '.-', ...
        'Color', colors(k, :), ...
        'DisplayName', strrep(audit.method_names(k), '_', ' '));
end
yline(0, '--k', 'HandleVisibility', 'off');
ylabel('113-cycle error (output cycles)'); grid on;
legend('Location', 'best');

nexttile;
bar(1:height(audit.method_metrics), ...
    audit.method_metrics.rms_cycles, 0.65);
xticks(1:height(audit.method_metrics));
xticklabels(strrep(audit.method_metrics.method, '_', ' '));
xtickangle(15); ylabel('RMS (output cycles)'); grid on;

nexttile;
zero_error = audit.interval_errors{1};
hold on;
for k = 2:numel(audit.method_names)
    scatter(zero_error, audit.interval_errors{k}, 12, ...
        colors(k, :), 'filled', ...
        'DisplayName', strrep(audit.method_names(k), '_', ' '));
end
all_error = zero_error(:);
for k = 2:numel(audit.method_names)
    all_error = [all_error; audit.interval_errors{k}(:)]; %#ok<AGROW>
end
limit = 1.08 * max(abs(all_error));
plot([-limit limit], [-limit limit], '--k', ...
    'HandleVisibility', 'off');
xlim([-limit limit]); ylim([-limit limit]);
xlabel('Zero-crossing error (cycles)');
ylabel('Other estimator error (cycles)'); grid on;
legend('Location', 'best');
files = dpll.export_paper_figure(fig, ...
    fullfile(figure_dir, 'independent_reference_phase_estimators'), ...
    [7.2 7.8]);
if strcmp(visibility, 'off'), close(fig); end
end

function files = make_detector_figure(audit, figure_dir, visibility)
response = audit.calibration.response;
fig = figure('Visible', visibility, 'Color', 'w', ...
    'Name', 'Detector transfer and AM-to-PM');
layout = tiledlayout(fig, 3, 1, 'TileSpacing', 'compact', ...
    'Padding', 'compact');
title(layout, 'Known-truth detector transfer, group delay, and AM-to-PM');
selected = ["fpga_post_cic", "fpga_post_iir", "fpga_cordic"];
colors = lines(numel(selected));
nexttile; hold on;
for k = 1:numel(selected)
    use = response.method == selected(k);
    plot(response.frequency_hz(use), response.gain_db(use), 'o-', ...
        'Color', colors(k, :), ...
        'DisplayName', strrep(selected(k), '_', ' '));
end
yline(0, '--k', 'HandleVisibility', 'off');
ylabel('Gain (dB)'); grid on; legend('Location', 'best');

nexttile; hold on;
for k = 1:numel(selected)
    use = response.method == selected(k);
    plot(response.frequency_hz(use), response.phase_deg(use), 'o-', ...
        'Color', colors(k, :), ...
        'DisplayName', strrep(selected(k), '_', ' '));
end
ylabel('Phase (deg)'); grid on; legend('Location', 'best');

nexttile;
am = audit.calibration.am_to_pm;
bar(1:height(am), am.false_phase_output_cycles, 0.65);
xticks(1:height(am)); xticklabels(strrep(am.method, '_', ' '));
xtickangle(18); ylabel('False phase (output cycles)');
xlabel('35% AM at 50 Hz with harmonic-shape variation'); grid on;
files = dpll.export_paper_figure(fig, ...
    fullfile(figure_dir, 'detector_transfer_and_am_to_pm'), [7.2 7.4]);
if strcmp(visibility, 'off'), close(fig); end
end

function files = make_budget_figure(audit, figure_dir, visibility)
fig = figure('Visible', visibility, 'Color', 'w', ...
    'Name', 'DPLL root-cause error budget');
labels = ["Fixed clock"; "Real PLL residual"; ...
    "Direct zero-cross reference"; "FPGA reference"; ...
    "PLL minus reference"; "Exact-113 synthetic PLL"];
if isempty(audit.pi_refinement)
    selected_exact_rms = ...
        sqrt(mean(audit.reference_ceiling.synthetic.pll_residual_error.^2));
else
    selected_row = audit.pi_refinement.metrics.candidate == ...
        audit.pi_refinement.selected_candidate.id;
    selected_exact_rms = ...
        audit.pi_refinement.metrics.exact113_rms_cycles(selected_row);
end
values = [ ...
    sqrt(mean(audit.validation.uncompensated_interval_error_output_cycles.^2)); ...
    sqrt(mean(audit.validation.recovered_interval_error.^2)); ...
    audit.method_metrics.rms_cycles( ...
        audit.method_metrics.method == "zero_crossing"); ...
    audit.method_metrics.rms_cycles( ...
        audit.method_metrics.method == "fpga_detector_reconstruction"); ...
    sqrt(mean(audit.reference_ceiling.real.pll_minus_reference_error.^2)); ...
    selected_exact_rms];
barh(1:numel(values), values, 0.65);
yticks(1:numel(values)); yticklabels(labels);
xlabel('RMS interval error (output cycles)'); grid on;
title('Error budget separates terminal mismatch from loop-only error');
files = dpll.export_paper_figure(fig, ...
    fullfile(figure_dir, 'dpll_root_cause_error_budget'), [7.2 4.6]);
if strcmp(visibility, 'off'), close(fig); end
end

function files = make_timing_figure(audit, figure_dir, visibility)
fig = figure('Visible', visibility, 'Color', 'w', ...
    'Name', 'Timing and peak-resolution audit');
layout = tiledlayout(fig, 3, 1, 'TileSpacing', 'compact', ...
    'Padding', 'compact');
title(layout, 'Fixed-delay scan and integer-lag peak-position signature');
nexttile; hold on;
methods = unique(audit.delay_scan.method, 'stable');
colors = lines(max(numel(methods), numel(audit.method_names)));
for k = 1:numel(methods)
    use = audit.delay_scan.method == methods(k);
    plot(1e3 * audit.delay_scan.shift_s(use), ...
        audit.delay_scan.std_cycles(use), 'LineWidth', 1.0, ...
        'Color', colors(k, :), ...
        'DisplayName', strrep(methods(k), '_', ' '));
end
xlabel('Reference time shift (ms)'); ylabel('Residual std (cycles)');
grid on; legend('Location', 'best');

nexttile; hold on;
for k = 1:numel(audit.method_names)
    phase_fraction = mod(audit.method_phase_at_peak_cycles{k}, 1);
    phase_fraction = unwrap(2 * pi * phase_fraction) / (2 * pi);
    phase_fraction = phase_fraction - mean(phase_fraction);
    plot(audit.validation.peak_time_s, ...
        audit.config.pulse.output_multiplier * phase_fraction, ...
        'Color', colors(k, :), ...
        'DisplayName', strrep(audit.method_names(k), '_', ' '));
end
ylabel('Reference phase at peak (output cycles)');
grid on; legend('Location', 'best');

nexttile;
zero = audit.interval_errors{1};
autocorrelation = nan(12, 1);
for lag = 1:12
    autocorrelation(lag) = corr(zero(1:end-lag), zero(1+lag:end));
end
stem(1:12, autocorrelation, 'filled');
yline(0, '--k'); xlabel('Lag (pulses)');
ylabel('Zero-crossing error autocorrelation'); grid on;
files = dpll.export_paper_figure(fig, ...
    fullfile(figure_dir, 'timing_and_peak_resolution_audit'), [7.2 7.4]);
if strcmp(visibility, 'off'), close(fig); end
end

function report_path = write_audit_report(audit, output_dir)
report_path = fullfile(output_dir, 'dpll_root_cause_report.md');
file_id = fopen(report_path, 'w');
if file_id < 0
    error('dpll:ReportOpenFailed', 'Cannot create report: %s', report_path);
end
cleanup = onCleanup(@() fclose(file_id)); %#ok<NASGU>
fprintf(file_id, '# DPLL root-cause audit\n\n');
fprintf(file_id, 'Generated: %s\n\n', audit.created_at);
fprintf(file_id, ['Calibration used synthetic/reference-only data and froze ' ...
    'before posterior peak intervals loaded: **true**.\n\n']);
fprintf(file_id, '## Decision\n\n');
fprintf(file_id, '**Primary:** %s\n\n', audit.decision.primary_issue);
fprintf(file_id, '**Secondary:** %s\n\n', audit.decision.secondary_issue);
fprintf(file_id, '## Independent real-reference estimators\n\n');
fprintf(file_id, ['| Method | RMS (cycles) | Std (cycles) | Fast std ' ...
    '(cycles) | Corr. with PLL |\n']);
fprintf(file_id, '|---|---:|---:|---:|---:|\n');
for k = 1:height(audit.method_metrics)
    row = audit.method_metrics(k, :);
    fprintf(file_id, '| %s | %.6f | %.6f | %.6f | %.6f |\n', ...
        strrep(row.method, '_', ' '), row.rms_cycles, row.std_cycles, ...
        row.fast_std_cycles, row.correlation_with_pll_residual);
end
fprintf(file_id, '\nAll covered intervals contain exactly **113** positive ');
fprintf(file_id, 'reference crossings: **%s**.\n\n', ...
    string(audit.decision.every_interval_contains_113_cycles));
fprintf(file_id, '## Known-truth calibration\n\n');
fprintf(file_id, ['| Method | Phase error RMS (output cycles) |\n' ...
    '|---|---:|\n']);
for k = 1:height(audit.calibration.accuracy)
    fprintf(file_id, '| %s | %.6f |\n', ...
        strrep(audit.calibration.accuracy.method(k), '_', ' '), ...
        audit.calibration.accuracy.phase_error_rms_output_cycles(k));
end
fprintf(file_id, '\n## Detector group-delay summary\n\n');
fprintf(file_id, ['| Method | Group delay (us) | Gain span (dB) |\n' ...
    '|---|---:|---:|\n']);
for k = 1:height(audit.detector_group_delay)
    fprintf(file_id, '| %s | %.6f | %.6f |\n', ...
        strrep(audit.detector_group_delay.method(k), '_', ' '), ...
        audit.detector_group_delay.fitted_group_delay_us(k), ...
        audit.detector_group_delay.gain_span_db(k));
end
fprintf(file_id, '\n## Peak extraction evidence\n\n');
for k = 1:height(audit.extractor_audit)
    fprintf(file_id, '- %s: **%s**. %s\n', ...
        audit.extractor_audit.check(k), ...
        string(audit.extractor_audit.result(k)), ...
        audit.extractor_audit.evidence(k));
end
fprintf(file_id, '\n## Error budget\n\n');
fprintf(file_id, '- Real PLL residual: **%.6f cycles RMS**.\n', ...
    sqrt(mean(audit.validation.recovered_interval_error.^2)));
fprintf(file_id, ['- Direct zero-cross reference/peak residual: ' ...
    '**%.6f cycles RMS**.\n'], ...
    metric_value(audit.method_metrics, "zero_crossing", 'rms_cycles'));
fprintf(file_id, ['- FPGA reconstructed reference/peak residual: ' ...
    '**%.6f cycles RMS**.\n'], ...
    metric_value(audit.method_metrics, ...
    "fpga_detector_reconstruction", 'rms_cycles'));
fprintf(file_id, ['- PLL minus detector-observable reference: ' ...
    '**%.6f cycles RMS**.\n'], ...
    sqrt(mean(audit.reference_ceiling.real.pll_minus_reference_error.^2)));
fprintf(file_id, ['- Exact-113 synthetic event PLL residual: ' ...
    '**%.6f cycles RMS**.\n\n'], ...
    sqrt(mean(audit.reference_ceiling.synthetic.pll_residual_error.^2)));
if ~isempty(audit.pi_refinement)
    selected_row = audit.pi_refinement.metrics.candidate == ...
        audit.pi_refinement.selected_candidate.id;
    fprintf(file_id, '## Final reference-only PI refinement\n\n');
    fprintf(file_id, '- Selected candidate: **%s**.\n', ...
        audit.pi_refinement.selected_candidate.id);
    fprintf(file_id, '- Selected exact-113 RMS: **%.6f cycles**.\n', ...
        audit.pi_refinement.metrics.exact113_rms_cycles(selected_row));
    fprintf(file_id, '- Selected 80 Hz residual gain: **%.6f dB**.\n', ...
        audit.pi_refinement.metrics.frequency_residual_gain_db(selected_row));
    fprintf(file_id, '- Frozen posterior RMS after selection: **%.6f cycles**.\n', ...
        sqrt(mean(audit.selected_pi_posterior.recovered_interval_error.^2)));
    fprintf(file_id, ['- P shift 6 controller saturation rate at 80 Hz: ' ...
        '**%.6f**.\n\n'], ...
        audit.pi_refinement.instability_boundary.controller_saturation_rate( ...
        audit.pi_refinement.instability_boundary.p_product_shift == 6));
end
fprintf(file_id, '## Engineering conclusion\n\n');
fprintf(file_id, ['The current P-shift-9 loop tracks the phase presented by ' ...
    'the detector to about one output cycle. Independent zero-crossing, ' ...
    'local-sinusoid, and analytic phase estimators reproduce the large real ' ...
    'peak/reference residual, so the CIC/IIR/CORDIC detector is not its ' ...
    'dominant source. Constant-delay correction is ineffective. The saved ' ...
    'peak file contains integer-valued distances, and the extraction source ' ...
    'rounds locations then selects an integer xcorr lag without sub-sample ' ...
    'interpolation. The IIR contributes about 238 us of group delay, but ' ...
    'constant-delay correction removes only a small fraction of the real ' ...
    'residual. Therefore this dataset cannot support attributing the ' ...
    'remaining fast residual to PI bandwidth or claiming sub-sample peak ' ...
    'ground truth.\n']);
end
