function validation = run_peak_validation(replay_mat_path, peak_mat_path, ...
    validation_mat_path, make_plot)
%RUN_PEAK_VALIDATION Load a frozen replay and run posterior-only validation.

arguments
    replay_mat_path (1,1) string
    peak_mat_path (1,1) string
    validation_mat_path (1,1) string = ""
    make_plot (1,1) logical = true
end
if ~isfile(replay_mat_path)
    error('dpll:ReplayNotFound', 'Replay MAT file does not exist: %s', replay_mat_path);
end
frozen = load(replay_mat_path, 'result');
if ~isfield(frozen, 'result')
    error('dpll:MissingReplayResult', 'Replay MAT file does not contain result.');
end
validation = validate_peak_alignment(frozen.result, peak_mat_path, make_plot);
if strlength(validation_mat_path) > 0
    save(validation_mat_path, 'validation', '-v7.3');
end
fprintf(['Posterior validation complete: %d peaks, recovered interval ' ...
    'mean %.6f, RMS error %.6f output cycles.\n'], ...
    validation.summary.peak_count, ...
    validation.summary.recovered_interval_mean, ...
    validation.summary.recovered_interval_rms_error);
fprintf(['  Slow residual %.3f%% (%+.2f dB), fast residual %.3f%% ' ...
    '(%+.2f dB), window %d pulses.\n'], ...
    100 * validation.summary.slow_residual_ratio, ...
    validation.summary.slow_suppression_db, ...
    100 * validation.summary.fast_residual_ratio, ...
    validation.summary.fast_suppression_db, ...
    validation.summary.slow_window_pulses);
end
