%% Complete DPLL reference, detector, timing, and posterior root-cause audit
% Edit this first section, then click MATLAB Run. A fresh calibration takes
% several minutes and never uses posterior peak intervals.

close all;
clc;
scriptDir = fileparts(mfilename('fullpath'));

replayMat = fullfile(scriptDir, 'data', ...
    'dat5_dpll_replay_result_optimized_pShift9.mat');
referenceMat = fullfile(scriptDir, 'data', ...
    'dat5_cc62M5_ch2_CIC_DCBlock_3M125.mat');
peakMat = fullfile(scriptDir, 'data', ...
    'dat5_cc62M5采样峰距离.mat');
peakExtractorScript = ...
    'E:\JiangSiyi\THz器件采样\光源稳定性分析\20260723\PCI_Read_Time_Run_DoublePeak.m';

referenceSampleCount = 4194304;
localWindowCycles = 8;
analyticHalfBandwidthHz = 500;
fixedDelayScanSeconds = (-0.003:0.00001:0.003).';
slowWindowPulses = 21;
reuseCalibration = false;
showFigures = true;

runTag = char(datetime('now', 'Format', 'yyyyMMdd_HHmmss'));
resultRoot = fullfile(scriptDir, 'results', ...
    'dpll_root_cause_audit', runTag);

audit = run_dpll_root_cause_audit( ...
    string(replayMat), string(referenceMat), string(peakMat), ...
    string(peakExtractorScript), string(resultRoot), ...
    reference_sample_count=referenceSampleCount, ...
    local_window_cycles=localWindowCycles, ...
    analytic_half_bandwidth_hz=analyticHalfBandwidthHz, ...
    delay_scan_s=fixedDelayScanSeconds, ...
    slow_window_pulses=slowWindowPulses, ...
    reuse_calibration=reuseCalibration, ...
    show_figures=showFigures);

fprintf('\nDone. Workspace variables: audit, resultRoot\n');
