function report_path = write_high_frequency_investigation_report(root_dir)
%WRITE_HIGH_FREQUENCY_INVESTIGATION_REPORT Write the consolidated report.

l1 = load(fullfile(root_dir, 'layer1', 'layer1_complete.mat'), 'layer1');
l2 = load(fullfile(root_dir, 'layer2', 'layer2_complete.mat'), 'layer2');
l3p = load(fullfile(root_dir, 'layer3p', 'layer3p_complete.mat'), 'layer3p');
l3i = load(fullfile(root_dir, 'layer3i', 'layer3i_complete.mat'), 'layer3i');
l3s = load(fullfile(root_dir, 'layer3s', 'layer3s_complete.mat'), 'layer3s');
real_data = load(fullfile(root_dir, 'real_candidates', ...
    'real_candidate_comparison.mat'), 'comparison');
posterior_data = load(fullfile(root_dir, 'posterior_validation', ...
    'posterior_candidate_comparison.mat'), 'comparison');
final_data = load(fullfile(root_dir, 'final_response', ...
    'final_response_complete.mat'), 'final_response');
cold_data = load(fullfile(root_dir, 'cold_start', ...
    'cold_start_regression.mat'), 'regression');

report_path = fullfile(root_dir, 'high_frequency_investigation_report.md');
file_id = fopen(report_path, 'w', 'n', 'UTF-8');
if file_id < 0, error('dpll:ReportOpenFailed', 'Cannot create report.'); end
cleanup = onCleanup(@() fclose(file_id));
fprintf(file_id, '# DPLL high-frequency tracking investigation\n\n');
fprintf(file_id, 'Generated: %s\n\n', ...
    char(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss')));
fprintf(file_id, ['All controller selection used synthetic/internal metrics. ' ...
    'Measured pulse positions were loaded only after five candidates were frozen.\n\n']);

fprintf(file_id, '## Layer 1: linearity and autonomous motion\n\n');
pure = l1.layer1.metrics(l1.layer1.metrics.phase_modulation_rad == 0, :);
fprintf(file_id, ['With no modulation, output-frequency std was %.6g Hz and ' ...
    'phase RMS was %.6g rad. No large autonomous oscillation was present.\n\n'], ...
    pure.output_frequency_std_hz, pure.phase_error_rms_rad);
small = l1.layer1.metrics(l1.layer1.metrics.phase_modulation_rad == 0.03, :);
fprintf(file_id, '| fm (Hz) | Small-signal gain (dB) | Phase (deg) | Fit R2 |\n');
fprintf(file_id, '|---:|---:|---:|---:|\n');
for k = 1:height(small)
    fprintf(file_id, '| %.0f | %.4f | %.3f | %.5f |\n', ...
        small.modulation_frequency_hz(k), small.closed_loop_gain_db(k), ...
        small.closed_loop_phase_deg(k), small.output_fit_r_squared(k));
end
fprintf(file_id, ['\nThe 60/80 Hz gain was amplitude-independent through beta=0.075 rad. ' ...
    'At beta=0.15 rad the response became nonlinear, so nonlinearity is a ' ...
    'consequence of the small-signal resonance, not its cause.\n\n']);

fprintf(file_id, '## Layer 2: PI and FLL isolation\n\n');
write_config_rows(file_id, l2.layer2.metrics, 80, ...
    {'full_loop','pi_only','fll_62k5','fll_125k'});
fprintf(file_id, ['Removing FLL increased the 80 Hz peak. FLL is not the source ' ...
    'of the resonance and supplies only weak damping.\n\n']);

fprintf(file_id, '## Layer 3: parameter and architecture tests\n\n');
fprintf(file_id, '### Effective P sweep at 80 Hz\n\n');
write_parameter_rows(file_id, l3p.layer3p.metrics, 80, 'p');
fprintf(file_id, '\n### Ki sweep at P shift 9, 80 Hz\n\n');
write_parameter_rows(file_id, l3i.layer3i.metrics, 80, 'i');
fprintf(file_id, '\n### FPGA-realizable structure screen, 80 Hz\n\n');
write_config_rows(file_id, l3s.layer3s.metrics, 80, ...
    {'baseline','multirate_kf250k','multirate_kf4m', ...
    'phase_lead8','phase_lead16','ff0p25','ff0p5','ff1p0'});
fprintf(file_id, ['The block-once FLL with Kf multiplied by 16 reproduced the ' ...
    'baseline within 0.01 dB. Replay timing is therefore not the limiting ' ...
    'mechanism. Phase prediction was too weak, and direct FLL feedforward had ' ...
    'frequency-dependent phase and failed for both coefficient signs.\n\n']);

fprintf(file_id, '## Real-reference replay before posterior validation\n\n');
real_metrics = real_data.comparison.metrics;
fprintf(file_id, '| Candidate | Phase RMS (rad) | 40-100 Hz phase RMS | Tracking std (Hz) |\n');
fprintf(file_id, '|---|---:|---:|---:|\n');
for k = 1:height(real_metrics)
    fprintf(file_id, '| %s | %.7f | %.7f | %.6f |\n', ...
        real_metrics.candidate_id(k), real_metrics.phase_rms_rad(k), ...
        real_metrics.phase_band_40_100_rms_rad(k), ...
        real_metrics.tracking_frequency_std_hz(k));
end

fprintf(file_id, '\n## Frozen posterior peak validation\n\n');
post = posterior_data.comparison.metrics;
fprintf(file_id, '| Candidate | Interval RMS | Fast std | Slow suppression | Fast suppression |\n');
fprintf(file_id, '|---|---:|---:|---:|---:|\n');
for k = 1:height(post)
    fprintf(file_id, '| %s | %.5f | %.5f | %.3f dB | %.3f dB |\n', ...
        post.candidate_id(k), post.recovered_interval_rms_error_cycles(k), ...
        post.fast_recovered_std_cycles(k), post.slow_suppression_db(k), ...
        post.fast_suppression_db(k));
end

improvement_percent = 100 * (post.recovered_interval_rms_error_cycles(1) - ...
    post.recovered_interval_rms_error_cycles(end)) / ...
    post.recovered_interval_rms_error_cycles(1);
fprintf(file_id, ['\nThe selected candidate reduced interval RMS by %.2f%%. ' ...
    'The three P-shift-9 Ki candidates differed by only %.5f cycles, so the ' ...
    'posterior does not support claiming a sharply tuned Ki optimum. Ki=2.5M ' ...
    'is retained for its stronger low-frequency phase regulation.\n'], ...
    improvement_percent, max(post.recovered_interval_rms_error_cycles(3:5)) - ...
    min(post.recovered_interval_rms_error_cycles(3:5)));

fprintf(file_id, '\n## Selected configuration\n\n');
fprintf(file_id, ['- Post-IQ CIC output shift: **9**\n' ...
    '- TRACK Kp: **6000000**\n' ...
    '- TRACK Ki: **2500000**\n' ...
    '- HDL P_PRODUCT_SHIFT: **9**\n' ...
    '- BLEND Kp: **750000** (preserves the former effective BLEND P)\n' ...
    '- FLL structure and Kf_track: unchanged\n\n']);
final = final_data.final_response.response;
fprintf(file_id, ['The selected loop has %.3f dB tracking gain, %.2f deg phase, ' ...
    'and %.3f dB residual gain at 80 Hz.\n\n'], ...
    final.closed_loop_gain_db(end), final.closed_loop_phase_deg(end), ...
    final.frequency_residual_gain_db(end));
cold = cold_data.regression.metrics;
fprintf(file_id, ['Cold-start TRACK entry was %.6f s for baseline and %.6f s for ' ...
    'the optimized loop; both remained in TRACK with zero controller saturation.\n\n'], ...
    cold.first_track_time_s(1), cold.first_track_time_s(2));
fprintf(file_id, ['The remaining pulse-interval RMS, %.5f cycles, is essentially ' ...
    'at the independently estimated reference/pulse consistency floor. ' ...
    'Further loop bandwidth alone should not be expected to drive it to zero.\n'], ...
    post.recovered_interval_rms_error_cycles(end));
end

function write_config_rows(file_id, metrics, frequency_hz, ids)
subset = metrics(metrics.modulation_frequency_hz == frequency_hz & ...
    ismember(metrics.config_id, string(ids)), :);
fprintf(file_id, '| Configuration | Gain (dB) | Phase (deg) | Residual (dB) | R2 |\n');
fprintf(file_id, '|---|---:|---:|---:|---:|\n');
for k = 1:height(subset)
    fprintf(file_id, '| %s | %.4f | %.3f | %.4f | %.5f |\n', ...
        subset.config_id(k), subset.closed_loop_gain_db(k), ...
        subset.closed_loop_phase_deg(k), ...
        subset.frequency_residual_gain_db(k), subset.output_fit_r_squared(k));
end
fprintf(file_id, '\n');
end

function write_parameter_rows(file_id, metrics, frequency_hz, kind)
subset = metrics(metrics.modulation_frequency_hz == frequency_hz, :);
if kind == 'p'
    parameter = arrayfun(@(shift, kp) sprintf('P shift %g, Kp %.0f', ...
        shift, kp), subset.p_product_shift, subset.kp_track, ...
        'UniformOutput', false);
else
    parameter = arrayfun(@(ki) sprintf('Ki %.0f', ki), subset.ki_track, ...
        'UniformOutput', false);
end
fprintf(file_id, '| Parameter | Gain (dB) | Phase (deg) | Residual (dB) |\n');
fprintf(file_id, '|---|---:|---:|---:|\n');
for k = 1:height(subset)
    fprintf(file_id, '| %s | %.4f | %.3f | %.4f |\n', parameter{k}, ...
        subset.closed_loop_gain_db(k), subset.closed_loop_phase_deg(k), ...
        subset.frequency_residual_gain_db(k));
end
end
