function report = write_dpll_complete_validation_report( ...
    output_root, prior_audit_root)
%WRITE_DPLL_COMPLETE_VALIDATION_REPORT Consolidate all frozen evidence.

arguments
    output_root (1,1) string
    prior_audit_root (1,1) string
end

paths.counter_summary = fullfile(output_root, 'detector_counterfactual', ...
    'tables', 'detector_counterfactual_summary.csv');
paths.counter_response = fullfile(output_root, 'detector_counterfactual', ...
    'tables', 'detector_counterfactual_frequency_response.csv');
paths.real_metrics = fullfile(output_root, 'real_detector_variants', ...
    'tables', 'real_detector_variant_metrics.csv');
paths.causal_metrics = fullfile(output_root, 'final_candidate', ...
    'causal_predictability', 'tables', 'causal_predictor_metrics.csv');
paths.posterior_metrics = fullfile(output_root, 'final_candidate', ...
    'posterior_causality', 'tables', 'posterior_series_metrics.csv');
paths.posterior_correlation = fullfile(output_root, 'final_candidate', ...
    'posterior_causality', 'tables', 'posterior_lag_correlation.csv');
paths.cold_metrics = fullfile(output_root, 'cold_start', ...
    'cold_start_metrics.csv');
paths.group_delay = fullfile(prior_audit_root, 'tables', ...
    'detector_group_delay_summary.csv');
paths.root_evidence = fullfile(prior_audit_root, 'tables', ...
    'root_cause_evidence.csv');
names = fieldnames(paths);
for k = 1:numel(names)
    if ~isfile(paths.(names{k}))
        error('dpll:MissingCompleteAuditArtifact', ...
            'Required audit artifact is missing: %s', paths.(names{k}));
    end
end

counter = readtable(paths.counter_summary, 'TextType', 'string');
response = readtable(paths.counter_response, 'TextType', 'string');
real_metrics = readtable(paths.real_metrics, 'TextType', 'string');
causal = readtable(paths.causal_metrics, 'TextType', 'string');
posterior = readtable(paths.posterior_metrics, 'TextType', 'string');
correlation = readtable(paths.posterior_correlation, 'TextType', 'string');
cold = readtable(paths.cold_metrics, 'TextType', 'string');
group_delay = readtable(paths.group_delay, 'TextType', 'string');
root_evidence = readtable(paths.root_evidence, 'TextType', 'string');

value = @(table_value, id, column) ...
    table_value.(column)(table_value.variant_id == id);
series_value = @(id, column) ...
    posterior.(column)(posterior.series == id);

p12_exact = value(counter, "hardware_p12", 'exact113_rms_cycles');
p8_rtl_exact = value(counter, "rtl_two_2k", 'exact113_rms_cycles');
p8_oracle_exact = value(counter, "oracle_zero", 'exact113_rms_cycles');
p8_decoupled_exact = value(counter, "rtl_decoupled", 'exact113_rms_cycles');
real_2k_exact = value(real_metrics, "two_2k", 'exact113_rms_cycles');
real_8k_exact = value(real_metrics, "two_8k", 'exact113_rms_cycles');
reference_event_rms = series_value("analytic_reference_event", 'rms_cycles');
loop_only_rms = series_value("loop_only", 'rms_cycles');
pll_total_rms = series_value("pll_output", 'rms_cycles');
predictor_floor = series_value("causal_predictor_floor", 'rms_cycles');
reference_lag1 = series_value("analytic_reference_event", ...
    'lag1_correlation');
zero_lag_corr = correlation.correlation( ...
    correlation.source == "analytic_reference_event" & ...
    correlation.target == "pll_output" & ...
    correlation.lag_pulses == 0);
current_predictor = causal(causal.horizon_steps == 0, :);
[best_predictor_floor, best_predictor_index] = min( ...
    current_predictor.exact113_prediction_floor_rms_cycles);
best_predictor_method = current_predictor.method(best_predictor_index);

fm80 = response(response.frequency_hz == 80, :);
p12_80 = fm80.frequency_residual_gain_db(fm80.variant_id == "hardware_p12");
p8_80 = fm80.frequency_residual_gain_db(fm80.variant_id == "rtl_two_2k");
oracle_80 = fm80.frequency_residual_gain_db(fm80.variant_id == "oracle_zero");

baseline_cold = cold(cold.config_id == "baseline", :);
final_cold = cold(cold.config_id == "optimized", :);
final_cfg = dpll_recommended_config(20000);
hardware = build_hardware_table(final_cfg);
iir_delay = build_iir_delay_table(final_cfg, group_delay);
metrics = build_decision_metrics(p12_exact, p8_rtl_exact, ...
    p8_oracle_exact, p8_decoupled_exact, real_2k_exact, real_8k_exact, ...
    reference_event_rms, loop_only_rms, pll_total_rms, predictor_floor, ...
    best_predictor_floor, p12_80, p8_80, oracle_80, ...
    baseline_cold, final_cold);

table_dir = fullfile(output_root, 'tables');
figure_dir = fullfile(output_root, 'figures');
if ~isfolder(table_dir), mkdir(table_dir); end
if ~isfolder(figure_dir), mkdir(figure_dir); end
writetable(metrics, fullfile(table_dir, 'final_decision_metrics.csv'));
writetable(hardware, fullfile(table_dir, ...
    'final_hardware_configuration.csv'));
writetable(iir_delay, fullfile(table_dir, ...
    'iir_variant_group_delay.csv'));
figure_files = make_summary_figure(metrics, figure_dir);

report.schema_version = 1;
report.created_at = char(datetime('now', 'Format', 'yyyy-MM-dd HH:mm:ss Z'));
report.output_root = output_root;
report.prior_audit_root = prior_audit_root;
report.metrics = metrics;
report.hardware = hardware;
report.iir_delay = iir_delay;
report.group_delay = group_delay;
report.root_evidence = root_evidence;
report.best_causal_predictor_method = best_predictor_method;
report.best_causal_predictor_floor_cycles = best_predictor_floor;
report.reference_event_lag1 = reference_lag1;
report.reference_pll_zero_lag_correlation = zero_lag_corr;
report.figure_files = figure_files;
report.primary_internal_cause = ...
    'P_PRODUCT_SHIFT=12 causes a poorly damped 60-120 Hz loop resonance.';
report.secondary_internal_cause = ...
    'Post-IQ CIC shift 8 overloads the CIC/CORDIC path on the real capture.';
report.terminal_system_limit = ...
    ['Pulse-event timestamps do not remain at constant fractional reference ' ...
    'phase; this 8.6-cycle component dominates the final interval residual.'];
report.report_path = fullfile(output_root, ...
    'dpll_complete_validation_report.md');
write_report(report.report_path, report, p12_exact, p8_rtl_exact, ...
    p8_oracle_exact, real_8k_exact, reference_event_rms, loop_only_rms, ...
    pll_total_rms, predictor_floor, reference_lag1, zero_lag_corr, ...
    p12_80, p8_80, oracle_80, baseline_cold, final_cold);
save(fullfile(output_root, 'dpll_complete_validation_summary.mat'), ...
    'report', '-v7.3');
end

function table_value = build_decision_metrics(p12_exact, p8_rtl_exact, ...
    p8_oracle_exact, p8_decoupled_exact, real_2k_exact, real_8k_exact, ...
    reference_event_rms, loop_only_rms, total_rms, predictor_floor, ...
    best_predictor_floor, p12_80, p8_80, oracle_80, baseline_cold, final_cold)
metric = ["p12_synthetic_exact113_rms"; ...
    "p8_rtl_synthetic_exact113_rms"; ...
    "p8_zero_delay_oracle_exact113_rms"; ...
    "p8_decoupled_schedule_exact113_rms"; ...
    "p8_real_2k_exact113_rms"; "p8_real_8k_exact113_rms"; ...
    "pulse_reference_event_rms"; "final_loop_only_rms"; ...
    "final_total_peak_residual_rms"; "final_causal_predictor_floor"; ...
    "best_reference_predictor_exact113_floor"; ...
    "p12_80hz_residual_gain_db"; "p8_80hz_residual_gain_db"; ...
    "oracle_80hz_residual_gain_db"; "baseline_cold_track_time_s"; ...
    "final_cold_track_time_s"; "baseline_cic_saturation_count"; ...
    "baseline_cordic_range_count"; "final_cic_saturation_count"; ...
    "final_cordic_range_count"];
value = [p12_exact; p8_rtl_exact; p8_oracle_exact; p8_decoupled_exact; ...
    real_2k_exact; real_8k_exact; reference_event_rms; loop_only_rms; ...
    total_rms; predictor_floor; best_predictor_floor; p12_80; p8_80; ...
    oracle_80; baseline_cold.first_track_time_s; ...
    final_cold.first_track_time_s; baseline_cold.cic_saturation_count; ...
    baseline_cold.cordic_out_of_range_count; ...
    final_cold.cic_saturation_count; final_cold.cordic_out_of_range_count];
unit = [repmat("output cycles RMS", 11, 1); repmat("dB", 3, 1); ...
    repmat("s", 2, 1); repmat("count", 4, 1)];
table_value = table(metric, value, unit);
end

function table_value = build_hardware_table(cfg)
parameter = ["P_PRODUCT_SHIFT"; "post_iq_cic_output_shift"; ...
    "kp_track"; "ki_track"; "kp_blend"; "track_iir_sections"; ...
    "track_iir_cutoff_hz"; "track_iir_b0_q30"; "track_iir_b1_q30"; ...
    "track_iir_b2_q30"; "track_iir_a1_q30"; "track_iir_a2_q30"; ...
    "kf_track"; "controller_update_mode"];
current = ["12"; "8"; "6000000"; "2500000"; "6000000"; "2"; ...
    "2000"; "configuration dependent"; "configuration dependent"; ...
    "configuration dependent"; "configuration dependent"; ...
    "configuration dependent"; "250000"; "fll_replay"];
recommended = [string(cfg.shifts.p_product); string(cfg.cic.output_shift); ...
    string(cfg.gains.kp_track); string(cfg.gains.ki_track); ...
    string(cfg.gains.kp_blend); string(cfg.iir.sections); ...
    string(cfg.iir.track_cutoff_hz); string(cfg.iir.track.b0); ...
    string(cfg.iir.track.b1); string(cfg.iir.track.b2); ...
    string(cfg.iir.track.a1); string(cfg.iir.track.a2); ...
    string(cfg.gains.kf_track); string(cfg.architecture.controller_update_mode)];
implementation = ["HDL parameter"; "ARM register"; "ARM register"; ...
    "ARM register"; "ARM register"; "unchanged HDL structure"; ...
    repmat("ARM IIR coefficient registers", 6, 1); ...
    "unchanged ARM register"; "unchanged HDL structure"];
table_value = table(parameter, current, recommended, implementation);
end

function table_value = build_iir_delay_table(cfg, measured_delay)
variant = ["two_2k"; "two_4k"; "two_8k"; "one_2k"];
sections = [2; 2; 2; 1];
cutoff_hz = [2000; 4000; 8000; 2000];
filter_group_delay_us = nan(size(cutoff_hz));
estimated_detector_delay_us = nan(size(cutoff_hz));
gain_span_1_200hz_db = nan(size(cutoff_hz));
sample_rate_hz = cfg.input_sample_rate_hz / cfg.cic.rate;
frequency_hz = (1:200).';
cic_delay_us = measured_delay.fitted_group_delay_us( ...
    measured_delay.method == "fpga_post_cic");
for k = 1:numel(cutoff_hz)
    coeff = dpll.design_biquad_q30(cutoff_hz(k), sample_rate_hz);
    z_inverse = exp(-1i * 2 * pi * frequency_hz / sample_rate_hz);
    numerator = double(coeff.b0) + double(coeff.b1) * z_inverse + ...
        double(coeff.b2) * z_inverse.^2;
    denominator = 2^30 + double(coeff.a1) * z_inverse + ...
        double(coeff.a2) * z_inverse.^2;
    transfer = (numerator ./ denominator).^sections(k);
    phase_fit = polyfit(frequency_hz, unwrap(angle(transfer)), 1);
    filter_group_delay_us(k) = -phase_fit(1) / (2 * pi) * 1e6;
    estimated_detector_delay_us(k) = ...
        filter_group_delay_us(k) + cic_delay_us;
    gain_db = 20 * log10(abs(transfer));
    gain_span_1_200hz_db(k) = max(gain_db) - min(gain_db);
end
table_value = table(variant, sections, cutoff_hz, filter_group_delay_us, ...
    estimated_detector_delay_us, gain_span_1_200hz_db);
end

function files = make_summary_figure(metrics, figure_dir)
get = @(name) metrics.value(metrics.metric == name);
fig = figure('Visible', 'off', 'Color', 'w');
layout = tiledlayout(fig, 1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');
nexttile(layout);
internal_values = [get("p12_synthetic_exact113_rms"), ...
    get("p8_rtl_synthetic_exact113_rms"), ...
    get("p8_zero_delay_oracle_exact113_rms"), ...
    get("p8_real_8k_exact113_rms")];
internal_labels = categorical(["P12 RTL"; "P8 RTL"; ...
    "P8 ideal phase"; "P8 + 8 kHz real"], ...
    ["P12 RTL"; "P8 RTL"; "P8 ideal phase"; "P8 + 8 kHz real"]);
bar(internal_labels, internal_values);
ylabel('Exact-113 RMS (output cycles)');
xtickangle(25); grid on; title('Loop-internal interventions');
nexttile(layout);
budget_values = [get("pulse_reference_event_rms"), ...
    get("final_loop_only_rms"), get("final_causal_predictor_floor"), ...
    get("final_total_peak_residual_rms")];
budget_labels = categorical(["Pulse/reference"; "Loop only"; ...
    "Causal floor"; "Total residual"], ...
    ["Pulse/reference"; "Loop only"; "Causal floor"; "Total residual"]);
bar(budget_labels, budget_values);
ylabel('RMS (output cycles)');
xtickangle(25); grid on; title('Final posterior error budget');
title(layout, 'DPLL root-cause summary');
files = dpll.export_paper_figure(fig, ...
    fullfile(figure_dir, 'dpll_complete_root_cause_summary'), [9.0 4.8]);
close(fig);
end

function write_report(path, report, p12_exact, p8_rtl_exact, ...
    p8_oracle_exact, real_8k_exact, reference_event_rms, loop_only_rms, ...
    total_rms, predictor_floor, reference_lag1, zero_lag_corr, ...
    p12_80, p8_80, oracle_80, baseline_cold, final_cold)
file_id = fopen(path, 'w');
if file_id < 0, error('dpll:ReportOpenFailed', 'Cannot write %s.', path); end
cleanup = onCleanup(@() fclose(file_id)); %#ok<NASGU>
fprintf(file_id, '# Complete DPLL validation and root-cause report\n\n');
fprintf(file_id, 'Generated: %s\n\n', report.created_at);
fprintf(file_id, '## Executive conclusion\n\n');
fprintf(file_id, ['There are two distinct problems. Inside the DPLL, ' ...
    '**P_PRODUCT_SHIFT=12** produces an underdamped 60--120 Hz resonance, ' ...
    'and post-IQ CIC shift 8 overloads the real detector path. For the final ' ...
    'pulse-alignment objective, the dominant residual is not inside the ' ...
    'DPLL: pulse timestamps do not remain at one fractional phase of the ' ...
    'measured reference, even though every interval contains 113 integer ' ...
    'reference cycles.\n\n']);

fprintf(file_id, '## Causal isolation\n\n');
fprintf(file_id, '| Experiment | RMS or gain | Result |\n');
fprintf(file_id, '|---|---:|---|\n');
fprintf(file_id, '| P shift 12, exact-113 | %.6f cycles | Internal failure |\n', p12_exact);
fprintf(file_id, '| P shift 8, current detector | %.6f cycles | %.1f%% lower |\n', ...
    p8_rtl_exact, 100 * (1 - p8_rtl_exact / p12_exact));
fprintf(file_id, '| P shift 8, zero-delay ideal phase | %.6f cycles | Delay is secondary |\n', ...
    p8_oracle_exact);
fprintf(file_id, '| P shift 8, real reference, 8 kHz IIR | %.6f cycles | Final internal candidate |\n', ...
    real_8k_exact);
fprintf(file_id, '| P shift 12, 80 Hz residual gain | %+.3f dB | Resonant amplification |\n', ...
    p12_80);
fprintf(file_id, '| P shift 8, 80 Hz residual gain | %+.3f dB | Strong suppression |\n', ...
    p8_80);
fprintf(file_id, '| Ideal phase, 80 Hz residual gain | %+.3f dB | Only marginally better |\n\n', ...
    oracle_80);
measured_cordic_delay = report.group_delay.fitted_group_delay_us( ...
    report.group_delay.method == "fpga_cordic");
final_estimated_delay = report.iir_delay.estimated_detector_delay_us( ...
    report.iir_delay.variant == "two_8k");
fprintf(file_id, ['The measured two-section 2 kHz CIC/IIR/CORDIC delay is ' ...
    '**%.3f us**. The quantized-coefficient estimate for the selected ' ...
    'two-section 8 kHz path is **%.3f us**. Removing detector delay entirely ' ...
    'changes exact-113 RMS from %.6f to %.6f cycles, so delay is a secondary ' ...
    'rather than dominant limit.\n\n'], measured_cordic_delay, ...
    final_estimated_delay, p8_rtl_exact, p8_oracle_exact);

fprintf(file_id, '## Final posterior error budget\n\n');
fprintf(file_id, '| Component | RMS (output cycles) |\n');
fprintf(file_id, '|---|---:|\n');
fprintf(file_id, '| Reference phase at real pulse events | %.6f |\n', reference_event_rms);
fprintf(file_id, '| Final loop-only contribution | %.6f |\n', loop_only_rms);
fprintf(file_id, '| Causal predictor floor | %.6f |\n', predictor_floor);
fprintf(file_id, '| Final recovered peak-interval residual | %.6f |\n\n', total_rms);
fprintf(file_id, ['The reference/event component and final PLL residual ' ...
    'have zero-lag correlation **%.6f**. The reference/event interval has ' ...
    'lag-1 correlation **%.6f**, close to the -0.5 signature of independent ' ...
    'per-event relative phase changes after interval differencing. Under the ' ...
    'stated assumption that extracted peak timestamps are accurate, this is ' ...
    'physical pulse-to-reference timing variation. A reference-only PLL ' ...
    'cannot remove it.\n\n'], zero_lag_corr, reference_lag1);

fprintf(file_id, '## Final FPGA-realizable configuration\n\n');
fprintf(file_id, '| Parameter | Current | Recommended | Implementation |\n');
fprintf(file_id, '|---|---:|---:|---|\n');
for k = 1:height(report.hardware)
    row = report.hardware(k, :);
    fprintf(file_id, '| %s | %s | %s | %s |\n', ...
        row.parameter, row.current, row.recommended, row.implementation);
end

fprintf(file_id, '\n## Cold-start regression\n\n');
fprintf(file_id, ['Baseline TRACK entry: **%.6f s**; final candidate: ' ...
    '**%.6f s**. Both remain in TRACK with zero controller saturation. ' ...
    'Baseline CIC/CORDIC fault counts are **%d/%d**; final counts are ' ...
    '**%d/%d**.\n\n'], baseline_cold.first_track_time_s, ...
    final_cold.first_track_time_s, baseline_cold.cic_saturation_count, ...
    baseline_cold.cordic_out_of_range_count, ...
    final_cold.cic_saturation_count, final_cold.cordic_out_of_range_count);

fprintf(file_id, '## Engineering decision\n\n');
fprintf(file_id, ['Deploy P shift 8, CIC shift 9, Kp/Ki 6000000/2500000, ' ...
    'Kp_blend 375000, and the two-section 8 kHz TRACK IIR. Keep the FLL ' ...
    'structure and Kf unchanged. Do not bypass the IIR and do not add the ' ...
    'multirate scheduling change; neither improves the measured result. A ' ...
    'small causal predictor may reduce the remaining 0.56-cycle loop term, ' ...
    'but it cannot reduce the 8.60-cycle pulse/reference term. Reaching near-' ...
    'zero real peak residual requires addressing pulse-generation timing or ' ...
    'adding pulse-derived feedback, not further PI gain.\n']);
end
