#!/usr/bin/env python3
from __future__ import annotations

import csv
import sys
from pathlib import Path

from dpll_fixed import freq_word_from_hz, unsigned


ROOT = Path(__file__).resolve().parents[2]
REPORT = ROOT / "reports" / "dpll_core_sine_lock_trace_20260629.md"
STABLE_TRACE = ROOT / "reports" / "dpll_core_sine_lock_trace_20260629.csv"


def parse_int(value: str) -> int:
    return int(value, 0)


def parse_float(value: str) -> float:
    return float(value)


def latest_trace() -> Path:
    traces = sorted(
        ROOT.glob("reports/xsim/dpll_core_sine_lock_*/dpll_core_sine_lock_trace.csv"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not traces:
        raise FileNotFoundError("no dpll_core_sine_lock_trace.csv found under reports/xsim")
    return traces[0]


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def write_stable_trace(rows: list[dict[str, str]]) -> None:
    if not rows:
        STABLE_TRACE.write_text("", encoding="utf-8")
        return
    with STABLE_TRACE.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def check_rows(rows: list[dict[str, str]]) -> tuple[list[str], list[str]]:
    failures: list[str] = []
    lines: list[str] = [
        "# DPLL Core Sine-Lock RTL Trace",
        "",
        "Generated by `python verification\\fixed_point\\check_dpll_core_sine_lock_trace.py`.",
        "",
    ]

    if len(rows) < 32:
        failures.append(f"expected at least 32 tracking rows, got {len(rows)}")
        return failures, lines

    input_hz = parse_float(rows[0]["input_hz"])
    center_hz = parse_float(rows[0]["center_hz"])
    center_word = parse_int(rows[0]["center_word"])
    expected_center = freq_word_from_hz(center_hz)
    expected_input = freq_word_from_hz(input_hz)
    expected_delta = unsigned(expected_input - expected_center, 48)
    if center_word != expected_center:
        failures.append(f"center word 0x{center_word:012x} != golden 0x{expected_center:012x}")
    if input_hz <= center_hz:
        failures.append(f"test expects high-side input, got input={input_hz} center={center_hz}")

    nonzero_corrections = 0
    positive_tracking_delta = 0
    track_rows = 0
    locked_rows = 0
    signal_rows = 0
    distinct_tracking_words: set[int] = set()
    sample_counts: list[int] = []
    fll_valid_counts: list[int] = []
    magnitudes: list[int] = []

    for index, row in enumerate(rows):
        row_index = parse_int(row["index"])
        if row_index != index:
            failures.append(f"row {index}: trace index {row_index} is not monotonic")
        sample_counts.append(parse_int(row["sample_count"]))
        fll_valid_counts.append(parse_int(row["fll_valid_count"]))
        tracking_word = parse_int(row["tracking_word"])
        correction = parse_int(row["freq_correction"])
        loop_state = parse_int(row["loop_state"])
        locked = parse_int(row["locked"])
        signal_present = parse_int(row["signal_present"])
        magnitude = parse_int(row["magnitude"])
        magnitudes.append(magnitude)
        distinct_tracking_words.add(tracking_word)
        if correction != 0:
            nonzero_corrections += 1
        if tracking_word > center_word:
            positive_tracking_delta += 1
        if loop_state == 6:
            track_rows += 1
        if locked:
            locked_rows += 1
        if signal_present:
            signal_rows += 1

    last_quarter = rows[(len(rows) * 3) // 4 :]
    last_locked = sum(1 for row in last_quarter if parse_int(row["locked"]))
    last_track = sum(1 for row in last_quarter if parse_int(row["loop_state"]) == 6)
    last_positive = sum(1 for row in last_quarter if parse_int(row["tracking_word"]) > center_word)
    last_nonzero = sum(1 for row in last_quarter if parse_int(row["freq_correction"]) != 0)

    if nonzero_corrections < 16:
        failures.append(f"nonzero corrections {nonzero_corrections} < 16")
    if positive_tracking_delta < 8:
        failures.append(f"tracking word above center rows {positive_tracking_delta} < 8")
    if len(distinct_tracking_words) < 8:
        failures.append(f"distinct tracking words {len(distinct_tracking_words)} < 8")
    if track_rows < 16:
        failures.append(f"TRACK rows {track_rows} < 16")
    if locked_rows < 16:
        failures.append(f"locked rows {locked_rows} < 16")
    if signal_rows < 16:
        failures.append(f"signal-present rows {signal_rows} < 16")
    final_fll_valid_count = fll_valid_counts[-1] if fll_valid_counts else 0
    if final_fll_valid_count < 32:
        failures.append(f"cumulative FLL valid count {final_fll_valid_count} < 32")
    if max(magnitudes) <= 0:
        failures.append("magnitude never became positive")
    if last_locked == 0 or last_track == 0:
        failures.append("last-quarter trace did not retain any TRACK/locked samples")
    if last_positive == 0 or last_nonzero == 0:
        failures.append("last-quarter trace did not retain nonzero high-side tracking response")
    if any(b <= a for a, b in zip(sample_counts, sample_counts[1:])):
        failures.append("sample_count is not strictly increasing across tracking rows")
    if any(b < a for a, b in zip(fll_valid_counts, fll_valid_counts[1:])):
        failures.append("fll_valid_count decreased across tracking rows")

    final_word = parse_int(rows[-1]["tracking_word"])
    final_delta = final_word - center_word
    lines.extend([
        f"Input sine: `{input_hz:.3f} Hz` at an equivalent 3.125 MSPS sample cadence.",
        f"Center word: `0x{center_word:012x}` (`{center_hz:.3f} Hz`).",
        f"Input golden word: `0x{expected_input:012x}`; high-side delta is about `0x{expected_delta:012x}`.",
        "",
        "| Metric | Value |",
        "|---|---:|",
        f"| rows | {len(rows)} |",
        f"| nonzero corrections | {nonzero_corrections} |",
        f"| distinct tracking words | {len(distinct_tracking_words)} |",
        f"| tracking word above center rows | {positive_tracking_delta} |",
        f"| TRACK rows | {track_rows} |",
        f"| locked rows | {locked_rows} |",
        f"| signal-present rows | {signal_rows} |",
        f"| cumulative FLL-valid measurements | {final_fll_valid_count} |",
        f"| max magnitude | {max(magnitudes)} |",
        f"| final tracking delta from center | {final_delta} |",
        "",
        "Scope:",
        "- This is an RTL/IP-aware sine-input closed-loop smoke trace, not a full tuned control-theory sign-off model.",
        "- It proves the real DDS/mixer/CIC/CORDIC/FLL/hybrid path observes valid FLL measurements, responds with nonzero tracking corrections for a high-side sine input, and reaches TRACK/locked samples.",
    ])
    return failures, lines


def main() -> int:
    trace = (ROOT / sys.argv[1]).resolve() if len(sys.argv) > 1 else latest_trace()
    rows = load_rows(trace)
    write_stable_trace(rows)
    failures, lines = check_rows(rows)
    lines.insert(4, f"Stable trace: `{STABLE_TRACE.relative_to(ROOT)}`")
    lines.insert(5, f"Source run trace: `{trace.relative_to(ROOT)}`")
    lines.insert(6, "")
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"trace={trace}")
    print(f"report={REPORT}")
    if failures:
        print("FAIL:")
        for failure in failures:
            print(f"- {failure}")
        return 1
    print("PASS: DPLL core sine-lock trace")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
