#!/usr/bin/env python3
from __future__ import annotations

import csv
import sys
from pathlib import Path

from dpll_fixed import freq_hz_from_word, freq_word_from_hz, unsigned


ROOT = Path(__file__).resolve().parents[2]
EXPECTED_HZ = [5_000, 10_000, 20_000, 50_000, 100_000, 150_000, 200_000]
REPORT = ROOT / "reports" / "multifrequency_golden_trace_20260628.md"
STABLE_TRACE = ROOT / "reports" / "multifrequency_golden_trace_20260628.csv"


def parse_int(value: str) -> int:
    return int(value, 0)


def latest_trace() -> Path:
    traces = sorted(
        ROOT.glob("reports/xsim/dpll_multifrequency_path_*/dpll_multifrequency_path_trace.csv"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not traces:
        raise FileNotFoundError("no dpll_multifrequency_path_trace.csv found under reports/xsim")
    return traces[0]


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def write_stable_trace(rows: list[dict[str, str]]) -> None:
    if not rows:
        STABLE_TRACE.write_text("", encoding="utf-8")
        return
    with STABLE_TRACE.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def check_rows(rows: list[dict[str, str]]) -> tuple[list[str], list[str]]:
    failures: list[str] = []
    lines: list[str] = [
        "# Multifrequency RTL Golden Trace",
        "",
        "Generated by `python verification\\fixed_point\\check_multifrequency_trace.py`.",
        "",
        "| Case | Hz | RTL word | Golden word | Tracking word | IQ | FLL | Tracking | State | Locked | Result |",
        "|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ]

    if len(rows) != len(EXPECTED_HZ):
        failures.append(f"expected {len(EXPECTED_HZ)} rows, got {len(rows)}")

    for expected_index, expected_hz in enumerate(EXPECTED_HZ):
        if expected_index >= len(rows):
            continue
        row = rows[expected_index]
        case_index = parse_int(row["case_index"])
        word = parse_int(row["word"])
        golden_word = freq_word_from_hz(float(expected_hz))
        tracking_word = parse_int(row["tracking_word"])
        iq_seen = parse_int(row["iq_seen"])
        freq_seen = parse_int(row["freq_seen"])
        tracking_seen = parse_int(row["tracking_seen"])
        loop_state = parse_int(row["loop_state"])
        locked = parse_int(row["locked"])
        phase_locked = parse_int(row["phase_locked"])
        frequency_locked = parse_int(row["frequency_locked"])
        signal_present = parse_int(row["signal_present"])
        active_r = parse_int(row["active_cic_rate_r"])
        active_shift = parse_int(row["active_cic_output_shift"])
        cic_illegal = parse_int(row["cic_illegal_config_seen"])
        cic_overflow = parse_int(row["cic_overflow_seen"])

        case_failures = []
        if case_index != expected_index:
            case_failures.append(f"case index {case_index} != {expected_index}")
        if word != golden_word:
            case_failures.append(f"word {word:#014x} != golden {golden_word:#014x}")
        if tracking_word != unsigned(golden_word, 48):
            case_failures.append(f"tracking {tracking_word:#014x} != zero-gain center {golden_word:#014x}")
        if iq_seen < 16:
            case_failures.append(f"iq_seen {iq_seen} < 16")
        if freq_seen < 8:
            case_failures.append(f"freq_seen {freq_seen} < 8")
        if tracking_seen < 4:
            case_failures.append(f"tracking_seen {tracking_seen} < 4")
        if loop_state != 6:
            case_failures.append(f"loop_state {loop_state} != TRACK(6)")
        if not (signal_present and phase_locked and frequency_locked and locked):
            case_failures.append("lock flags are not all asserted")
        if active_r != 8 or active_shift != 4:
            case_failures.append(f"CIC active config R={active_r} shift={active_shift}, expected 8/4")
        if cic_illegal or cic_overflow:
            case_failures.append(f"CIC fault illegal={cic_illegal} overflow={cic_overflow}")

        result = "PASS" if not case_failures else "; ".join(case_failures)
        if case_failures:
            failures.extend(f"case {expected_index}: {item}" for item in case_failures)
        lines.append(
            f"| {expected_index} | {expected_hz} | `0x{word:012x}` | `0x{golden_word:012x}` | "
            f"`0x{tracking_word:012x}` | {iq_seen} | {freq_seen} | {tracking_seen} | "
            f"{loop_state} | {locked} | {result} |"
        )

        roundtrip_hz = freq_hz_from_word(word)
        if abs(roundtrip_hz - expected_hz) > 1e-3:
            failures.append(f"case {expected_index}: roundtrip Hz {roundtrip_hz} != {expected_hz}")

    lines.extend([
        "",
        "Model assumptions:",
        "- Frequency words use the frozen 48-bit, 125 MHz v1 mapping.",
        "- The RTL test drives zero loop gains, so the expected tracking word is the applied center word.",
        "- This checker validates the current 5/10/20/50/100/150/200 kHz RTL trace; it is not a replacement for a tuned nonzero-gain closed-loop control model.",
    ])
    return failures, lines


def main() -> int:
    trace = (ROOT / sys.argv[1]).resolve() if len(sys.argv) > 1 else latest_trace()
    rows = load_rows(trace)
    write_stable_trace(rows)
    failures, lines = check_rows(rows)
    lines.insert(4, f"Stable trace: `{STABLE_TRACE.relative_to(ROOT)}`")
    lines.insert(5, f"Source run trace: `{trace.relative_to(ROOT)}`")
    lines.insert(6, "")
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"trace={trace}")
    print(f"report={REPORT}")
    if failures:
        print("FAIL:")
        for failure in failures:
            print(f"- {failure}")
        return 1
    print("PASS: multifrequency golden trace")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
