#!/usr/bin/env python3
from __future__ import annotations

import csv
import sys
from pathlib import Path

from dpll_fixed import mask, saturate_signed


ROOT = Path(__file__).resolve().parents[2]
REPORT = ROOT / "reports" / "hybrid_loop_golden_trace_20260628.md"
STABLE_TRACE = ROOT / "reports" / "hybrid_loop_golden_trace_20260628.csv"
STATE_WIDTH = 56
WORD_WIDTH = 48
PRODUCT_SHIFT = 18


def parse_int(value: str) -> int:
    return int(value, 0)


def latest_trace() -> Path:
    traces = sorted(
        ROOT.glob("reports/xsim/hybrid_loop_stage_a_cli_*/hybrid_fll_pll_filter_trace.csv"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not traces:
        raise FileNotFoundError("no hybrid_fll_pll_filter_trace.csv found under reports/xsim")
    return traces[0]


def load_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def write_stable_trace(rows: list[dict[str, str]]) -> None:
    if not rows:
        STABLE_TRACE.write_text("", encoding="utf-8")
        return
    with STABLE_TRACE.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def sat_word(value: int) -> int:
    if value < 0:
        return 0
    return min(value, mask(WORD_WIDTH))


def model_rows(rows: list[dict[str, str]]) -> tuple[list[str], list[str]]:
    failures: list[str] = []
    lines: list[str] = [
        "# Hybrid Loop Fixed/RTL Golden Trace",
        "",
        "Generated by `python verification\\fixed_point\\check_hybrid_loop_trace.py`.",
        "",
        "| Case | FLL/I/P | Phase | Freq | Expected State | RTL State | Expected Correction | RTL Correction | Expected Tracking | RTL Tracking | Result |",
        "|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---|",
    ]
    state = 0

    for expected_index, row in enumerate(rows):
        case_index = parse_int(row["case_index"])
        enable_fll = parse_int(row["enable_fll"])
        enable_i = parse_int(row["enable_pll_i"])
        enable_p = parse_int(row["enable_pll_p"])
        phase = parse_int(row["phase_error"])
        freq = parse_int(row["freq_error"])
        kf = parse_int(row["kf"])
        ki = parse_int(row["ki"])
        kp = parse_int(row["kp"])
        center = parse_int(row["center_word"])
        positive_limit = parse_int(row["positive_limit"])
        negative_limit = parse_int(row["negative_limit"])

        fll_term = (freq * kf) >> PRODUCT_SHIFT if enable_fll else 0
        i_term = (phase * ki) >> PRODUCT_SHIFT if enable_i else 0
        p_term = (phase * kp) >> PRODUCT_SHIFT if enable_p else 0
        delta = fll_term + i_term
        state_sum = state + delta
        push_high = state >= positive_limit and delta > 0
        push_low = state <= negative_limit and delta < 0
        allow_update = not (push_high or push_low)
        expected_state = saturate_signed(state_sum, STATE_WIDTH)
        expected_state = min(expected_state, positive_limit)
        expected_state = max(expected_state, negative_limit)
        if not allow_update:
            expected_state = state
        expected_correction = min(max(expected_state + p_term, negative_limit), positive_limit)
        expected_tracking = sat_word(center + expected_correction)
        expected_sat_high = int(state_sum > positive_limit or expected_state + p_term > positive_limit)
        expected_sat_low = int(state_sum < negative_limit or expected_state + p_term < negative_limit)

        rtl_state = parse_int(row["freq_state"])
        rtl_correction = parse_int(row["freq_correction"])
        rtl_tracking = parse_int(row["tracking_word"])
        rtl_sat_high = parse_int(row["saturated_high"])
        rtl_sat_low = parse_int(row["saturated_low"])

        case_failures = []
        if case_index != expected_index:
            case_failures.append(f"case index {case_index} != {expected_index}")
        if rtl_state != expected_state:
            case_failures.append(f"state {rtl_state} != {expected_state}")
        if rtl_correction != expected_correction:
            case_failures.append(f"correction {rtl_correction} != {expected_correction}")
        if rtl_tracking != expected_tracking:
            case_failures.append(f"tracking {rtl_tracking} != {expected_tracking}")
        if rtl_sat_high != expected_sat_high:
            case_failures.append(f"sat_high {rtl_sat_high} != {expected_sat_high}")
        if rtl_sat_low != expected_sat_low:
            case_failures.append(f"sat_low {rtl_sat_low} != {expected_sat_low}")

        result = "PASS" if not case_failures else "; ".join(case_failures)
        if case_failures:
            failures.extend(f"case {expected_index}: {item}" for item in case_failures)
        lines.append(
            f"| {expected_index} | {enable_fll}/{enable_i}/{enable_p} | {phase} | {freq} | "
            f"{expected_state} | {rtl_state} | {expected_correction} | {rtl_correction} | "
            f"{expected_tracking} | {rtl_tracking} | {result} |"
        )
        state = expected_state

    lines.extend([
        "",
        "Model assumptions:",
        "- Products use signed arithmetic right shift by 18 bits, matching `PRODUCT_SHIFT`.",
        "- Anti-windup blocks only when the current state is already at a limit and the next state delta pushes farther into that limit.",
        "- The checker validates the hybrid FLL/PI/P fixed-point loop block, not the full CORDIC/DDS/CIC signal chain.",
    ])
    return failures, lines


def main() -> int:
    trace = (ROOT / sys.argv[1]).resolve() if len(sys.argv) > 1 else latest_trace()
    rows = load_rows(trace)
    write_stable_trace(rows)
    failures, lines = model_rows(rows)
    lines.insert(4, f"Stable trace: `{STABLE_TRACE.relative_to(ROOT)}`")
    lines.insert(5, f"Source run trace: `{trace.relative_to(ROOT)}`")
    lines.insert(6, "")
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"trace={trace}")
    print(f"report={REPORT}")
    if failures:
        print("FAIL:")
        for failure in failures:
            print(f"- {failure}")
        return 1
    print("PASS: hybrid loop golden trace")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
