#!/usr/bin/env python3
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DPLL = ROOT / "DPLL_Rewrite.srcs" / "sources_1" / "DigitalPLL"
SRC = ROOT / "DPLL_Rewrite.srcs" / "sources_1"
REPORT = ROOT / "reports" / "review2_closure_audit_20260628.md"


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def check(condition: bool, label: str, evidence: str) -> tuple[str, bool]:
    status = "PASS" if condition else "FAIL"
    print(f"{status}: {label}")
    return f"| {status} | {label} | {evidence} |", condition


def main() -> int:
    core = read(DPLL / "core" / "dpll_single_clock_core_stage_a.v")
    dc = read(DPLL / "frontend" / "dc_blocker_valid_stage_a.v")
    fll = read(DPLL / "detector_fll" / "fll_phase_difference_stage_a.v")
    loop = read(DPLL / "hybrid_loop" / "loop_state_manager_stage_a.v")
    cic = read(DPLL / "iq_cic" / "post_iq_cic_stage_a.v")
    dds_xci = read(SRC / "Freq_Meter" / "DDC" / "ip" / "LO_DDS_H" / "LO_DDS_H.xci")
    input_mult_sim = read(DPLL / "DDC" / "ip" / "input_multiplier" / "sim" / "input_multiplier.vhd")

    checks: list[tuple[str, bool]] = []
    checks.append(check(
        "sample_out <= saturate_to_data(next_shifted_hp);" in dc
        and "out_valid <= 1'b1;" in dc
        and "if (out_valid)" not in dc,
        "DC blocker output data and valid update in the same input-valid cycle",
        "`sample_out` uses `next_hp_value` under `in_valid`",
    ))
    checks.append(check(
        "mixer_input_valid_r0 <= dc_valid && dds_valid;" in core
        and "if (dc_valid && dds_valid)" in core,
        "Mixer samples ADC and LO only when both DC blocker and DDS outputs are valid",
        "core gates mixer input with `dc_valid && dds_valid`",
    ))
    checks.append(check(
        "C_LATENCY => 1" in input_mult_sim
        and "mixer_product_valid <= mixer_input_valid_r1;" in core
        and "assign mixer_valid = mixer_product_valid;" in core,
        "Mixer valid is delayed for the configured one-cycle multiplier IP latency",
        "`input_multiplier` latency is 1 and core has a product-valid stage",
    ))
    checks.append(check(
        "(mixer_i_product[31] ? -32'sd16384 : 32'sd16384)" in core
        and "(mixer_q_product[31] ? -32'sd16384 : 32'sd16384)" in core,
        "Mixer rounding is sign-symmetric",
        "positive and negative products use opposite rounding bias",
    ))
    checks.append(check(
        ".measurement_timeout(holdover_timeout)" in core
        and "measurement_gap_count" in loop
        and "LOSS_TIMEOUT" in loop,
        "State manager has a no-measurement watchdog",
        "`measurement_gap_count` sends acquire/blend/track/reacquire to holdover on timeout",
    ))
    checks.append(check(
        ".measurement_valid(state_measurement_valid_r)" in core
        and "state_measurement_valid_r <= freq_error_valid_d;" in core,
        "State manager decisions are driven by valid FLL error samples",
        "core presents state measurements only after delayed `freq_error_valid`",
    ))
    checks.append(check(
        "input  wire                              clear" in fll
        and "if (rst_125m || clear)" in fll
        and ".clear(config_apply | (cordic_valid && !cordic_signal_usable))" in core,
        "FLL history clears on APPLY or unusable low-magnitude CORDIC samples",
        "FLL has explicit clear and core gates phase history by magnitude",
    ))
    checks.append(check(
        "illegal_config_seen <= 1'b0;" in cic
        and "config_apply && apply_is_legal" in cic,
        "Legal post-IQ CIC APPLY clears previous illegal-config fault",
        "sticky fault no longer permanently blocks recovery after a legal APPLY",
    ))
    checks.append(check(
        "tracking_phase_accumulator_stage_a" not in core
        and "PARAM_VALUE.Phase_Increment\">Streaming" in dds_xci
        and "LO_DDS_H tracking_lo_dds_inst" in core,
        "Active IQ LO uses DDS Streaming PINC without a redundant local phase accumulator",
        "`LO_DDS_H` is configured for streaming phase increment",
    ))
    checks.append(check(
        ".ambiguous(fll_ambiguous)" in core
        and "assign freq_error_usable = freq_error_valid && !fll_ambiguous;" in core
        and "hybrid_error_valid_r <= freq_error_usable;" in core
        and "state_measurement_valid_r <= freq_error_valid_d;" in core,
        "Ambiguous FLL measurements are blocked before state and hybrid-loop updates",
        "`fll_ambiguous` masks `freq_error_valid` through `freq_error_usable`",
    ))

    lines = [
        "# Review2 Closure Audit",
        "",
        "Generated by `python scripts\\audit_review2_closure.py`.",
        "",
        "| Status | Requirement | Evidence |",
        "|---|---|---|",
    ]
    lines.extend(line for line, _ in checks)
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    failed = [line for line, ok in checks if not ok]
    print(f"report={REPORT}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
