#!/usr/bin/env python3
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "DPLL_Rewrite.srcs" / "sources_1"
REPORT = ROOT / "reports" / "review2_ip_config_audit_20260628.md"


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def xml_value(text: str, ref: str) -> str | None:
    pattern = rf'referenceId="{re.escape(ref)}">([^<]+)<'
    m = re.search(pattern, text)
    return m.group(1) if m else None


def check(condition: bool, label: str, evidence: str) -> tuple[str, bool]:
    status = "PASS" if condition else "FAIL"
    print(f"{status}: {label}")
    return f"| {status} | {label} | {evidence} |", condition


def main() -> int:
    lo_xci = read(SRC / "Freq_Meter" / "DDC" / "ip" / "LO_DDS_H" / "LO_DDS_H.xci")
    cic_xci = read(SRC / "DigitalPLL" / "DDC" / "ip" / "pre_iq_cic_40_125m_v1" / "pre_iq_cic_40_125m_v1" / "pre_iq_cic_40_125m_v1.xci")
    wrapper = read(SRC / "DigitalPLL" / "dpll_wrapper.v")
    div_xci = read(SRC / "DigitalPLL" / "VCO" / "div_gen_pll_u" / "div_gen_pll_u" / "div_gen_pll_u.xci")
    manifest_path = ROOT / "reports" / "review2_ip_config_regen" / "manifest.txt"
    manifest = read(manifest_path) if manifest_path.exists() else ""

    lo_clock = xml_value(lo_xci, "PARAM_VALUE.DDS_Clock_Rate")
    lo_phase_increment = xml_value(lo_xci, "PARAM_VALUE.Phase_Increment")
    lo_phase_width = xml_value(lo_xci, "PARAM_VALUE.Phase_Width")
    lo_output = xml_value(lo_xci, "PARAM_VALUE.Output_Selection")

    cic_clock = xml_value(cic_xci, "PARAM_VALUE.Clock_Frequency")
    cic_input_sample_frequency = xml_value(cic_xci, "PARAM_VALUE.Input_Sample_Frequency")
    cic_rate = xml_value(cic_xci, "PARAM_VALUE.Fixed_Or_Initial_Rate")
    cic_stages = xml_value(cic_xci, "PARAM_VALUE.Number_Of_Stages")
    cic_diff_delay = xml_value(cic_xci, "PARAM_VALUE.Differential_Delay")
    cic_has_out_ready = xml_value(cic_xci, "PARAM_VALUE.HAS_DOUT_TREADY")

    div_algorithm = xml_value(div_xci, "PARAM_VALUE.algorithm_type")
    div_sign = xml_value(div_xci, "PARAM_VALUE.operand_sign")
    div_model_sign = xml_value(div_xci, "MODELPARAM_VALUE.SIGNED_B")
    div_latency = xml_value(div_xci, "PARAM_VALUE.latency")
    div_flow = xml_value(div_xci, "PARAM_VALUE.FlowControl")

    checks: list[tuple[str, bool]] = []
    checks.append(check(
        lo_clock == "125" and lo_phase_increment == "Streaming" and lo_phase_width == "48" and lo_output == "Sine_and_Cosine",
        "LO_DDS_H regenerated for the active 125 MHz single-clock DPLL path",
        f"`DDS_Clock_Rate={lo_clock}`, `Phase_Increment={lo_phase_increment}`, `Phase_Width={lo_phase_width}`, `Output_Selection={lo_output}`",
    ))
    checks.append(check(
        cic_rate == "40" and cic_stages == "4" and cic_diff_delay == "2" and cic_has_out_ready == "false",
        "pre-IQ CIC functional parameters remain fixed /40 non-blocking decimation",
        f"`R={cic_rate}`, `N={cic_stages}`, `M={cic_diff_delay}`, `HAS_DOUT_TREADY={cic_has_out_ready}`",
    ))
    checks.append(check(
        cic_clock == "125.0" and cic_input_sample_frequency == "125.0",
        "pre-IQ CIC clock metadata is regenerated for 125 MHz",
        f"`Clock_Frequency={cic_clock}`, `Input_Sample_Frequency={cic_input_sample_frequency}`",
    ))
    checks.append(check(
        "pre_iq_cic_40_125m_v1 pre_iq_cic_40_inst" in wrapper,
        "active wrapper uses the regenerated pre-IQ CIC replacement",
        "`dpll_wrapper.v` instantiates `pre_iq_cic_40_125m_v1` for `pre_iq_cic_40_inst`",
    ))
    checks.append(check(
        div_algorithm == "Radix2" and div_sign == "Unsigned" and div_model_sign == "0",
        "VCO divider IP is replaced with an unsigned Vivado 2018.3 instance",
        f"`algorithm_type={div_algorithm}`, `operand_sign={div_sign}`, `SIGNED_B={div_model_sign}`",
    ))
    checks.append(check(
        div_latency == "32" and div_flow == "NonBlocking",
        "VCO divider latency and flow control remain explicitly managed",
        f"`latency={div_latency}`, `FlowControl={div_flow}`",
    ))
    checks.append(check(
        "note.cic.Clock_Frequency disabled" in manifest and "note.div.operand_sign disabled" in manifest,
        "Vivado 2018.3 IP regeneration limitations are recorded",
        "`reports/review2_ip_config_regen/manifest.txt` records why replacement IPs were required for disabled existing-instance parameters",
    ))

    lines = [
        "# Review2 IP Configuration Audit",
        "",
        "Generated by `python scripts\\audit_review2_ip_config.py`.",
        "",
        "| Status | Requirement | Evidence |",
        "|---|---|---|",
    ]
    lines.extend(line for line, _ in checks)
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    failed = [line for line, ok in checks if not ok]
    print(f"report={REPORT}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
