from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCAN_ROOT = ROOT / "DPLL_Rewrite.srcs" / "sources_1" / "DigitalPLL"
OUT_PATH = ROOT / "reports" / "clk_dpll_migration_audit.md"


@dataclass
class Hit:
    path: Path
    line_no: int
    text: str
    context: str = ""


def classify(hit: Hit) -> str:
    rel = hit.path.as_posix()
    text = hit.text
    if rel.endswith("dpll_wrapper.v.bk"):
        return "backup-ignore"
    if rel.endswith("dpll_wrapper.v") and "input" in text:
        return "stage-a-wrapper-boundary"
    if "DDC_wideband_filters.vhd" in rel:
        return "frontend-nco-mixer-owner"
    if "DDC0_inst" in hit.context:
        return "frontend-nco-mixer-owner"
    if "PLL_VCO_MUL_DIV.v" in rel:
        return "register-dac-owner"
    if "VCO0_mul_div" in hit.context:
        return "register-dac-owner"
    if "PLL_loop_filters" in text or "output_summing" in text:
        return "hybrid-loop-owner"
    if "residuals_monitor" in text or "Status_" in text or "PLL_output_average" in text:
        return "register-dac-owner"
    if ".clk(clk_dpll)" in text and "dpll_wrapper.v" in rel:
        return "register-dac-owner"
    if "always @(posedge clk_dpll)" in text or "rising_edge(clk_dpll)" in text:
        return "clock-valid-owner"
    return "needs-owner-triage"


def iter_hits() -> list[Hit]:
    hits: list[Hit] = []
    for path in sorted(SCAN_ROOT.rglob("*")):
        if not path.is_file():
            continue
        if path.suffix.lower() not in {".v", ".vh", ".sv", ".vhd", ".vhdl"}:
            continue
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except UnicodeDecodeError:
            lines = path.read_text(encoding="mbcs").splitlines()
        for line_no, line in enumerate(lines, 1):
            if "clk_dpll" in line:
                context_start = max(0, line_no - 12)
                context = "\n".join(lines[context_start:line_no])
                hits.append(Hit(path.relative_to(ROOT), line_no, line.strip(), context))
    return hits


def main() -> int:
    hits = iter_hits()
    active_hits = [hit for hit in hits if classify(hit) != "backup-ignore"]
    by_class: dict[str, list[Hit]] = {}
    for hit in hits:
        by_class.setdefault(classify(hit), []).append(hit)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUT_PATH.open("w", encoding="utf-8", newline="\n") as f:
        f.write("# clk_dpll Migration Audit\n\n")
        f.write("Generated by `scripts/audit_clk_dpll_usage.py`.\n\n")
        f.write(f"Active hits excluding `.bk`: {len(active_hits)}\n\n")
        f.write("## Summary By Owner\n\n")
        f.write("| Owner bucket | Hits |\n")
        f.write("|---|---:|\n")
        for owner in sorted(by_class):
            f.write(f"| `{owner}` | {len(by_class[owner])} |\n")
        f.write("\n## Active Hits\n\n")
        for hit in active_hits:
            owner = classify(hit)
            f.write(f"- `{owner}` `{hit.path.as_posix()}:{hit.line_no}`: `{hit.text}`\n")
        if "backup-ignore" in by_class:
            f.write("\n## Ignored Backup Hits\n\n")
            for hit in by_class["backup-ignore"]:
                f.write(f"- `{hit.path.as_posix()}:{hit.line_no}`: `{hit.text}`\n")

    print(f"active_clk_dpll_hits={len(active_hits)}")
    print(f"report={OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
