#!/usr/bin/env python3
"""Audit the post-IQ CIC R/output-shift contract.

The RTL intentionally does not fully divide out the R^3 gain of the
third-order CIC.  Instead, the recommended table keeps 5 to 6 bits of gain
relative to full CIC compensation, and the APPLY validator allows a bounded
range around that recommendation.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "reports" / "cic_shift_model_20260630.md"


@dataclass(frozen=True)
class CicShiftRow:
    rate_r: int
    recommended_shift: int


ROWS = (
    CicShiftRow(8, 4),
    CicShiftRow(16, 7),
    CicShiftRow(31, 10),
    CicShiftRow(78, 13),
    CicShiftRow(156, 16),
    CicShiftRow(312, 19),
)


def ceil_log2(value: int) -> int:
    if value <= 0:
        raise ValueError("ceil_log2 requires a positive integer")
    return (value - 1).bit_length()


def render_report() -> str:
    lines = [
        "# Post-IQ CIC Shift Model Audit",
        "",
        "Generated by `python scripts/audit_cic_shift_model.py`.",
        "",
        "## Model",
        "",
        "- The post-IQ CIC is a third-order, M=1 decimator, so the worst-case CIC gain is `R^3`.",
        "- Full gain compensation would use `ceil(log2(R^3))` output shift bits.",
        "- The implemented recommendation intentionally keeps 5 to 6 bits of CIC gain relative to full compensation.",
        "- The APPLY validator accepts `recommended_shift - 1` through `recommended_shift + 3`.",
        "- This is a bounded configuration contract, not a proof that arbitrary full-scale ADC input cannot saturate.",
        "- Runtime saturation remains observable through `overflow_seen` / `DPLL_CORE_FLAGS[0]`.",
        "",
        "## Standard Rate Table",
        "",
        "| R | full gain shift `ceil(log2(R^3))` | recommended shift | retained gain bits | legal shift range |",
        "|---:|---:|---:|---:|---:|",
    ]
    for row in ROWS:
        full_gain_shift = ceil_log2(row.rate_r ** 3)
        retained_gain_bits = full_gain_shift - row.recommended_shift
        legal_min = row.recommended_shift - 1
        legal_max = row.recommended_shift + 3
        lines.append(
            f"| {row.rate_r} | {full_gain_shift} | {row.recommended_shift} | "
            f"{retained_gain_bits} | {legal_min}..{legal_max} |"
        )
    lines.extend(
        [
            "",
            "## Audit Result",
            "",
            "PASS: the implemented table preserves 5 to 6 retained gain bits for all standard R values,",
            "and every validator range stays inside the 6-bit shift field.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    failures: list[str] = []
    for row in ROWS:
        full_gain_shift = ceil_log2(row.rate_r ** 3)
        retained_gain_bits = full_gain_shift - row.recommended_shift
        legal_min = row.recommended_shift - 1
        legal_max = row.recommended_shift + 3
        if not 5 <= retained_gain_bits <= 6:
            failures.append(
                f"R={row.rate_r}: retained gain bits {retained_gain_bits} outside 5..6"
            )
        if legal_min < 0 or legal_max > 63:
            failures.append(
                f"R={row.rate_r}: legal range {legal_min}..{legal_max} outside 6-bit shift field"
            )
        if not legal_min <= row.recommended_shift <= legal_max:
            failures.append(f"R={row.rate_r}: recommendation excluded by legal range")

    REPORT.write_text(render_report(), encoding="utf-8", newline="\n")

    if failures:
        for failure in failures:
            print(f"FAIL: {failure}")
        print(f"report={REPORT}")
        return 1

    print(f"PASS: post-IQ CIC shift model rows={len(ROWS)} report={REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
