#!/usr/bin/env python3
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "DPLL_Rewrite.srcs" / "sources_1"
DPLL = SRC / "DigitalPLL"
SDK = ROOT / "DPLL_Rewrite.sdk" / "DPLL_2COM" / "src"
REPORT = ROOT / "reports" / "review_closure_audit_20260628.md"


def read(path: Path, encoding: str = "utf-8") -> str:
    try:
        return path.read_text(encoding=encoding, errors="strict")
    except UnicodeDecodeError:
        return path.read_text(encoding="gbk", errors="strict")


def read_gbk(path: Path) -> str:
    return path.read_text(encoding="gbk", errors="strict")


def pass_if(condition: bool, label: str, detail: str = "") -> tuple[str, bool]:
    status = "PASS" if condition else "FAIL"
    line = f"| {status} | {label} | {detail} |"
    print(f"{status}: {label}")
    return line, condition


def no_uncommented_false_path() -> tuple[str, bool]:
    active = []
    for path in (SRC / "xdc").rglob("*.xdc"):
        for line_no, line in enumerate(read(path).splitlines(), 1):
            stripped = line.strip()
            if "set_false_path" in stripped and not stripped.startswith("#"):
                active.append(f"{path.relative_to(ROOT).as_posix()}:{line_no}")
    return pass_if(not active, "No active false-path constraints hide timing", ", ".join(active) if active else "only commented/library CDC constraints found")


def no_active_clk_dpll() -> tuple[str, bool]:
    hits = []
    for path in DPLL.rglob("*"):
        if path.suffix.lower() not in {".v", ".vh", ".sv", ".vhd", ".vhdl"}:
            continue
        text = read(path)
        if "clk_dpll" in text:
            hits.append(path.relative_to(ROOT).as_posix())
    return pass_if(not hits, "No clk_dpll text remains in active DigitalPLL sources", ", ".join(hits) if hits else "0 hits")


def no_retired_stage_a_stubs() -> tuple[str, bool]:
    retired = [
        "DPLL_Rewrite.srcs/sources_1/DigitalPLL/clocking/dpll_clock_valid_stage_a.v",
        "DPLL_Rewrite.srcs/sources_1/DigitalPLL/frontend/tracking_phase_accumulator_stage_a.v",
        "verification/rtl/dpll_clock_valid_stage_a_tb.v",
        "verification/rtl/tracking_phase_accumulator_stage_a_tb.v",
        "scripts/run_clock_valid_stage_a_xsim.ps1",
        "scripts/run_clock_valid_stage_a_xsim.tcl",
        "scripts/vivado_stage_a_synth_check.tcl",
        "scripts/vivado_stage_a_project_frontend_check.tcl",
    ]
    tracked = set(subprocess.run(["git", "ls-files"], cwd=ROOT, check=True, text=True, stdout=subprocess.PIPE).stdout.splitlines())
    hits = [path for path in retired if path in tracked]
    return pass_if(not hits, "Retired local NCO and 3.125MHz clock-valid stubs are not tracked", ", ".join(hits) if hits else "0 hits")


def main() -> int:
    wrapper = read(DPLL / "dpll_wrapper.v")
    core = read(DPLL / "DDC" / "dpll_single_clock_core_stage_a.v")
    cic = read(DPLL / "DDC" / "post_iq_cic_stage_a.v")
    vco = read(DPLL / "VCO" / "PLL_VCO_MUL_DIV.v")
    dbg = read(DPLL / "debug" / "debug_dac_formatter_stage_a.v")
    fll = read(DPLL / "hybrid_loop" / "fll_phase_difference_stage_a.v")
    loop = read(DPLL / "hybrid_loop" / "loop_state_manager_stage_a.v")
    lo_dds_h_xci = read(SRC / "Freq_Meter" / "DDC" / "ip" / "LO_DDS_H" / "LO_DDS_H.xci")
    arm_mock = read(ROOT / "verification" / "arm" / "test_dpll_control_mock.py")
    arm = read_gbk(SDK / "helloworld.c")
    periph = read_gbk(SDK / "Peripherals.h")

    lines: list[str] = [
        "# Review Closure Audit",
        "",
        "Generated by `python scripts\\audit_review_closure.py`.",
        "",
        "| Status | Requirement | Evidence |",
        "|---|---|---|",
    ]

    checks: list[tuple[str, bool]] = []
    checks.append(pass_if("DigitalPLL2" not in "\n".join(p.name for p in DPLL.rglob("*")), "No DigitalPLL2 artifact exists", "file-name scan under active DigitalPLL tree"))
    checks.append(no_active_clk_dpll())
    checks.append(no_retired_stage_a_stubs())
    pre_iq_cic_vhd = read(DPLL / "DDC" / "ip" / "pre_iq_cic_40_125m_v1" / "pre_iq_cic_40_125m_v1" / "synth" / "pre_iq_cic_40_125m_v1.vhd")
    checks.append(pass_if("pre_iq_cic_40_125m_v1 pre_iq_cic_40_inst" in wrapper and ".m_axis_data_tvalid(pre_cic_valid)" in wrapper, "Pre-IQ /40 path uses Xilinx CIC valid", "`pre_iq_cic_40_125m_v1` drives `pre_cic_valid`"))
    checks.append(pass_if('C_RATE=40' in pre_iq_cic_vhd, "Pre-IQ CIC IP is configured for R=40", "Xilinx CIC Compiler metadata has `C_RATE=40`"))
    checks.append(pass_if(
        "LO_DDS_H tracking_lo_dds_inst" in core
        and "PARAM_VALUE.Phase_Increment\">Streaming" in lo_dds_h_xci
        and "tracking_phase_accumulator_stage_a" not in core,
        "Tracking NCO runs continuously in Xilinx DDS Streaming PINC mode",
        "`LO_DDS_H` phase generator consumes continuous tracking-word increments",
    ))
    checks.append(pass_if("LO_DDS_H tracking_lo_dds_inst" in core and "PARAM_VALUE.Output_Selection\">Sine_and_Cosine" in lo_dds_h_xci, "IQ LO uses Xilinx DDS sine/cosine IP", "`LO_DDS_H` DDS Compiler configured for sine and cosine"))
    checks.append(pass_if("dc_blocker_valid_stage_a" in core, "DC blocker is present before IQ mixer", "core instantiates `dc_blocker_valid_stage_a`"))
    angle_cordic_xci = read(DPLL / "DDC" / "ip" / "angle_CORDIC" / "angle_CORDIC.xci")
    checks.append(pass_if("angle_CORDIC phase_cordic_inst" in core and "PARAM_VALUE.Functional_Selection\">Translate" in angle_cordic_xci, "CORDIC phase/magnitude is in DPLL path", "`angle_CORDIC` IP configured for translate"))
    checks.append(pass_if("assign phase_error_next = cordic_phase_word - phase_setpoint;" in core, "Phase error comes from CORDIC phase", "not raw Q truncation"))
    checks.append(pass_if("delay_sel" in fll and "phase_delta" in fll and "PHASE_WIDTH" in fll, "FLL phase difference supports selectable wrapped delay", "`fll_phase_difference_stage_a` implements delay selection"))
    checks.append(pass_if(all(name in loop for name in ["FLL_ACQUIRE", "FLL_PLL_BLEND", "PLL_TRACK", "HOLDOVER", "REACQUIRE"]), "FLL/PLL state manager includes acquire/blend/track/holdover/reacquire", "`loop_state_manager_stage_a` state names present"))
    checks.append(pass_if("config_apply && apply_is_legal" in cic and "illegal_config_seen <= 1'b1" in cic, "Post-IQ CIC R/shift apply is atomic and rejects illegal config", "active config changes only on legal APPLY"))
    checks.append(pass_if("warmup_outputs_remaining <= WARMUP_OUTPUT_COUNT" in cic and "active_rounding_bias" in cic, "Post-IQ CIC warmup and symmetric rounding exist", "warmup counter and signed rounding bias present"))
    checks.append(pass_if("PLL_VCO_MUL_DIV_inst" in wrapper and "mult_gen_pll VCO0_Multiplier" in vco and "div_gen_pll_u VCO0_Divider" in vco, "Output MUL/DIV uses existing Xilinx IP", "`mult_gen_pll` and unsigned `div_gen_pll_u` instantiated"))
    checks.append(pass_if(all(s in vco for s in ["ST_MULT_WAIT", "ST_DIV_SEND", "ST_DIV_WAIT", "ST_DIV_OUT"]), "Output MUL/DIV uses explicit multi-cycle start/done sequencing", "state machine around multiplier/divider IP"))
    checks.append(pass_if("debug_dac_formatter_stage_a debug_dac_formatter_inst" in wrapper and ".dac_sample(DACout1)" in wrapper, "DACout1 is registered debug formatter output", "`DACout1` connected only through debug formatter instance"))
    checks.append(pass_if(
        "MODE_RAW_BIT_WINDOW" in dbg
        and "mode_r0 <= format_word[9:8]" in dbg
        and (
            "product_r2 <= shifted_signed_r1 * gain_r1" in dbg
            or "product_r3 <= shifted_signed_r2 * gain_r2" in dbg
        ),
        "DACout1 format register affects debug formatting",
        "raw-window and scaled modes implemented",
    ))
    checks.append(pass_if("DPLL_ABI_VERSION_Addr" in periph and "DPLL_FPGA_BUILD_ID_Addr" in periph, "ARM header exposes ABI/build registers", "v1 readback symbols present"))
    checks.append(pass_if("dpll_abi_ready = dpll_check_abi();" in arm and "action_status = (dpll_set_enable(1) == 0) ? STATUS_ACK : STATUS_NACK;" in arm, "ARM startup and STM control are ABI gated", "startup check plus command-result ACK/NACK"))
    checks.append(pass_if(
        "DPLL_CONFIG_APPLY_SEQ_MASK" in periph
        and "PC_ERR_DPLL_APPLY_TIMEOUT" in arm
        and "Xil_In32(DPLL_CONFIG_APPLY_Addr)" in arm
        and "pc_send_dpll_apply_result(dpll_apply_config());" in arm,
        "ARM APPLY waits for FPGA readback status",
        "`dpll_apply_config` polls `CONFIG_APPLY` sequence/busy before ACK",
    ))
    checks.append(pass_if(all(token in arm_mock for token in ["MockMmio", "parse_dpll_addr", "write_adv_config", "DPLL_CONFIG_APPLY_Addr"]), "ARM mock MMIO tests cover ABI/APPLY control", "`verification/arm/test_dpll_control_mock.py` parses real register definitions"))
    checks.append(pass_if("PID_GainI2_Addr" not in periph.replace("Freq_Meter_PID_GainI2_Addr", ""), "DPLL ARM aliases do not restore PII2", "remaining I2 name is frequency-meter only"))
    checks.append(pass_if("DAC1 is a debug output only" in periph and "DPLL_DEBUG_DAC_SOURCE_ADDR" in periph, "DAC1/DACout1 ABI is debug-only", "debug source selector uses DPLL debug DAC naming"))
    checks.append(no_uncommented_false_path())

    lines.extend(line for line, _ in checks)
    lines.extend([
        "",
        "## Excluded By User",
        "",
        "- Direct system bus `adc_clk -> pll_adc_clk` timing remains excluded from this closure audit.",
        "- Timing closure as a whole is not claimed by this audit.",
        "",
    ])

    REPORT.write_text("\n".join(lines), encoding="utf-8")
    failed = [line for line, ok in checks if not ok]
    if failed:
        print(f"report={REPORT}")
        return 1
    print("PASS: review_closure_audit")
    print(f"report={REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
