#!/usr/bin/env python3
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT_DIR = ROOT / "reports" / "vivado_full_impl"
CLOCK_INTERACTION = REPORT_DIR / "clock_interaction.rpt"
TIMING_SUMMARY = REPORT_DIR / "timing_summary.rpt"
OUT_PATH = ROOT / "reports" / "full_timing_exception_audit_20260628.md"


@dataclass(frozen=True)
class ClockPair:
    src: str
    dst: str
    wns: float
    tns: float
    failing_endpoints: int
    total_endpoints: int

    @property
    def key(self) -> str:
        return f"{self.src} -> {self.dst}"

    @property
    def is_user_excluded(self) -> bool:
        return self.src == "adc_clk" and self.dst == "pll_adc_clk"

    @property
    def owner_bucket(self) -> str:
        if self.is_user_excluded:
            return "user-excluded-system-bus-crossing"
        if self.src == "pll_adc_clk" and self.dst == "pll_adc_clk":
            return "pll-adc-domain-non-excluded"
        if self.src == self.dst == "adc_clk":
            return "axi-system-domain-non-excluded"
        if self.src == self.dst:
            return "other-intra-clock-non-excluded"
        return "other-inter-clock-non-excluded"


def parse_clock_interaction(text: str) -> list[ClockPair]:
    pairs: list[ClockPair] = []
    row_re = re.compile(
        r"^(?P<src>\S+)\s+"
        r"(?P<dst>\S+)\s+"
        r"rise\s+-\s+(?:rise|fall)\s+"
        r"(?P<wns>-?\d+\.\d+)\s+"
        r"(?P<tns>-?\d+\.\d+)\s+"
        r"(?P<fail>\d+)\s+"
        r"(?P<total>\d+)\s+"
    )
    for line in text.splitlines():
        match = row_re.match(line)
        if not match:
            continue
        pairs.append(
            ClockPair(
                src=match.group("src"),
                dst=match.group("dst"),
                wns=float(match.group("wns")),
                tns=float(match.group("tns")),
                failing_endpoints=int(match.group("fail")),
                total_endpoints=int(match.group("total")),
            )
        )
    return pairs


def parse_design_summary(text: str) -> tuple[float, float, int] | None:
    lines = text.splitlines()
    for idx, line in enumerate(lines):
        if "TNS Failing Endpoints" not in line:
            continue
        for candidate in lines[idx + 1 : idx + 6]:
            fields = candidate.split()
            if len(fields) >= 4:
                try:
                    return float(fields[0]), float(fields[1]), int(fields[2])
                except ValueError:
                    continue
    return None


def main() -> int:
    clock_text = CLOCK_INTERACTION.read_text(encoding="utf-8", errors="replace")
    timing_text = TIMING_SUMMARY.read_text(encoding="utf-8", errors="replace")
    pairs = parse_clock_interaction(clock_text)
    failing = [pair for pair in pairs if pair.failing_endpoints > 0]
    excluded = [pair for pair in failing if pair.is_user_excluded]
    non_excluded = [pair for pair in failing if not pair.is_user_excluded]
    summary = parse_design_summary(timing_text)

    lines = [
        "# Full Timing Exception Audit",
        "",
        "Generated by `python scripts\\audit_full_timing_exceptions.py`.",
        "",
    ]
    if summary is not None:
        wns, tns, endpoints = summary
        lines.extend(
            [
                "## Design Timing Summary",
                "",
                f"- WNS: `{wns:.3f} ns`",
                f"- TNS: `{tns:.3f} ns`",
                f"- Failing endpoints: `{endpoints}`",
                "",
            ]
        )

    lines.extend(
        [
            "## Failing Clock Pairs",
            "",
            "| Scope | Clock pair | WNS ns | TNS ns | Failing endpoints | Total endpoints |",
            "|---|---|---:|---:|---:|---:|",
        ]
    )
    for pair in failing:
        lines.append(
            f"| `{pair.owner_bucket}` | `{pair.key}` | {pair.wns:.3f} | {pair.tns:.3f} | "
            f"{pair.failing_endpoints} | {pair.total_endpoints} |"
        )

    if not failing:
        lines.append("| `clean` | none | 0.000 | 0.000 | 0 | 0 |")

    lines.extend(
        [
            "",
            "## Closure Decision",
            "",
            f"- User-excluded failing clock pairs: `{len(excluded)}`.",
            f"- Non-excluded failing clock pairs: `{len(non_excluded)}`.",
        ]
    )
    if non_excluded:
        lines.append("- Result: `NOT_CLOSED` because non-excluded timing failures remain.")
    elif excluded:
        lines.append("- Result: `CLOSED_EXCEPT_USER_EXCLUDED_ADC_TO_PLL_ADC`.")
    else:
        lines.append("- Result: `CLOSED`.")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"failing_pairs={len(failing)}")
    print(f"user_excluded_pairs={len(excluded)}")
    print(f"non_excluded_pairs={len(non_excluded)}")
    print(f"report={OUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
