#!/usr/bin/env python3
"""Audit the top-level system-bus clock source.

The PS GP0 AXI slave and the Red Pitaya system bus must use the same PLL/BUFG
125 MHz clock as the active peripheral register banks.  Driving GP0 from the
raw ADC input clock creates an avoidable adc_clk_in/adc_clk timing crossing.
"""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TOP = ROOT / "DPLL_Rewrite.srcs" / "sources_1" / "ReadPitaya" / "red_pitaya_top.v"
REPORT = ROOT / "reports" / "system_bus_clock_audit_20260630.md"


def main() -> int:
    top = TOP.read_text(encoding="utf-8", errors="replace")
    checks = [
        (
            ".axi0_clk_i(adc_clk)",
            ".axi0_clk_i(adc_clk)" in top,
            "PS GP0 AXI clock is driven by the PLL/BUFG ADC clock.",
        ),
        (
            "not .axi0_clk_i(adc_clk_in)",
            ".axi0_clk_i(adc_clk_in)" not in top,
            "PS GP0 AXI clock is no longer driven by the raw ADC input clock.",
        ),
        (
            "sys_clk alias",
            "wire              sys_clk   = ps_sys_clk" in top,
            "Top-level system bus still uses the PS GP0 clock output.",
        ),
        (
            "DPLL clk1",
            ".clk1                    (  adc_clk" in top,
            "DPLL datapath/register destination clock remains the PLL/BUFG ADC clock.",
        ),
        (
            "Freq meter clk1",
            "Digital_Freq_Meter Digital_Freq_Meter_inst" in top
            and ".clk1                    (  adc_clk" in top,
            "Frequency meter destination clock remains the PLL/BUFG ADC clock.",
        ),
    ]

    lines = [
        "# System Bus Clock Audit",
        "",
        "Generated by `python scripts/audit_system_bus_clock.py`.",
        "",
        "| Status | Check | Evidence |",
        "|---|---|---|",
    ]
    failed = False
    for name, ok, evidence in checks:
        status = "PASS" if ok else "FAIL"
        print(f"{status}: {name}")
        lines.append(f"| {status} | {name} | {evidence} |")
        failed = failed or not ok

    lines.extend(
        [
            "",
            "## Timing Intent",
            "",
            "- `red_pitaya_ps` drives `sys_clk_o` from `gp0_maxi_aclk`.",
            "- `gp0_maxi_aclk` is the `axi0_clk_i` supplied by `red_pitaya_top`.",
            "- Using `adc_clk` keeps the AXI GP0/system-bus logic on the same PLL/BUFG clock as `dpll_wrapper` and `Digital_Freq_Meter` register banks.",
            "- The prior `adc_clk_in` connection made Vivado time raw-input-clock system-bus launch registers against PLL/BUFG destination registers.",
        ]
    )
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"report={REPORT}")
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
